### ISSUE TITLE
Amber auth edit user don't work w/ method patch in form

### ISSUE THREAD

**Issue by Willyboar** [amberframework/amber#1008]
### Description

Update user profile of amber auth don't work.

### Steps to Reproduce

1. Create a new amber project with sqlite
2. Create amber auth using
    `amber g auth User`
3. Create and migrate the database.
4. I use both seed the db or register a new user.

**Expected behavior:** 
Expect to edit the user email

**Actual behavior:** 
Doesn't edited the user

**Reproduces how often:**
Always

### Versions

I am using latest versions of both Crystal and Amberframework

### Additional Information

when i change the form method in the src/views/user/edit.ecr from patch to post it works. Put and patch don't work. 

P.S It would be nice to be able to edit password too.

Thank you

**Comment by dwightwatson** [comment]
Looks like it's because slang uses the form helper but ECR just outputs a form tag with `method="patch"`, which a browser will do nothing about.

```crystal
== form(action: "/profile", method: :patch) do
```

vs

```html
<form action="/profile" method="patch">
```

I'm not actually sure how to fix it because my ECR isn't that great. I've tried this which I thought would do the job, but it fails to compile. What's the appropriate way to pass a block and output the whole thing in ECR?

```crystal
<%= form(action: "/profile", method: :patch) do %>
  <%= csrf_tag %>
  <div class="form-group">
    <input class="form-control" type="email" name="email" placeholder="Email" value="<%= user.email %>" />
  </div>
  <%= submit("Update", class: "btn btn-primary btn-sm") %>
  <%= link_to("profile", "/profile", class: "btn btn-light btn-sm") %>
<%- end %>
```

**Comment by drujensen** [comment]
@dwightwatson unfortunately, blocks are not supported in `ecr` yet.

@Willyboar `post` will create a new user, not update one.  We will need to add a hidden field `_method` with the value of `patch` for this to work.
