### ISSUE TITLE
Break up Amber::Router::Cookies module

### ISSUE THREAD

**Issue by dwightwatson** [amberframework/amber#1014]
### Description
The file for `Amber::Router::Cookies` contains multiple class and module definitions, and `Amber::Router::Cookies` may not even need to be a class itself. I think it would be beneficial for the classes and modules defined in the namespace to be broken up into individual files so that it's easier to find.

I suspect that there may be other instances of file/class inconsistencies that would be good to address as well. 

* `Amber::Router::Session::Store` located in `amber/router/session/session_store.cr`
* `Amber::Pipe` located in `amber/pipes` directory

**Comment by drujensen** [comment]
@eliasjpr wdyt?

**Comment by eliasjpr** [comment]
I thought of doing that previously. I think is a good idea

**Comment by dwightwatson** [comment]
Was looking at renaming `Amber::Pipe` to `Amber::Pipes` versus renaming the directory to `amber/pipe`.

There might be room for discussion around naming and seeing if we can develop some consistency between the module names.

![image](https://user-images.githubusercontent.com/1100408/50810631-aa81d600-135e-11e9-94e8-2cb05342e1c2.png)

One option might be to aim for singular names. It may be better to go from `Amber::Validators` to `Amber::Validation`.

```
Amber::CLI
Amber::Controller
Amber::DSL
Amber::Environment
Amber::Exception
Amber::Extension
Amber::Pipe
Amber::Router
Amber::Server
Amber::Support
Amber::Validation
Amber::WebSocket
```

**Comment by robacarp** [comment]
Some will always be singular, server for example. But I think any namespaces/folders which represent a collection of things should be plural. Validations, Extensions, Support, etc. 

Is Support plural? Whatever...

**Comment by eliasjpr** [comment]
I was working on reorganizing the project into modules as in this screenshot, the team was hesitant at the time to make these changes. Not sure how the team feels now, to slowly modularized and document the code

![screenshot from 2019-01-08 20-34-18](https://user-images.githubusercontent.com/1685772/50870190-f6477600-1384-11e9-9c81-f4f1a62d758b.png)

**Comment by eliasjpr** [comment]
I was  in the past proposing the idea to modularized the code further, to something maybe towards [this](https://github.com/eliasjpr/amber/tree/ep/cleanup-router-session/src/amber) I know the team was hesitant to do so then. I am not sure how the team feels now, to slowly organize and document the project so we can generate crystal docs.

**Comment by drujensen** [comment]
@dwightwatson I agree with @robacarp. It depends on what the purpose of the module is.  If it is name spacing a collection of items, it should be plural but if it's used to be included in a class, it's more than likely singular.

Closing this issue.  Thanks for the contribution!
