### ISSUE TITLE
Params validation should not present optional field when it not present in the input

### ISSUE THREAD

**Issue by cpunion** [amberframework/amber#1019]
### Description

Params validation should not present the optional field when it not present in the input.

### Steps to Reproduce

The following is an example:
```crystal
def user_params
  params.validation do
    optional :age
    required :name
  end
end
```

When use it validate the input `name=Don`, it returns:

```crystal
{"name" => "Don", "age" => nil}
```

**It will OVERWRITE the `age` field in the database.**

**Expected behavior:** [What you expect to happen]

Expect it returns:
```crystal
{"name" => "Don"}
```

**Actual behavior:** [What actually happens]
It returns:

```crystal
{"name" => "Don", "age" => nil}
```
**Reproduces how often:** [What percentage of the time does it reproduce?]

Always.

### Versions

Amber 0.11.2
Crystal 0.27.0

**Comment by drujensen** [comment]
@cpunion Thanks for reporting this.  Is this something you will have time to look into?

**Comment by cpunion** [comment]
Yay! My first PR. Please review.
