### ISSUE TITLE
Firefox: Auto Reload interfering with navigation

### ISSUE THREAD

**Issue by drujensen** [amberframework/amber#1023]
### Description

If auto-reload is enabled, Firefox v64 will exhibit navigation issues.  Clicking links in the navigation will not always navigate.  Submitting forms will not always redirect to expected page. 

If I disable auto-reload, the app works as expected.

### Steps to Reproduce

1. Create a new application using `amber new blog`
2. Run `amber g scaffold post title:string`
3. Run the migrations `amber db create migrate`
4. Run `amber w`
5. Try to navigate between home and posts in the navigation.  Also try submitting a new post.

**Expected behavior:** [What you expect to happen]

Navigation between home and posts would properly navigate.  Navigation after submitting forms would properly navigate to appropriate pages.

**Actual behavior:** [What actually happens]

Navigation intermittently fails.

**Reproduces how often:** [What percentage of the time does it reproduce?]

50% of the time

### Versions

Crystal 0.27.0
Amber v0.11.2
Mac OS Mojave and Firefox v64

### Additional Information

Disabling auto-reload will fix the issue

**Comment by vifreefly** [comment]
Can confirm, have the same bug in Firefox

**Comment by faustinoaq** [comment]
@drujensen Interesting, I think we have a similar issue some time ago.

BTW, How did you disable auto-reload? I just commented npm section on new `.amber.yml` settings :sparkles:
