### ISSUE TITLE
Problems with Pipe Authenticated Routes and current_user compile-time type is (User | Nil)

### ISSUE THREAD

**Issue by westonganger** [amberframework/amber#1030]
I am using the basic authenticate pipe. I cant seem to get around errors similar to the following on authenticated actions.

```
undefined method 'fetch_items' for Nil (compile-time type is (User | Nil))

      items = current_user.fetch_items
```

Since this is an authenticated action it should be assured to be not nil. However regardless even if I try to do the following it still gives the same error.

```
if !current_user.nil?
  items = current_user.fetch_items
end
```

How can I deal with this?

**Comment by westonganger** [comment]
Looks like I fixed it with some changes to the methods in ApplicationController. 

Current Instructions:

```
class ApplicationController < AmberController::Base

  def current_user : User
    context.current_user
  end

  def signed_in?
    current_user ? true : false
  end

end
```

My working solution:

```
class ApplicationController < AmberController::Base

  def current_user : User
    context.current_user || User.new
  end

  def current_user?
    context.current_user
  end

  def signed_in?
    current_user? ? true : false
  end

end
```

Maybe the solution in the docs could be updated to this. What do you think?

**Comment by drujensen** [comment]
Hi @westonganger  This is a common error you will hit using Crystal dealing with union types.

The union type `(User | Nil)` needs to be changed into `User` so you don't get the error.  `User` has the method `fetch_items` but `Nil` does not, so it throws the error.

There are several ways to do this.  The one that is recommended is to use:
```crystal
if user = current_user
  user.fetch_items
else
  # handle Nil type
end
```
The assignment will remove the `Nil` from the union and return only a `User`.  

Another option is to use `not_nil!` if you know for sure that there is no way that it can be `Nil`.  It's ugly on purpose:
```crystal
current_user.not_nil!.fetch_items
```

In Crystal, you are forced to deal with the `Nil` case.  This prevents runtime errors that are so common in Ruby.

**Comment by westonganger** [comment]
Perfect thanks for the tips.
