### ISSUE TITLE
Mailer is not included by default, must be specifically required

### ISSUE THREAD

**Issue by westonganger** [amberframework/amber#1031]
To get the mailers working I had to add the following require statements: 

```ruby
require "quartz_mailer"
require "src/mailers/**"
```

I've submitted a PR https://github.com/amberframework/docs/pull/127 to update the documentation accordingly however I do not know if this instead should have been required by default.

**Comment by drujensen** [comment]
@westonganger Did you use the generators?  It should have done this for you.

**Comment by westonganger** [comment]
Just tested both my original `v0.11.2` and the latest stable `v0.11.3`. This file is not getting generated.

**Comment by westonganger** [comment]
Oh I see. No I did not use the generator, I didn't realize there was a generator until now. It wasnt mentioned in the mailer docs.
