### ISSUE TITLE
Make Controller LAYOUT more dynamic

### ISSUE THREAD

**Issue by westonganger** [amberframework/amber#1039]
It would be nice if the controller LAYOUT was not just a static string and could be dynamic. I want to be able to assign a Proc and/or instance method name (as Symbol). Currently it appears you cannot do so.

**Comment by westonganger** [comment]
Is there not another way we could go about this at runtime instead?

**Comment by eliasjpr** [comment]
You can redefine the `LAYOUT` constant in your controllers. 

```crystal

class ApplicationController < Amber::Controller::Base
  include JasperHelpers
  LAYOUT = "example_layout.slang"
end

class OtherController < ApplicationController
  LAYOUT = "other_layout.slang"
end

```
