### ISSUE TITLE
Generated ErrorControlller does not inherit from ApplicationController but still uses the application layout

### ISSUE THREAD

**Issue by westonganger** [amberframework/amber#1041]
When generating the Error controller, by default uses the `application.slang` layout file. So suddenly the compiler started complaining about missing methods in my layout file that are defined in ApplicationController but not defined in ErrorController.

It turned out the errors popped up because the ErrorController does not inherit from ApplicationController. I am fine with errors happening after I change code myself but when a generator does it I am left questioning what the heck happened.

Here are two possible solutions
- Preferred (If Possible) - Somehow have the ErrorController inherit from ApplicationController by default
- Alternative - Make ErrorController have its own `error.slang` layout file by default. This way if the user decides to change the layout to the application layout they will have more of an understanding why the errors started occurring.

**Comment by elorest** [comment]
Option 1 probably makes the most sense since it's nice if error pages still look the same and allow you to navigate out without having to go back.

**Comment by elorest** [comment]
@westonganger Are the missing methods in your layout created by you or generated by default? Last time I checked application layout doesn't depend on any methods in application controller by default. If so then this is probably something that should be fixed by end users on a case by case basis. If it happens by default then it should be fixed in amber.

**Comment by westonganger** [comment]
@elorest the missing methods were added by me but again this happens after a generator has been used making it super confusing.

**Comment by robacarp** [comment]
I think it makes sense for ErrorController to inherit from ApplicationController

**Comment by eliasjpr** [comment]
I think we can create a module for these error helper methods. WDYT?

**Comment by westonganger** [comment]
Yes that sounds perfect

```ruby
class ErrorController < ApplicationController
  include Amber::Controller::Helpers::ErrorControllerHelpers

end

module Amber::Controller::Helpers::ErrorControllerHelpers
  LAYOUT = "application.slang"

  def initialize(@context : HTTP::Server::Context, @ex : Exception)
    super(@context)
    @context.response.content_type = content_type
  end

  def forbidden
    render("forbidden.slang")
  end

  def not_found
    render("not_found.slang")
  end

  def internal_server_error
    render("internal_server_error.slang")
  end

  def bad_request
    render("bad_request.slang")
  end

  private def content_type
    if context.request.headers["Accept"]?
      request.headers["Accept"].split(",").first
    else
      "text/plain"
    end
  end

  private def response_format
    case content_type
    when "application/json"
      {"error": @ex.message}.to_json
    when "text/html"
      html_response
    else
      @ex.message
    end
  end

  private def html_response
    if Amber.env.development?
      Amber::Exceptions::Page.for_runtime_exception(context, @ex).to_s
    else
      "<html><body><pre>#{@ex.message}</pre></body></html>"
    end
  end
end
```
