### ISSUE TITLE
Missing space between navbar and alert on v0.11.3

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#1046]
### Description

New version released 7 days ago includes amber logo on navbar (see #1005 ), although, it removes the space between navbar and alert boxes.

### Steps to Reproduce

1. `amber new Example -d sqlite`
2. `cd Example`
3. `amber g scaffold Post title:string content:text`
4. `amber watch`
5. Go to http://0.0.0.0:3000/posts and create a new post

**Expected behavior:** space between navbar and alert box

![image](https://user-images.githubusercontent.com/3067335/51428108-ea05b900-1bcd-11e9-8e79-47880184da15.png)

**Actual behavior:** no actual space between navbar and alert box

![image](https://user-images.githubusercontent.com/3067335/51428081-9abf8880-1bcd-11e9-81da-b9755e538b33.png)

**Reproduces how often:** 100%

### Versions

```
[tiktok@pc Example]$ shards --version
Shards 0.8.1 (2018-06-19)
[tiktok@pc Example]$ crystal -v
Crystal 0.27.0 (2018-11-02)

LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu
[tiktok@pc Example]$ amber -v
Amber CLI (amberframework.org) - v0.11.3
[tiktok@pc Example]$ npm -v
6.5.0
```

### Additional Information

I added a `margin-top: 1rem` to `.alert`, WDYT?

![image](https://user-images.githubusercontent.com/3067335/51428148-4c5eb980-1bce-11e9-9582-7eb403571e10.png)

Ping @dwightwatson

**Comment by dwightwatson** [comment]
Would it be better to add `.mb-3` to the navbar so that it has a bottom margin? Means we don't need to customise Bootstrap's alert styles, and it won't look odd if multiple alerts are stacked.

**Comment by faustinoaq** [comment]
@dwightwatson Thank you for you suggestion, I already sent a PR, see #1059 :+1:
