### ISSUE TITLE
Unhandled exception: No registered adapter with the name 'pg' (Exception)

### ISSUE THREAD

**Issue by gdonald** [amberframework/amber#1049]
I tried this getting started guide:

https://docs.amberframework.org/amber/getting-started

When I do `amber watch` I get an endless stream of:

    Unhandled exception: No registered adapter with the name 'pg' (Exception)
      from ~Pet::adapter:init
      from lib/jasper_helpers/src/jasper_helpers/tags.cr:0:1 in '__crystal_main'
      from /usr/local/Cellar/crystal/0.27.0/src/crystal/main.cr:97:5 in 'main_user_code'
      from /usr/local/Cellar/crystal/0.27.0/src/crystal/main.cr:86:7 in 'main'
      from /usr/local/Cellar/crystal/0.27.0/src/crystal/main.cr:106:3 in 'main'
    05:55:08 Watch run  | (INFO) All processes died. Trying to restart...

My database connectivity works:

    > amber db drop create migrate
    05:59:41 Database   | (INFO) Dropped database amber_test_development
    05:59:41 Database   | (INFO) Created database amber_test_development
    05:59:41 Database   | (INFO) Migrating db, current version: 0, target: 20190124173747704
    05:59:41 Database   | (INFO) OK   20190124173747704_create_pet.sql

The database migration succeeded:

    > psql amber_test_development
    psql (11.1)
    Type "help" for help.

    amber_test_development=# \d
                       List of relations
     Schema |           Name            |   Type   | Owner
    --------+---------------------------+----------+-------
     public | micrate_db_version        | table    | gd
     public | micrate_db_version_id_seq | sequence | gd
     public | pets                      | table    | gd
     public | pets_id_seq               | sequence | gd
    (4 rows)

I have 'pg' in my shard.yml:

    cat shard.yml |grep pg
      pg:
        github: will/crystal-pg

And `shards install` succeeds and the output includes 'Using pg (0.15.0)'

My crystal version:

    > crystal version
    Crystal 0.27.0 (2018-11-04)

    LLVM: 6.0.1 
    Default target: x86_64-apple-macosx

Any idea?  Thanks.

**Comment by gdonald** [comment]
Found Lucky, using it instead.  Closing issue.  Thanks anyway!

**Comment by elorest** [comment]
Could you tell me what version of amber you're using. I just tried the latest version from a couple weeks ago and I'm not having that issue. Are you in MacOS or Linux? I'd definitely like to solve this issue for future users even if it's too late for you.
