### ISSUE TITLE
Error when installing Amber on Mac OS Mojave via Homebrew

### ISSUE THREAD

**Issue by JRiggles** [amberframework/amber#1050]
### Preface
This issue replicates #979, but I have found a different solution which I hope others may find useful.

### Description
An error occurs when installing Amber on Mac OS Mojave (10.14.2) via Homebrew (1.9.3)

Following the install procedure outlined on https://docs.amberframework.org/amber/getting-started produces the error

FWIW, I am using Fish Shell (3.0.0) https://fishshell.com
### Steps to Reproduce

*Follow install commands...*
```
brew tap amberframework/amber
brew install amber
```
*...receive error*
```
Error: amber: /usr/local/Homebrew/Library/Taps/amberframework/homebrew-amber/Formula/amber.rb:4: syntax error, unexpected <<, expecting keyword_end
<<<<<<< HEAD
  ^
/usr/local/Homebrew/Library/Taps/amberframework/homebrew-amber/Formula/amber.rb:7: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/amberframework/homebrew-amber/Formula/amber.rb:10: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Creating homebrew tap for amber
  ^
/usr/local/Homebrew/Library/Taps/amberframework/homebrew-amber/Formula/amber.rb:10: syntax error, unexpected '\n', expecting &. or :: or '[' or '.'
/usr/local/Homebrew/Library/Taps/amberframework/homebrew-amber/Formula/amber.rb:30: syntax error, unexpected keyword_do_block, expecting keyword_end
    ].each do |path|
             ^
/usr/local/Homebrew/Library/Taps/amberframework/homebrew-amber/Formula/amber.rb:31: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
      assert_match path, output
                       ^
/usr/local/Homebrew/Library/Taps/amberframework/homebrew-amber/Formula/amber.rb:31: syntax error, unexpected '\n', expecting '='
```

### Solution
Using ```brew tap amberframework/amber --full```
prior to ```brew install amber```
solves the problem and Amber Framework is installed without issues.

### Versions

OS: Mac OS Mojave 10.14.2
Package Manager: Homebrew 1.9.3
Fish: 3.0.0
Amber: Latest
Crystal: Latest (0.27.0)

**Comment by elorest** [comment]
There are merge conflicts in your local version of the formula. Deleting the formula and re tapping would also solve.

**Comment by JRiggles** [comment]
@elorest I did try to install Amber from a clean slate with `brew untap` and `brew uninstall`, but didn't have any luck. That said, you still have a point.

**Comment by elorest** [comment]
Brew untap doesn't remove the formula if it's already been corrupted. I'm not sure why but I've had this issue multiple times over the years with homebrew.

FYI: I usually just run `brew install amberframework/amber/amber` instead of running tap and install. Won't solve your issue but still saves time.
