### ISSUE TITLE
Trouble following the docs

### ISSUE THREAD

**Issue by peoplenamed** [amberframework/amber#1058]
I am having a bit of trouble following the [Amber docs](https://docs.amberframework.org/amber/cookbook/file-upload). I understand they may be outdated.

env.params throws an error. 
`image = env.params.files["file"]`
> in src/controllers/editor_controller.cr:8: undefined local variable or method 'env'

I am getting another error trying to inspect the params.
undefined method 'to_unsafe_h' for Amber::Router::Params
params.to_unsafe_h produces an error when compiled. 
I was able to get around this by using raw_params. But when I inspect the params from a form upload all I see is the name of the file.

`form action="/editor/open" id="open_editor_file"`
  `  input type="file" name="file"`
  `  button type="submit"`

`puts params.raw_params.to_h`
`files = params.files`
`puts files`
> {"file" => "coffeMug1.svg"}
> {}

**Comment by elorest** [comment]
Thanks. I nave no idea when `env.params` would have been added to the docs. If you could submit a PR to fix the docs I'd really appreciate it. `env` has never been an object on controller base or context.

Try `context.params.files["file"]`. You could also call `to_h` on that. Thanks a lot for submitting. Let me know if you still have issue with that. I'm working to add full file support to the generators.

**Comment by peoplenamed** [comment]
I figured out why my form did not submit. My mistake! I needed to add enctype="multipart/form-data" (What a noob)

**Comment by peoplenamed** [comment]
[pull request](https://github.com/amberframework/docs/pull/139)

**Comment by elorest** [comment]
Thanks! 👍
