### ISSUE TITLE
"Read Amber quick start guide" link is a 404

### ISSUE THREAD

**Issue by alex-min** [amberframework/amber#1062]
### Description

The link "Read Amber quick start guide" on the Readme goes to a 404.

### Steps to Reproduce

1. Click on the "Read Amber quick start guide" link on the Readme

**Expected behavior:** It should go to some quick start guide page.

**Comment by faustinoaq** [comment]
Hi @alex-min Do you mean this one https://docs.amberframework.org/amber/getting-started ?

Can you provide a link? :sweat_smile:

**Comment by elorest** [comment]
I checked this morning and it worked fine. @faustinoaq since you're here. Did you see my comments about gitbook?

**Comment by alex-min** [comment]
Ah really it's this link? I would have done a PR but I did not know which one it was supposed to go to.

https://docs.amberframework.org/amber/getting-started/quick-start is the one on the readme
and maybe https://docs.amberframework.org/amber/getting-started is the one which should be there then?

**Comment by faustinoaq** [comment]
> Did you see my comments about gitbook?

Not yet, let me check, Thank you for pointing it out! :+1:
