### ISSUE TITLE
i18n files do not reload on changes

### ISSUE THREAD

**Issue by alex-min** [amberframework/amber#1070]
Hi everyone,

I've noticed the i18n files do not reload when you save them, you have to run "amber watch" again to make the changes available.

Would it be possible to recompile them if they changed? I need to check the current code on how it's done.

**Comment by robacarp** [comment]
@alex-min it is definitely possible. I think you can update your .amber.yml config to instruct the watch command to pay attention to the i18n files.

**Comment by kvirani** [comment]
This is fixed in #1071 so can we close this issue?

**Comment by alex-min** [comment]
yep sorry, forgot to close it
