### ISSUE TITLE
Requiring application.cr in seeds.cr causes Watcher output

### ISSUE THREAD

**Issue by kvirani** [amberframework/amber#1086]
### Description

When running the seeds file, developer sees output regarding `Watcher` if they require `application.cr` first (in order to load models, etc first)

```terminal
> amber db seed    
10:43:56 Watcher    | (INFO) Watching 11 files (browser reload)...
hello from seeds
10:43:56 Database   | (INFO) Seeded database
```

db/seeds.cr:
```crystal
require "../config/application"
puts "Hello from seeds"
```

This is not a blocker and thus a low priority issue.

### Steps to Reproduce

1. Create a seeds file (I created it manually): `touch db/seeds.cr`
2. Add reference to a model in the seeds file (eg: `puts User.count`)
3. Run `amber db seed` in terminal
4. Notice the error `undefined constant User`
5. To fix this, prepend the line `require "../config/application"` to the seeds file
6. Run and notice the error is fixed but the output includes mention of `Watcher`, as stated in the issue desc

**Expected behavior:** 

Seeds file should run.

**Actual behavior:**

Seeds file _does_ run, but mentions `Watcher` in the output.

**Reproduces how often:** 100%

### Versions

```
Crystal 0.27.2 (2019-02-05)

LLVM: 3.9.1
Default target: x86_64-apple-macosx
```

### Additional Information

_Disclaimer: I am new to Amber (but have been using Rails since 2007) so it may be a case of me misunderstanding which file I should require (in order to boot up the Amber app/env so that we can reference the models) prior to running the seeds._

**Comment by elorest** [comment]
Fixed with PR #1088
