### ISSUE TITLE
Route Constraints

### ISSUE THREAD

**Issue by Blacksmoke16** [amberframework/amber#1089]
Since https://github.com/amberframework/amber-router/pull/12 was merged Amber supports adding constraints to its routes, like https://guides.rubyonrails.org/routing.html#segment-constraints.  

However there is not currently a method of defining these on a given route/resource.

Should be pretty simple like
```crystal
get "/user/:id", UserController, :show, constraints: {id: /\d+/}
```

Then just pass the constraints to the router when adding the route.

**Comment by kvirani** [comment]
I'd like to take a stab at this, and in doing so get more comfortable with the amber source code. No guarantees though.
