### ISSUE TITLE
Consider adding a guide or support for FormBuilder.cr

### ISSUE THREAD

**Issue by westonganger** [amberframework/amber#1097]
I would like to propose an addition to the documentation as a recommended shard with a guide (which I would provide PR)

**Proposed Shard:** FormBuilder.cr - https://github.com/westonganger/form_builder.cr

> Dead simple HTML form builder for Crystal with built-in support for many popular UI libraries such as Bootstrap. Works well with your favourite Crystal web framework such as Kemal, Amber, or Lucky.

This appears to be the only shard dedicated **solely** to form building for the language so far. The only other libraries with minimal form building support seem to be `jasper-helpers` and https://github.com/imdrasil/view_model.cr both of which I consider form building to be somewhat of a afterthought as they are both kitchen sink libraries.

I created this shard to address a need in the Crystal community for a complete HTML form builder that also considers theme/css support as a first class citizen.

If it matters for any credibility it was added to the awesome-crystal list: https://github.com/veelenga/awesome-crystal/pull/395

**Comment by imdrasil** [comment]
Hi there. If you would like I can easily extract all form-related functionality of https://github.com/imdrasil/view_model.cr to a separate gem (which honestly I was going to do but had no own use cases / Github issues for this)

**Comment by westonganger** [comment]
A PR providing this guide has now been submitted at https://github.com/amberframework/docs/pull/162
