### ISSUE TITLE
Docker tag for 0.28.0 missing

### ISSUE THREAD

**Issue by drhuffman12** [amberframework/amber#1099]
### Description

Using the latest version of Amber (0.28.0), when you do `amber new some_app_name`, it generates (among other files) a docker file w/ `FROM amberframework/amber:v0.28.0`. The `0.28.0` tag is missing from https://hub.docker.com/r/amberframework/amber/tags .

### Steps to Reproduce

1. `amber new some_app_name`
2. `cd some_app_name`
3. `docker-compose build`

**Expected behavior:** [What you expect to happen]

The container for the initialized app should build.

**Actual behavior:** [What actually happens]

```
$ docker-compose build
db uses an image, skipping
Building app
Step 1/7 : FROM amberframework/amber:v0.28.0
ERROR: Service 'app' failed to build: manifest for amberframework/amber:v0.28.0 not found
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```
$ amber --version
Amber CLI (amberframework.org) - v0.28.0

$ crystal --version
Crystal 0.28.0 [639e4765f] (2019-04-17)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

$ cat /etc/linuxmint/info
RELEASE=19.1
CODENAME=tessa
EDITION="MATE"
DESCRIPTION="Linux Mint 19.1 Tessa"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=https://www.linuxmint.com/rel_tessa_mate_whatsnew.php
RELEASE_NOTES_URL=https://www.linuxmint.com/rel_tessa_mate.php
USER_GUIDE_URL=https://www.linuxmint.com/documentation.php
GRUB_TITLE=Linux Mint 19.1 MATE
```

**Comment by rmarronnier** [comment]
Also the dockerfile still points to crystal 0.27.0
`FROM crystallang/crystal:0.27.0

# Install Dependencies
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && apt-get install -y --no-install-recommends libpq-dev libsqlite3-dev libmysqlclient-dev libreadline-dev git curl vim netcat

# Install Node
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs

WORKDIR /opt/amber

# Build Amber
ENV PATH /opt/amber/bin:$PATH
COPY . /opt/amber
RUN shards build amber

CMD ["crystal", "spec"]
`
