### ISSUE TITLE
Unhandled exception: cast from Nil to String failed

### ISSUE THREAD

**Issue by jaydorsey** [amberframework/amber#1101]
### Description

I'm following the amber getting started guide. Macos 10.14.4. After the `brew install amber` step I run the `amber new pet-tracker` command and get the error noted below.

```
Unhandled exception: cast from Nil to String failed, at /usr/local/Cellar/crystal/0.28.0/src/yaml/any.cr:176:5:176 (TypeCastError)
  from YAML::Any#as_s:String
  from Amber::CLI::Config::get_name:String
  from Sentry::SentryCommand::Options::defaults:NamedTuple(name: String, process_name: String, build: String, run: String, watch: Array(String))
  from __crystal_main
  from Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil
  from Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32
  from main
```

I receive the same error when running any amber command (`amber`, `amber --version`, etc.) I've tried uninstalling & reinstalling amber with no luck.

### Versions

The crystal version I have installed is the version installed via homebrew:

```
Crystal 0.28.0 (2019-04-24)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

I'm unable to provide the amber version due to the error, but the homebrew output (no errors) looks like it was probably 0.28.0:

```
==> Installing amber from amberframework/amber
==> Downloading https://github.com/amberframework/amber/archive/v0.28.0.tar.gz
Already downloaded: /Users/jay/Library/Caches/Homebrew/downloads/5d69471e30abf4be4ffd694b512cecaab22f84a174f4a14e92a4a3c4e2940577--amber-0.28.0.tar.gz
==> shards install
==> make install PREFIX=/usr/local/Cellar/amber/0.28.0
🍺  /usr/local/Cellar/amber/0.28.0: 5 files, 6.9MB, built in 1 minute 10 seconds
```

### Additional Info

I also tried building amber from the repo (master branch) with `shards install`, then `make` and `make install`. It built the binary & put it in `/usr/local/bin/amber`. I can actually run \*`amber --version` with that binary.

I just noticed I can run `amber --version` when I'm in the amber repo that I cloned and built the application in. If I change to a different directory, the error returns. It looks like something may not have been linked properly? I may have missed a step by rebuilding, but the homebrew binary shows the same error. Thanks for any pointers

**Comment by jaydorsey** [comment]
I'm closing this issue, because my issue appears to have gone away. I made no changes since I reported it last night, other than updating my $PATH to include the path to llvm@6. I'm assuming that may have been the missing link

    export PATH="/usr/local/opt/llvm@6/bin:$PATH"

**Comment by lukad** [comment]
I'm having the same issue with the latest crystal and amber version installed via homebrew.

```
$ crystal --version
Crystal 1.4.1 (2022-04-22)

LLVM: 13.0.1
Default target: aarch64-apple-darwin21.4.0
```

```
$ amber --help
Unhandled exception: cast from Nil to String failed, at /opt/homebrew/Cellar/crystal/1.4.1/src/yaml/any.cr:168:5:168 (TypeCastError)
  from /opt/homebrew/Cellar/amber/1.2.1/bin/amber in 'Exception::CallStack::unwind:Array(Pointer(Void))'
  from /opt/homebrew/Cellar/amber/1.2.1/bin/amber in 'Exception::CallStack#initialize:Array(Pointer(Void))'
  from /opt/homebrew/Cellar/amber/1.2.1/bin/amber in 'Exception::CallStack::new:Exception::CallStack'
  from /opt/homebrew/Cellar/amber/1.2.1/bin/amber in 'raise<TypeCastError>:NoReturn'
  from /opt/homebrew/Cellar/amber/1.2.1/bin/amber in 'YAML::Any#as_s:String'
  from /opt/homebrew/Cellar/amber/1.2.1/bin/amber in 'Amber::CLI::Config::get_name:String'
  from /opt/homebrew/Cellar/amber/1.2.1/bin/amber in 'Sentry::SentryCommand::Options::defaults:NamedTuple(name: String, process_name: String, build: String, run: String, watch: Array(String))'
  from /opt/homebrew/Cellar/amber/1.2.1/bin/amber in '__crystal_main'
  from /opt/homebrew/Cellar/amber/1.2.1/bin/amber in 'Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil'
  from /opt/homebrew/Cellar/amber/1.2.1/bin/amber in 'Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32'
  from /opt/homebrew/Cellar/amber/1.2.1/bin/amber in 'main'
```
