### ISSUE TITLE
Option in amber.yml to disable spec generation

### ISSUE THREAD

**Issue by nathanielsuchy** [amberframework/amber#1118]
Some projects choose to not unit tests (specs) or use a third party option rather than Amber's build in spec system. It would be nice to have an option in `amber.yml` and at the new app create generator to disable the specs generation. Thoughts?

**Comment by drujensen** [comment]
We recommend that you have specs so the default generators will always provide them.  

Eventually, with recipes, you will be able to design your own generators and remove specs if you wish.  @damianham and I have been discussing how this might work in #1079

**Comment by nsuchy** [comment]
> We recommend that you have specs so the default generators will always provide them.
> 
> Eventually, with recipes, you will be able to design your own generators and remove specs if you wish. @damianham and I have been discussing how this might work in #1079

Providing them by default is understandable, but Amber should still support user choice and give an opt-out ability.
