### ISSUE TITLE
Should we update the github used by to use shards

### ISSUE THREAD

**Issue by wontruefree** [amberframework/amber#1119]
I mostly use system package managers to install amber but for the purpose of github should we update the package manager to say something about shards? 

Since you cannot install amber via the shards commandline eg. `shards install amberframework` I dont really know what this should say.

<img width="432" alt="Screen Shot 2019-06-20 at 4 28 27 PM" src="https://user-images.githubusercontent.com/1045155/59882863-f5c1fb00-9378-11e9-9775-a46680ad8467.png">

**Comment by drujensen** [comment]
@wontruefree I checked and there is no way of fixing this.  We cannot disable it or control it.  It is reading from the package.json and assuming the project is Node/JS.

**Comment by wontruefree** [comment]
that is a bummer

**Comment by wout** [comment]
Shouldn't Github be notified about this issue? By now, they should be able to detect a Crystal project by its `shard.yml` file.
