### ISSUE TITLE
Error: abstract `def Enumerable(T)#each(&block)` must be implemented by Callback::ResultSet(T)

### ISSUE THREAD

**Issue by dcalixto** [amberframework/amber#1124]
This `Error: abstract def Enumerable(T)#each(&block) must be implemented by Callback::ResultSet(T)
`
Showed on the log on the fresh install of the framework by the [](https://docs.amberframework.org/amber/getting-started)

guide!

![amber](https://user-images.githubusercontent.com/1009077/62410607-3dfe4b00-b5be-11e9-8194-4babe59cbc2d.png)

**Comment by alex-lairan** [comment]
Hi, you are using Crystal 0.30.

This version have a breaking change with modules and abstacts methods with return type. 

Use the 0.29 version and you will not have problems :) 

Maybe next week Amber will be 0.30 ready.

You can follow this pull request https://github.com/amberframework/amber/pull/1123

**Comment by dcalixto** [comment]
@alex-lairan , ok thank you :)
