### ISSUE TITLE
How do I set SameSite cookies?

### ISSUE THREAD

**Issue by irlcatgirl** [amberframework/amber#1136]
Is it possible to require SameSite cookies? I'd like to add them as an extra protection against CSRF attacks. If this isn't currently built into Amber could it be added as a setting?

**Comment by eliasjpr** [comment]
Create a Cookie object as shown here https://crystal-lang.org/api/0.33.0/HTTP/Cookie.html then and then write it `cookies[:commenter_name]= cookie_object`
