### ISSUE TITLE
Unhandled exception on HTTP::Handler when upgrading from 0.11 to 0.30

### ISSUE THREAD

**Issue by faissaloo** [amberframework/amber#1137]
### Description

I'm in the process of migrating from Amber 0.11 to 0.30, I've made the changes described [here](https://github.com/amberframework/amber/releases/tag/v0.30.0) but while it compiles fine I get the following error in the terminal whenever I try to access a page:  
```
Unhandled exception on HTTP::Handler
Error reading file: Is a directory (Errno)
  from /usr/share/crystal/src/crystal/system/unix/file_descriptor.cr:59:9 in 'unbuffered_read'
  from /usr/share/crystal/src/io/buffered.cr:214:5 in 'fill_buffer'
  from /usr/share/crystal/src/io/buffered.cr:103:7 in 'peek'
  from /usr/share/crystal/src/io.cr:632:37 in 'gets'
  from /usr/share/crystal/src/io.cr:605:5 in 'gets'
  from /usr/share/crystal/src/io.cr:575:5 in 'gets'
  from /usr/share/crystal/src/file.cr:918:18 in 'read_lines'
  from /usr/share/crystal/src/file.cr:653:3 in 'read_lines'
  from lib/exception_page/src/exception_page/frame.cr:11:7 in 'snippets'
  from lib/exception_page/src/exception_page.cr:645:29 in 'to_s'
  from /usr/share/crystal/src/object.cr:96:7 in 'to_s'
  from lib/amber/src/amber/controller/error.cr:49:11 in 'html_response'
  from lib/amber/src/amber/controller/error.cr:41:11 in 'response_format'
  from lib/amber/src/amber/controller/error.cr:25:9 in 'internal_server_error'
  from lib/amber/src/amber/pipes/error.cr:23:9 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call_next'
  from lib/citrine-i18n/src/citrine-i18n/handler.cr:16:9 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call_next'
  from lib/amber/src/amber/pipes/powered_by_amber.cr:6:9 in 'call'
  from lib/amber/src/amber/pipes/pipeline.cr:20:11 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:39:11 in 'process'
  from /usr/share/crystal/src/http/server/request_processor.cr:16:3 in 'process'
  from /usr/share/crystal/src/http/server.cr:462:5 in 'handle_client'
  from /usr/share/crystal/src/http/server.cr:428:13 in '->'
  from /usr/share/crystal/src/fiber.cr:255:3 in 'run'
  from /usr/share/crystal/src/fiber.cr:47:34 in '->'
  from ???
```

### Steps to Reproduce

1. `git clone https://github.com/faissaloo/ratmachine/ -b crystal-0.3`
2. Run `shards build`
3. Run `bin/ratmachine`
4. Attempt to access `localhost:3000`
5. You will get a 500 error and the console will show

**Expected behavior:** My program should compile

**Actual behavior:** I get an error

**Reproduces how often:** 100%

### Versions

Amber CLI (amberframework.org) - v0.30.0
Crystal 0.30.1 [5e6a1b672] (2019-08-12)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
Distributor ID: Ubuntu
Description: Pop!_OS 18.04 LTS
Release: 18.04

**Comment by drujensen** [comment]
It looks like you have the error pages installed.  Can you try commenting out the Error Pipe in the routes.cr?  `lib/amber/src/amber/pipes/error.cr:23:9 in 'call'`  You may need to rerun the generator for that.

**Comment by faissaloo** [comment]
Yeah commenting out the error pipes worked. How do I regenerate them?

**Comment by elorest** [comment]
Try making a fresh project and copying them over.
