### ISSUE TITLE
Remove Cluster Option

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#1148]
# Remove Cluster Option
With the addition of the `-Dpreview_mt` crystal cluster option will not be necessary. Instead we can use the process count setting to easily set the `CRYSTAL_WORKERS` environment variable when starting the amber server.

**Comment by elorest** [comment]
I think we should wait for multithreading to be out of preview before removing a feature used by people in production.

**Comment by elorest** [comment]
Let's a deprecation warning when clustering is turned on. I can do that.

**Comment by eliasjpr** [comment]
Yes, this was a ticket to follow up when multithreading is ready

**Comment by elorest** [comment]
Perfect.

**Comment by codered** [comment]
Based on the last comment in #1157 , this ticket can be closed. There is no action from the Amber team at this time.
