### ISSUE TITLE
no database.yml in config

### ISSUE THREAD

**Issue by bnsv** [amberframework/amber#1156]
### Description
This is my first installation of Amber. I follow the instruction from the docs. Everything went well until creating database.  The connection is unsuccessful. It is said to change my preference in config/database.yml. But when i look into config directory there is no database.yml. There is only database.cr. No other yml files at all in this directory.

### Steps to Reproduce

**Expected behavior:**
Database.yml should exists in config directory. Should I manually make one?

**Actual behavior:** [What actually happens]
no any .yml files. only a database.cr

**Reproduces how often:** [What percentage of the time does it reproduce?]
I don't know

### Versions
Amber CLI (amberframework.org) - v0.31.0
Crystal 0.31.1 [0e2e1d067] (2019-09-30)
LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
Linux Kubuntu 18 LTS

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by elorest** [comment]
Database settings are in `config/environments/[env].yml`. If the docs say otherwise they're a couple years old. I'd love it if you could fix that. Thanks.

**Comment by bnsv** [comment]
Great Elorest. It turns out that my pdf doc is the old one, how can I missed that. I should check the online docs at first place. Thanks a lot.
