### ISSUE TITLE
generated Dockerfile points to non existent docker image

### ISSUE THREAD

**Issue by jondruse** [amberframework/amber#1158]
### Description

After generating a new amber application, the Dockerfile included:

`FROM amberframework/amber:v0.31.0`

which doesn't exist on docker hub and causes docker-compose to fail.

### Steps to Reproduce

1. brew tap amberframework/amber
2. brew install amber
3. amber new test_app
4. cd test_app
5. docker-compose build

**Expected behavior:** docker to build

**Actual behavior:** ERROR: Service 'migrate' failed to build: manifest for amberframework/amber:v0.31.0 not found: manifest unknown: manifest unknown

### Versions

Amber CLI (amberframework.org) - v0.31.0

### Additional Information

Using MacOS Mojave 10.14.6.

Also, the docker-compose.yml that's generated is not what's described in the [documentation](https://docs.amberframework.org/amber/guides/docker)

**Comment by drujensen** [comment]
Done.  I have been having issues with DockerHub lately.  Hoping github's package manager releases soon.  🙏
