### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by LeandroRezendeCoutinho** [amberframework/amber#1160]
Building migrate
Step 1/7 : FROM amberframework/amber:v0.30.1
ERROR: Service 'migrate' failed to build: manifest for amberframework/amber:v0.30.1 not found: manifest unknown: manifest unknown

SO: Manjaro

Steps: Just run > docker-compose up

**Comment by drujensen** [comment]
try v0.31.0 https://hub.docker.com/r/amberframework/amber/tags
