### ISSUE TITLE
libssl issue on MacOS Catalina (maybe as early as Mohave)

### ISSUE THREAD

**Issue by seanwatters** [amberframework/amber#1163]
### Description

I'm currently having an issue when attempting to run Amber projects after creation w/ `amber w` where I get the error 

```
ld: library not found for -lssl (this usually means you need to install the development package for libssl)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o '/Users/username/Documents/development/asdf/bin/asdf'  -rdynamic  -lyaml -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lpcre /usr/local/Cellar/crystal/0.31.1/embedded/lib/libgc.a -lpthread /usr/local/Cellar/crystal/0.31.1/src/ext/libcrystal.a -levent -liconv -ldl -L/usr/local/Cellar/crystal/0.31.1/embedded/lib -L/usr/lib -L/usr/local/lib`
```

### Steps to Reproduce

Create an Amber project running MacOS Catalina and run `amber w`

**Expected behavior:** 

Start up Amber project on `localhost:3000`

**Actual behavior:**

I get the error message above

**Reproduces how often:**

100% on newly generated projects

### Versions

Current version

### Additional Information

I have a fix that works for now. If you have `libressl` installed with 

```
brew install libressl
```

You can run the commands:

```
export CPPFLAGS="-I/usr/local/opt/libressl/include"

export PKG_CONFIG_PATH="/usr/local/opt/libressl/lib/pkgconfig"
```

And the project will run fine.

**Comment by g33kidd** [comment]
Can confirm this is also occurring in Mojave. Currently running MacOS 10.14.4 and running into the same issue when running `amber watch`.

**Comment by wontruefree** [comment]
Does this need to be updated?
https://crystal-lang.org/install/on_mac_os/

**Comment by eliasjpr** [comment]
Please follow the instructions here https://crystal-lang.org/install/on_mac_os/
