### ISSUE TITLE
Fix specs for `Redirector.from_controller_action` class method

### ISSUE THREAD

**Issue by drujensen** [amberframework/amber#1193]
### Description

Specs are failing in Travis for creating a `Redirector` using `from_controller_action`.  These tests passed on my local MacBook Pro.

https://github.com/amberframework/amber/blob/master/spec/amber/controller/redirect_spec.cr#L51

Look into fixing them.

**Comment by OpakAlex** [comment]
@drujensen can i pick up this one? can you assign to me?

**Comment by drujensen** [comment]
thanks @OpakAlex !
