### ISSUE TITLE
AMBER_ENV=production causes Missing named tuple key: "production"

### ISSUE THREAD

**Issue by faissaloo** [amberframework/amber#1200]
### Description

When trying to start my application in production mode I get an error and it does not start

### Steps to Reproduce

1. Start application in production mode

**Expected behavior:** The application starts as usual

**Actual behavior:** The following error:
```
Unhandled exception: Missing named tuple key: "production" (KeyError)
  from /home/faissaloo/.asdf/installs/crystal/0.30.1/share/crystal/src/named_tuple.cr:103:37 in 'logger'
  from /home/faissaloo/ratmachine/config/initializers/database.cr:4:27 in '__crystal_main'
  from /home/faissaloo/.asdf/installs/crystal/0.30.1/share/crystal/src/crystal/main.cr:47:14 in 'main'
  from /home/faissaloo/.asdf/installs/crystal/0.30.1/share/crystal/src/pointer.cr:80:3 in '__crystal_personality'
  from _start
  from ???
```

**Reproduces how often:** Unknown

### Versions

Crystal 0.30.1 [5e6a1b672] (2019-08-12)  
LLVM: 4.0.0  
Default target: x86_64-unknown-linux-gnu  
Amber CLI (amberframework.org) - v0.31.0  
Distributor ID:	Ubuntu  
Description:	Ubuntu 20.04 LTS  
Release:	20.04  
Codename:	focal

**Comment by drujensen** [comment]
Hi @faissaloo Can you confirm you have a `./config/environments/production.yml` and a `database_url` set?  It looks like it can't find that setting for production.

**Comment by faissaloo** [comment]
I have a `config/environments/.production.enc` and it has a `database_url` set, I was under the impression that it should be trying to decrypt it?

**Comment by drujensen** [comment]
@faissaloo Ok. I tried this using Crystal 0.34.0 with no issues.

Can you provide `/config/initializers/database.cr:4:27`?  This is where the error is occuring and I'm wondering why its not finding the key `production`

**Comment by faissaloo** [comment]
That file is just:
```
require "granite/adapter/pg"

Granite::Connections << Granite::Adapter::Pg.new(name: "pg", url: Amber.settings.database_url)
Granite.settings.logger = Amber.settings.logger.dup
Granite.settings.logger.progname = "Granite"
```
I'll try see if I can get myself on Crystal 0.34.0

**Comment by faissaloo** [comment]
I managed to get myself on 0.33.0 but it still has the same issue

**Comment by faissaloo** [comment]
How strange, removing `Granite.settings.logger = Amber.settings.logger.dup` seems to stop it breaking but I'm not quite sure why that line isn't working

**Comment by faissaloo** [comment]
Ok I've fixed it, turns out because I upgraded from an older version of Amber things were in the wrong place. When looking at a newly created project in 0.33.0 there is a new file `config/settings.cr` which I had to move the configuration I was previously doing in `config/application.cr` into or the logger wouldn't initialize before it was needed.
![image](https://user-images.githubusercontent.com/8840681/82365876-34d55200-9a09-11ea-9cd6-07f48aa35033.png)
