### ISSUE TITLE
Private key leakage

### ISSUE THREAD

**Issue by Ajwani97** [amberframework/amber#1202]
Hello team,
Please retract the private key of the framework, if it's not used for testing purposes.

If it's a legitimate private key, it can be used for signing viruses.. 

Thanks

**Comment by drujensen** [comment]
I believe this key is only used by the tests.  @eliasjpr @elorest can you confirm?

**Comment by drujensen** [comment]
I confirmed this is a self signed cert using the default `Internet Widgits Pty Ltd`
```
openssl x509 -noout -subject -issuer -in cert.pem 
subject= /C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
issuer= /C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
```

I think we can close this unless I'm missing something.

**Comment by Ajwani97** [comment]
Its the file named as key.pem, present in the same dir as cert.pem..

Apologies, if you found this issue time consuming.. 🙂
