### ISSUE TITLE
How to create project without webpack, only API? 

### ISSUE THREAD

**Issue by OpakAlex** [amberframework/amber#1205]
Hello, how it's possible to create project for API without templates and webpack code?

**Comment by drujensen** [comment]
It would be great to add a `--minimal` flag like Rails 6.0 is adding.

For now, you can delete the webpack configuration and all the view templates.  Then in the `.amber.yml`, remove the `npm` section from the watcher.

Finally you can use the `amber generate api Post title:string body:text published:bool` command to provide you a full restful resource with routes, controller, model and migrations.

**Comment by OpakAlex** [comment]
Thanks, i will check your generators!
