### ISSUE TITLE
Not valid project root directory

### ISSUE THREAD

**Issue by manindragautam** [amberframework/amber#1215]
Hi,
I have installed crystal 0.35.0 and amber 0.35.0 . After creating a new application, the `amber routes` command is working, but when I generate scaffold like in amber starting guide, after that `amber routes` is not working and throwing this error.

**Before**
![Screenshot from 2020-06-26 14-54-20](https://user-images.githubusercontent.com/33649380/85842803-e3657300-b7bd-11ea-96ab-b41326c44c28.png)

**After**
![Screenshot from 2020-06-26 14-54-42](https://user-images.githubusercontent.com/33649380/85842845-f37d5280-b7bd-11ea-8b1d-13ae130ccba6.png)

**Comment by sardaukar** [comment]
Any plans for a release with this fix? It's really jarring to have this error after using scaffolding.

**Comment by drujensen** [comment]
Right now, we are doing releases when Crystal does their release.  We are in maintenance mode waiting for 1.0.  I can do a patch release if you want.

**Comment by sardaukar** [comment]
Not needed if you're locked with Crystal, thanks!
