### ISSUE TITLE
Cannot connect to database while following Getting Started guide but with the provided Docker Compose db

### ISSUE THREAD

**Issue by ZimbiX** [amberframework/amber#1232]
### Description

Following Amber's [Getting Started guide](https://docs.amberframework.org/amber/getting-started), but using the provided Docker Compose `db` service instead of installing Postgres, results in an error, since the database does not expose its port:

```bash
$ docker-compose up -d db
$ amber db create migrate
Connection unsuccessful: postgres://postgres:password@localhost:5432/postgres
```

I wasn't sure whether to file this issue here or on the docs repo, since it probably affects both. I chose here because I reckon there's a code change required: to expose the port.

### Steps to Reproduce

Follow the [Getting Started guide](https://docs.amberframework.org/amber/getting-started) for the most part:

1. *Install dependencies*:
    1. *Install `crystal` and `amber`*:

        ```bash
        $ yay -S amber
        ```
    2. *Install a database*:

        Instead of the linked official Postgres installation guide, prepare to make use of the included Docker Compose Postgres `db` service by installing Docker Compose and Docker:

        ```bash
        $ yay -S docker-compose
        ```

2. *Generate a new Amber application*

    ```bash
    $ amber new pet-tracker && cd pet-tracker
    ```

3. *Generate a resource*

    ```bash
    $ amber g scaffold Pet name:string breed:string age:integer
    ```

4. *Create and migrate the database*

    First, start the `db` Docker Compose service:

    ```bash
    $ docker-compose up -d db
    ```

    Now attempt to migrate it:

    ```bash
    $ amber db create migrate
    Connection unsuccessful: postgres://postgres:password@localhost:5432/postgres
    ```

**Expected behavior:** The database gets migrated

**Actual behavior:** Error shown

**Reproduces how often:** Always

### Versions

```
$ amber --version
Amber CLI (amberframework.org) - v0.35.0

$ crystal --version
Crystal 0.35.1 (2020-06-21)

LLVM: 10.0.0
Default target: x86_64-pc-linux-gnu

$ uname -a
Linux ZimbiX-GreenSync 5.8.8-arch1-1 #1 SMP PREEMPT Wed, 09 Sep 2020 18:59:45 +0000 x86_64 GNU/Linux
```

### Resolution

I propose that:

- Docker database usage be documented in the Getting Started guide. That is, only using Docker for the database. This is simpler than installing and setting up Postgres yourself
- The Docker Compose service expose the port:

    ```diff
    diff --git a/docker-compose.yml b/docker-compose.yml
    index 17ec765..2e3cdce 100644
    --- a/docker-compose.yml
    +++ b/docker-compose.yml
    @@ -35,6 +35,8 @@ services:
           POSTGRES_DB: pet_tracker_development
         volumes:
           - db:/var/lib/postgres/data
    +    ports:
    +      - 5432:5432
     
     volumes:
       db:
    ```

    Or, if you don't want to do that by default to avoid conflicting with an installed Postgres, have the lines in there commented out, with a comment like:

    > Uncomment this to expose the port if you want to Dockerise the database but use Amber outside Docker

I have other suggestions regarding the Docker Compose setup; I might make separate issues for those.

**Comment by eliasjpr** [comment]
@ZimbiX thanks for bringing this up. This looks like a very simple change and backwards compatible. You can go ahead and open the PR and we will review it. Please ensure that any documentation is updated with this change. 

Thank you @ZimbiX

**Comment by utshahGSW30** [comment]
Are there any updates?

**Comment by eliasjpr** [comment]
Addressed with https://github.com/amberframework/amber/pull/1257
