### ISSUE TITLE
filters.cr:27:65 Error: unexpected token: Nil

### ISSUE THREAD

**Issue by kematy** [amberframework/amber#1254]
$:/mnt/d/crystal/ruby2crystal/ruby2crystal-master$ shards build ruby2crystal --ignore-crystal-version
Dependencies are satisfied
Building: ruby2crystal
Error target ruby2crystal failed to compile:
In lib/amber/src/amber/controller/filters.cr:27:65

 27 | record Filter, precedence : Symbol, action : Symbol, blk : -> Nil do
                                                                    ^
Error: unexpected token: Nil

**Comment by eliasjpr** [comment]
@kematy ` -> Nil` is valid crystal. Not sure what Ruby2Crystal stating this is incorrect. 

Can you please elaborate on the reported issue, thank you.
