### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by wout** [amberframework/amber#1270]
For a while now, https://amberframework.org is down.

**Comment by crimson-knight** [comment]
Looks like the domain expired and was renewed without the right configuration to keep the site live.

That's a bummer.

**Comment by wout** [comment]
> Looks like the domain expired and was renewed without the right configuration to keep the site live.
> 
> That's a bummer.

Yeah, it doesn't look good. It's been at least a week or so like that.

**Comment by elorest** [comment]
I checked and the server is still running as expected. I'll reach out to the domain owner and see if we can get it pointed correctly.

**Comment by elorest** [comment]
IP should be 45.55.191.2

**Comment by elorest** [comment]
It's up again. Thanks @eliasjpr
