### ISSUE TITLE
Missing build step

### ISSUE THREAD

**Issue by marccremer** [amberframework/amber#1272]
### Description

If you try to build locally you need to run "shards install" before make
else you get an error
`Missing shard.lock`

### Steps to Reproduce

1. git clone git@github.com:amberframework/amber.git
2. cd amber
3. git checkout stable
4. make

**Expected behavior:** 
If I follow the readme the project should build
**Actual behavior:** 
I get an error `Missing shard.lock`

**Reproduces how often:** 
Always

### Versions
Crystal 1.3.2 (2022-01-19)

LLVM: 13.0.0
Default target: x86_64-pc-linux-gnu
arch linux

### Additional Information
If you run `shards install` it works

**Comment by crimson-knight** [comment]
Can you make that change to the readme and submit a PR?

**Comment by crimson-knight** [comment]
Thanks, @marccremer for your PR, we've updated the build instructions to include the missing step. I've also created another PR that will update the stable branch for our Linux users to get the latest 1.2.2 version of Amber in #1285 but in the mean time you can build from master to get all of the latest updates.
