### ISSUE TITLE
[CLI][Feature Request] Amber new --api

### ISSUE THREAD

**Issue by tekanic** [amberframework/amber#1273]
[Feature Request] 

It would be great if the project generator automatically created the necessary pipes and endpoints with jwt configured if you specify --api when creating a new project.

**Comment by drujensen** [comment]
The existing `amber generate api Post title:string body:text` will create a different pipeline:
```
  pipeline :api do
    plug Amber::Pipe::Error.new
    plug Amber::Pipe::Logger.new
    plug Amber::Pipe::Session.new
    plug Amber::Pipe::CORS.new
  end
```

This could add a new plug for JWT support.

**Comment by elorest** [comment]
What @drujensen said. In addition it's currently setup to send an encrypted json block back with `set-cookie` header. JWT in it's default state is sort of a step backwards because it doesn't support encryption by default.

**Comment by robacarp** [comment]
I agree that there is no reason to assume that someone would want JWT by default. HTTP session and cookie are more than enough for a default, and they create far less headache on the front-end, too.

**Comment by codered** [comment]
A solution has been provided and no updates on this feature for almost a year. It is safe to close and if we really need JWT a new feature request can be open.
