### ISSUE TITLE
amberframework.org and docs.amberframework.org are down / unreachable

### ISSUE THREAD

**Issue by carlendev** [amberframework/amber#1295]
Hello,

Both [amberframework.org](https://amberframework.org/) and [docs.amberframework.org](https://docs.amberframework.org/amber/)  seems down since 24 hours or so.

I have no idea if it's related or not but the same issue appeared last year (2021) at the same period #1270 , (maybe related with the domain).

Thanks

**Comment by crimson-knight** [comment]
Yeah @carlendev it's similar, the domain needs to be renewed. 


@eliasjpr can you renew/transfer and let me know when that's complete? I'll reimburse you for any costs.

**Comment by crimson-knight** [comment]
I was able to get the site online a month ago, just forgot to close this :)
