### ISSUE TITLE
Minimum node version not detected when generating a new app

### ISSUE THREAD

**Issue by crimson-knight** [amberframework/amber#1300]
Currently, we support Node 14.18+ and 16+. However, you can still generate a new amber app without a supported node version installed.

- The node version should be detected to confirm the asset pipeline will work
- If an unsupported node version is detected, the app creation should fail and display an error message containing the node version found, and display the minimum supported versions required
- Add a `--ignore-node-version` flag to opt-out of this node version safety check (don't know why you'd need this, but seems smart to include)

**Comment by alex-lairan** [comment]
> Add a --ignore-node-version flag to opt-out of this node version safety check (don't know why you'd need this, but seems smart to include)

You may have a version manager, and the system version is not up to date (for any legacy reason) but the corrects versions are available once you have the .node-version or any version file.

**Comment by crimson-knight** [comment]
@alex-lairan that was also my thought. I use nvm but I still have my global node version set to 18 because I install some scripts globally to run as cli tools, and I'm betting most others have the same setup (but not all, who knows)

So when the node version check is ignored, what should the default dependencies be set to? The 16+ version makes the most sense to me.

**Comment by alex-lairan** [comment]
I would say the highest possible.

**Comment by crimson-knight** [comment]
Closing this because we removed the dependency on Node entirely
