### ISSUE TITLE
Remove bootstrap from the default app generators and new app template

### ISSUE THREAD

**Issue by crimson-knight** [amberframework/amber#1303]
Amber is currently tightly coupled with Bootstrap 4. 

Pros:
- This makes it easy to get started with some styling built in
- Less configuration out of the box

Cons:
- It's tied into every generator (new apps, scaffolds and views), making more work to use a different front-end framework
- It's using Bootstrap 4, but the latest is Bootstrap 5
- Upgrading Bootstrap 4 -> still means some of the older classes get mixed in and create more work to change the generated views

Let's remove Bootstrap entirely. 
- The default home page should be built using inline CSS
- The scaffold generators can stop adding to the navigation layout during generation
- Generated views should be minimal HTML with maybe some inline CSS for bare minimum styling

This sets the path for easier customization of templates for new Amber users.

**Comment by drujensen** [comment]
@crimson-knight Agree.  We should go all the way and remove npm dependency as well.  use HTMX and keep CSS < 100kb.

**Comment by crimson-knight** [comment]
I would love to remove the node dependency entirely. Is there a shard to do that though? Seems like everything these days for styling is handled by a JS bundler

**Comment by drujensen** [comment]
If we go minimal like you are suggesting, you don't need any of that stuff.  I will work on this when I get a chance.

**Comment by crimson-knight** [comment]
Cool thanks Dru. I checked out htmx, looks sweet!

Including a copy of htmx for our asset pipeline to start is a good way to allow for installing Vite or some other JS/asset bundler for styling should anyone want to implement it.
