### ISSUE TITLE
Website funding is over and needs to be renegotiated every year with digital ocean.

### ISSUE THREAD

**Issue by elorest** [amberframework/amber#1316]
Last year I tried to include the correct people in the email chain with them but who could handle that this year. I can forward all the email threads from the past.

**Comment by crimson-knight** [comment]
That would be me! Crimsonknightstdios@gmail.com

**Comment by elorest** [comment]
Something seems wrong with that email. Gmail reports it doesn't exist.

**Comment by crimson-knight** [comment]
Woops I forgot a letter

Crimsonknightstudios@gmail.com
