### ISSUE TITLE
Default configuration: host

### ISSUE THREAD

**Issue by Nephos** [amberframework/amber#132]
Hello,

In the configuration (https://amber-crystal.gitbooks.io/amber/content/getting-started/configuration.html) there is a default env variable for the port but not the host. It could be interesting to add one.

```crystal
  port = ENV["PORT"] || 8080
  app.host = ENV["HOST"] || "0.0.0.0"
```

(note: shouln't it be a `ENV[...]?` ?)

**Comment by elorest** [comment]
Yes it should be ENV[]?. Would probably be good to have host but for now 0.0.0.0 is the default and works fine I believe.

**Comment by Nephos** [comment]
The recommended behaviour is to listen on 127.0.0.1, in order to avoid security flaws if the firewall is configured or not configured.

**Comment by eliasjpr** [comment]
0.0.0.0 is a non-routable meta-address used to designate an invalid, unknown, or non-applicable target (a ‘no particular address’ place holder).

The reason we decided to bind to 0.0.0.0 is that some PAAS such as HEROKU do not provide the binding IP address when a dyno is started in fact the originating IP address for these requests cannot be controlled by the user. The 0.0.0.0 allows us to bind to which ever IP address is being used by the process.

**Comment by elorest** [comment]
I prefer to listen on 0.0.0.0 in development. Once we get environments
setup right it will default to 127.0.0.1 in production.

**Comment by drujensen** [comment]
@Nephos Thanks for reporting this.

With the latest release, we now support `config/environments/{environment}.yml` which allows you to configure the `host: {host_ip}` per environment.

Please re-open this ticket if it doesn't address your concern.
