### ISSUE TITLE
Use Ansible to test installation instructions for different OSes

### ISSUE THREAD

**Issue by a-alhusaini** [amberframework/amber#1347]
We can use ansible playbooks during CI/CD to test the steps needed to install amber on different operating systems with different configurations.

**Comment by codered** [comment]
Vagrant might be a better option. What do you think @a-alhusaini ?

**Comment by crimson-knight** [comment]
We don't need additional tooling to do this, CircleCI will already support this.

Here's the OSX version I was working on yesterday: https://app.circleci.com/pipelines/github/amberframework/amber/15/workflows/d0e875d3-c4ea-492a-b923-417cfbfaa4aa/jobs/40

This workflow gets triggered manually as a pre-release test process, so it does not run on every PR/commit
