### ISSUE TITLE
Sqlite dependency version missmatch

### ISSUE THREAD

**Issue by kidandcat** [amberframework/amber#1348]
### Description

Amber new generator with `-d sqlite` adds `sqlite3 (~> 0.18.0)` to the shards.yml file, but amber 1.4.1 requires `sqlite3 (~> 0.19.0)` and this generates a conflicts and shards install will throw an error.

### Steps to Reproduce

1. amber new example -d sqlite

**Expected behavior:** A new project is created and dependencies installed

**Actual behavior:** 
```
Unable to satisfy the following requirements:

- `sqlite3 (~> 0.18.0)` required by `shard.yml`
- `sqlite3 (~> 0.19.0)` required by `amber 1.4.1`
Failed to resolve dependencies
```

**Reproduces how often:** 100%

### Versions

Amber CLI (amberframework.org) - v1.4.1

Crystal 1.10.1 (2023-10-13)
LLVM: 15.0.7
Default target: x86_64-apple-macosx

MacOS Sonoma (M2) 14.1

### Additional Information

Changing the shards.yml sqlite version from 1.18.0 to 1.19.0 solves the problem.

**Comment by codered** [comment]
This has been fixed with with a recent PR. https://github.com/amberframework/amber/pull/1351 . 

You can either compile the new amber binary and use it or wait for the change to be pushed into master.
