### ISSUE TITLE
First registered connection cannot be nil

### ISSUE THREAD

**Issue by kidandcat** [amberframework/amber#1350]
### Description

When I run an amber app from a clean `amber new app` I get this error:
```
Unhandled exception: First registered connection cannot be nil (Exception)
  from lib/granite/src/granite/connections.cr:34:7 in 'first_connection'
  from lib/granite/src/granite/connections.cr:43:7 in 'first_reader'
  from lib/granite/src/granite/base.cr:33:3 in '~Granite::Base::reader_adapter:init'
  from lib/granite/src/granite/base.cr:33:3 in '__crystal_main'
  from /usr/local/Cellar/crystal/1.10.1/share/crystal/src/crystal/main.cr:129:5 in 'main_user_code'
  from /usr/local/Cellar/crystal/1.10.1/share/crystal/src/crystal/main.cr:115:7 in 'main'
  from /usr/local/Cellar/crystal/1.10.1/share/crystal/src/crystal/main.cr:141:3 in 'main'
 ```

### Steps to Reproduce

1. Create a new app with `amber new app`
2. Create db with `amber db create`
3. Migrate db with `amber db migrate`
4. Run the app with `amber watch` (or build and run, it fails with the same error)

**Expected behavior:** The app runs properly

**Actual behavior:** There is an error
```
Unhandled exception: First registered connection cannot be nil (Exception)
  from lib/granite/src/granite/connections.cr:34:7 in 'first_connection'
  from lib/granite/src/granite/connections.cr:43:7 in 'first_reader'
  from lib/granite/src/granite/base.cr:33:3 in '~Granite::Base::reader_adapter:init'
  from lib/granite/src/granite/base.cr:33:3 in '__crystal_main'
  from /usr/local/Cellar/crystal/1.10.1/share/crystal/src/crystal/main.cr:129:5 in 'main_user_code'
  from /usr/local/Cellar/crystal/1.10.1/share/crystal/src/crystal/main.cr:115:7 in 'main'
  from /usr/local/Cellar/crystal/1.10.1/share/crystal/src/crystal/main.cr:141:3 in 'main'
 ```

**Reproduces how often:** 100%

### Versions

Amber CLI (amberframework.org) - v1.4.1

Crystal 1.10.1 (2023-10-13)
LLVM: 15.0.7
Default target: x86_64-apple-macosx

MacOS Sonoma (M2) 14.1

### Additional Information

I couldn't find a way to make it work.

**Comment by crimson-knight** [comment]
@kidandcat Thank you for the thorough issue. It appears this was an issue with Granite, I've merged a fix into master on granite.

Please make sure your `shard.yml` has the following:

```yaml
  granite:
    github: amberframework/granite
    branch: master
```

Then run `shards update` to get the latest version. Your app will now start as expected.

**Comment by kidandcat** [comment]
Thanks for the quick response & fix! 
I can confirm it works now.
