### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by matthewblott** [amberframework/amber#1357]
I've tried to join the Discord server but I'm presented with the following:

![Screenshot 2023-11-02 at 13 37 48](https://github.com/amberframework/amber/assets/1231417/253f0d5e-57cd-4c32-9bfc-c374e824cd42)

I'm on several servers already (nowhere near the 100 limit) so I'm at a bit of a loss. I tried various browsers, clearing the cache etc hence the reason for posting a question here. Thanks in advance :-)

**Comment by crimson-knight** [comment]
@matthewblott

Can you tell me which link below works for you or if both cause the same error:

1. https://discord.gg/vwvP5zakSn
2. https://discord.gg/vx55tNJUMw

**Comment by robacarp** [comment]
This link will never expire: https://discord.gg/wUJ4az5mVD

**Comment by matthewblott** [comment]
> 2\. https://discord.gg/vx55tNJUMw

Both return the same message as the one I posted above.

**Comment by robacarp** [comment]
No worries, glad you got it sorted out.
