### ISSUE TITLE
When SSL is on, http:// is disabled

### ISSUE THREAD

**Issue by mixflame** [amberframework/amber#158]
A redirect from http:// to https:// would be better

**Comment by veelenga** [comment]
Just want to mention this works for me https://github.com/veelenga/crystal-ann/pull/16.
This change is of course Heroku-dependent, because of `x-forwarded-proto`... ;)

**Comment by elorest** [comment]
It should just redirect to path instead of url then we won't have to worry about protocol. I believe rails does it this way.

**Comment by mixflame** [comment]
I have some code here on master branch to try to run 2 servers, one for HTTP and one for HTTPS

but it fails

https://github.com/mixflame/amber

**Comment by eliasjpr** [comment]
Closing this issue since it seems to be working as expected. Please reopen if you find out more about this issue
