### ISSUE TITLE
Provide ability to configure pipes at initialization

### ISSUE THREAD

**Issue by drujensen** [amberframework/amber#171]
Some of the pipes have configuration settings.  Allow these setting to be initialized at creation.

**Comment by marksiemers** [comment]
@drujensen - Do you have an idea how to implement this?

**Comment by marksiemers** [comment]
@drujensen and @elorest - Please confirm that either this is done, or what work is left to complete this feature.

**Comment by eliasjpr** [comment]
There is work still to be done for a couple of pipes

**Comment by docelic** [comment]
https://github.com/amberframework/amber/pull/539

**Comment by eliasjpr** [comment]
This is awesome! Thank you for all the work @docelic

**Comment by drujensen** [comment]
Closing this.  I believe this is now complete.
