### ISSUE TITLE
Cookie and session keys don't persist across server restarts.

### ISSUE THREAD

**Issue by elorest** [amberframework/amber#194]
### Description

Every time server restarts `Support::CachingKeyGenerator` generates new keys causing session, and cookies to all become invalid. This is a bug since rails, sinatra, phoenix, laravel, and hanami all have persistent keys usually set via Env or secrets.yml.

### Steps to Reproduce

1. Create an action and set a session.
2. Created another action which reads and prints the session.
3. Run server and visit both pages.
4. Restart the server and refresh the session printing page without visiting the session writing page first.

**Expected behavior:** Session should print.

**Actual behavior:** Session is nil.

**Reproduces how often:** Everytime.

### Solution

I can work on this while working on environments and secrets. My suggestion would be to pull these keys from secrets and only generate them if they're missing.

**Comment by drujensen** [comment]
This bug is pretty annoying since every code change will log me out of my website.

**Comment by eliasjpr** [comment]
Should we add `amber g secret` command?

**Comment by elorest** [comment]
I'm working on that.

**Comment by eliasjpr** [comment]
Whats the progress on this?
