### ISSUE TITLE
Random things get printed by specs.

### ISSUE THREAD

**Issue by elorest** [amberframework/amber#229]
### Description
Too many random things get printed while running specs. Below is an example. It would also be great to figure out how not to print the files being created via generators. 
................................................................................................................................200  | GET  "/index/elias"  | 11.0µs
Params: name=elias
.200  | GET  "/hello"  | 7.0µs
Params: 
.200  | PUT  "/hello/1"  | 5.0µs
Params: id=1
.200  | PATCH  "/hello/1"  | 4.0µs
Params: id=1
.200  | POST  "/hello"  | 3.0µs
Params: 
.200  | DELETE  "/hello/1"  | 4.0µs
Params: id=1
.....................................................................................................I, [2017-09-04 12:25:22 -0600 #64216]  INFO -- : Socket listening at /
......I, [2017-09-04 12:25:22 -0600 #64216]  INFO -- : Socket listening at /
.I, [2017-09-04 12:25:22 -0600 #64216]  INFO -- : Socket listening at /

### Solution
Text printed via specs should be intentional and neat like:

```
Running generators specs....
Cleaning up tmp files...
Testing router...
```

**Comment by eliasjpr** [comment]
I don't see this as an issue :(

**Comment by faustinoaq** [comment]
Maybe we should use `spec --verbose` or disable logs on amber tests

**Comment by elorest** [comment]
If we have output other than green dots with should be a clear description of which test is running not data arbitrarily printing to the screen as a side effect of the tests running. IMO.

**Comment by elorest** [comment]
Definitely not a Priority. I'd rather keep this ticket open though.

**Comment by eliasjpr** [comment]
I would like to close this since this is something that would be somehow a little dificult given that the generators outputs stuff
