### ISSUE TITLE
Installation procedure could be less dangerous

### ISSUE THREAD

**Issue by renich** [amberframework/amber#245]
Usually, on a makefile, you have a separate make command for installation. In your case, `sudo make` is advised. This will build amber and install it.

IMHO, the build process should not be done with sudo powers; only the installation process.

I suggest you decouple it.

**Comment by faustinoaq** [comment]
Good advice :+1:

**Comment by renich** [comment]
Glad to help, man. ;)

**Comment by faustinoaq** [comment]
This issue created a new issue, see: #262
