### ISSUE TITLE
Don't use forks as shards

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#261]
### Description

Currently Amber is using `TechMagister/crystal-icr` a fork of `https://github.com/crystal-community/icr`

Official ICR is getting updated with many improves and bug fixes.

### Steps to Reproduce

1. Create an Amber project
2. Install dependencies `shards`
3. Start `amber c` (it's using `TechMagister/crystal-icr`)

**Expected behavior:** Use latest version of https://github.com/crystal-community/icr

**Actual behavior:** It's using a fork (`TechMagister/crystal-icr`)

**Reproduces how often:** 100%

### Versions

amber `0.2.6`

### Additional Information

```yaml
  sentry:
    github: TechMagister/sentry
    branch: change_cli
```

Sentry is also a fork, Should we using forks as shards?

Maybe we can create dedicated repos for these shards inside _amberframework_ organization

WDYT @TechMagister @drujensen @eliasjpr ?

**Comment by faustinoaq** [comment]
Currently Amber has three forks as dependencies:

- https://github.com/TechMagister/crystal-icr by @TechMagister 
- https://github.com/TechMagister/sentry by @TechMagister 
- https://github.com/elorest/spinner by @elorest 

What are the alternatives?

0. Keep using forks

**Pros:** Don't need changes.
**Cons:** Uses forks (I think it seems unprofessional for a web framework)

1. Merge forks and change dependencies to original repos.

**Pros:** Don't use forks
**Cons:** Forks need to be merged, original shard author would take time to check changes or changes would not be generic enough, just Amber specific.

2. Copy shards code (icr, sentry, spinner) inside amber.

**Pros:** Don't use forks
**Cons:** Amber codebase will grow too much.

3. Create dedicated repos for `Amber::ICR`, `Amber::Sentry` and `Amber::Spinner` inside _amberframework_ organization and use them.

**Pros:** Don't use forks
**Cons:** Original shards creator could disagree if we copy his code to _amberframework_

The above are options I thoughts as feasible. I like option 3, because we can put a big banned saying 

```
Note:
This shard is based on ... and is modified to use in Amber Framework.
We recommend you to use the provided by the original author.
```

WDYT @elorest @eliasjpr ?

**Comment by elorest** [comment]
I agree with you that we should stop using forks. In the case of the
spinner one it was just a fix to make it work with a modern version of
crystal. I think the PR has finally been merged on that.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Comment by faustinoaq** [comment]
Yes, I think we can mix options 1(merge) and 3 (create new repo inside org _amberframework_).

**Comment by elorest** [comment]
I agree.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Comment by faustinoaq** [comment]
For now [alternative 0](https://github.com/amberframework/amber/issues/261#issuecomment-330679938) is working.

To implement alternative 3 core members need to create new repositories inside amberframework organization.

To implement alternative 1 @elorest and @TechMagister need to create PR request to original repos.

I think `elorest/spinner` could be merged to original repo.

However  `TechMagister/sentry` and `TechMagister/crystal-icr ` were changed to work specifically with amber, so maybe we should use alternative 3 on these.
