### ISSUE TITLE
Invalid installation instructions

### ISSUE THREAD

**Issue by thomasnal** [amberframework/amber#264]
### Description

Installation of Amber from documentation does not work.  `amber-cmd` repository does not exist.

### Steps to Reproduce

Excerpt from https://docs.amberframework.org/getting-started/Installation/
```
...
Method 1 - From Source:

Install crystal by following these instructions. https://crystal-lang.org/docs/installation/

Next download and install amber_cmd

git clone https://github.com/amber-crystal/amber-cmd.git
...
```

**Expected behavior:** Git clone to succeed.

**Actual behavior:** There is no such repository.

**Reproduces how often:** 100%

**Comment by faustinoaq** [comment]
@thomasnal Yea, you are right. We need to update our documentation. Amber have made some good improvements and refactorings in last days. By example, `amber_cmd` was merged with `amber` itself and `ambercr` is now _amberframework_. I hope we get updated documentation in next days.

Thanks for report this issue! :smile:

**Comment by thomasnal** [comment]
Good work.

As there is no information of the activities you mention, for me as one not involved I had to figure out I need to re-fetch, re-compile, ...  Straightforward removal of the gem didn't work.

The ticket helps others.

**Comment by drujensen** [comment]
The gitbooks stopped automatically updating after we changed names.  This is now fixed.  Thanks for reporting this.
