### ISSUE TITLE
Drop repo's 'crystal-language' topic

### ISSUE THREAD

**Issue by matiasgarciaisaia** [amberframework/amber#267]
The Crystal community has somewhat decided to [use `crystal` as the language's topic](https://github.com/search?utf8=✓&q=topic%3Acrystal&type=Repositories).

To avoid fragmentation in the community, please drop the `crystal-language` topic, that only has ~8 repositories at the moment.

Any contributor can change it from the repo's homepage.

See crystal-lang/crystal#4241 for more context.

Thank you very much :)

**Comment by drujensen** [comment]
fixed.  not sure how long it takes to propagate. @matiasgarciaisaia thanks!
