### ISSUE TITLE
Use nano instead of vim on amber encrypted

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#271]
### Description

Currently amber uses vim to edit encrypted settings. Vim is nice but it have a high learning curve.
Nano is simpler and is enough for edit a simple file.

### Steps to Reproduce

1. Generate a new Amber Project
2. Use `amber e`
3. Amber opens vim editor or shows an error because vim is not installed.

**Expected behavior:** Use a simple editor like nano

**Actual behavior:** Use vim an excellent editor, but with high learning curve.

**Reproduces how often:** 100%

### Versions

0.2.6

### Additional Information

`vim` is not installed in some distros by default. However `nano` is installed in almost all distros. Also we can try `vi` but isn't user friendly at all.

**Comment by elorest** [comment]
I think vim is as ubiquitous as nano/pico but you can use whatever editor you want with `amber encrypt -e [nano, pico, emacs, etc]`

**Comment by elorest** [comment]
`git merge` and `git commit` also uses vim by default until you configure it differently.

**Comment by drujensen** [comment]
Can we leverage the editor they chose in git as the default?

```
git config --global core.editor "vim"
```
or:
```
export GIT_EDITOR=vim
```

**Comment by faustinoaq** [comment]
I agree with @drujensen

**Comment by faustinoaq** [comment]
> you can use whatever editor you want with amber encrypt -e [nano, pico, emacs, etc]

Oh, @elorest thanks you I forgot the `--help` flag :sweat_smile:

**Comment by faustinoaq** [comment]
> git merge and git commit also uses vim by default until you configure it differently.
>> Can we leverage the editor they chose in git as the default?

About default editor:

> By default, Git uses whatever you’ve set as your default text editor ($VISUAL or $EDITOR) or else falls back to the vi editor to create and edit your commit and tag messages [0]

[0] - https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration

**Comment by elorest** [comment]
Interestingly the default editor it falls back to errors in OSX. 
http://tooky.co.uk/there-was-a-problem-with-the-editor-vi-git-on-mac-os-x/

**Comment by faustinoaq** [comment]
So, I think my issue was answered, I'll close this, reopen if you need to.

**Comment by sam0x17** [comment]
was there ever a way added to override the default other than by specifying the command line option?

**Comment by elorest** [comment]
System editor I think.
