### ISSUE TITLE
When generating new app Amber w fails after the render changes 

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#282]
### Description
After generating a new amber app the app fails to compile.

### Steps to Reproduce

1. Generate an amber app with `amber new {app} --deps`
2. Run `amber w` to run the project

**Expected behavior:** Expected the site to compile and see the default amber screen on browser when visiting localhost:3000

**Actual behavior:** App does not compile see  error https://gist.github.com/eliasjpr/30aabfa358cc79f64bfafdc155385b02

**Reproduces how often:** 100%

### Versions

Amber 0.2.6

**Comment by eliasjpr** [comment]
I believe we need to make a release for the `render` method changes to take effect.

**Comment by faustinoaq** [comment]
I can't reproduce this issue

My environment is:

```
$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        17.0.2
Codename:       Gellivara
$ crystal -v
Crystal 0.23.1 (2017-07-17) LLVM 4.0.1
$ amber -v
Amber CMD (amberframework.org) - v0.2.7
```

**Comment by elorest** [comment]
Should be resolved.
