### ISSUE TITLE
not running on specified port

### ISSUE THREAD

**Issue by sam0x17** [amberframework/amber#292]
I am trying to use the -p command line option to run amber on port 8080, however it is ignoring me and still using port 3000. I am trying to run on google app engine so it must run on 8080. Please advise.

**Comment by jasdeepsingh** [comment]
@sam0x17 what version of Amber are you on? If you are on the latest version you should be able to specify the port in `config/environments/{environment}.yml`

**Comment by elorest** [comment]
That's correct. Thanks. @jasdeepsingh

**Comment by sam0x17** [comment]
Oh ok thanks, it would be helpful if this was more clear in the docs

**Comment by sam0x17** [comment]
Is there example for working with the encrypted production settings? I can't find a section for that in the docs

**Comment by elorest** [comment]
Run `amber encrypt` to edit your production settings. Your key is stored in
.amber_secret_key but can also be set via ENV AMBER_SECRET_KEY


On Oct 7, 2017 11:05 AM, "Sam Johnson" <notifications@github.com> wrote:

Is there example for working with the encrypted production settings? I
can't find a section for that in the docs

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/amberframework/amber/issues/292#issuecomment-334950493>,
or mute the thread

**Comment by sam0x17** [comment]
@elorest thanks! is there a way to get it to use nano instead of vim?

**Comment by elorest** [comment]
-e nano

**Comment by elorest** [comment]
If you could document any of the things that were confusing to you it would
help a lot.

**Comment by sam0x17** [comment]
I might do just that

**Comment by sam0x17** [comment]
@elorest one other quick question related to this: why in the default Dockerfile does it simply use `amber watch` at the end -- should't it be using `amber r -e production`, since `watch` is only for development mode?

**Comment by elorest** [comment]
The default dockerfile is for development purposes. It could be modified and used for production, but it's hard to know what peoples production requirements will be.

**Comment by elorest** [comment]
It's also probably easier just to run `crystal compile --release --no-debug src/project.cr && ./project` so you have more control.

**Comment by drujensen** [comment]
@elorest @sam0x17 what do you think about changing this to use the production compile and run command instead of `amber watch`?

It seems like the `Docker` file should be ready for production release where the `docker-compose.yml` can focus on the development environment.

**Comment by elorest** [comment]
I'm fine with that. Run command will need to be updated if we're going to use it though. Also we'll need to to make sure to add `--no-debug` to fix the linux llvm bug thing.

**Comment by sam0x17** [comment]
The Dockerfile I ended up using (that works with google app engine):

```
FROM crystallang/crystal

RUN apt-get update
RUN apt-get upgrade -y

# Add this directory to container as /app
ADD . /app
WORKDIR /app

# Install dependencies
RUN shards install

# Build our app
RUN crystal build --release --no-debug src/bitfort.cr

# Run the tests
#RUN crystal spec

#EXPOSE 3000

WORKDIR /app
EXPOSE 8080
CMD ["./bitfort", "--port", "8080"]
```

**Comment by drujensen** [comment]
:+1:

**Comment by eliasjpr** [comment]
Closing this issue since the question has been answered. 

I will be opening a new issue for running amber in production for docker.
