### ISSUE TITLE
Move the database url config from the database.yml to the environment.yml

### ISSUE THREAD

**Issue by drujensen** [amberframework/amber#293]
### Description

Currently both Granite and Crecto are using the `config/database.yml` file to configure the database.  They also both support DATABASE_URL environment variable override.

This request is to add an initializer for Granite and Crecto that will look for a `database_url` in the environment instead. 

This will provide the ability to specify different databases for development, test and production.  It should continue to honor the `DATABASE_URL` override environment variable.

**Comment by elorest** [comment]
I'd like to pair with you on this.

**Comment by eliasjpr** [comment]
Can we start work on this? This seems to be fairly straightforward

**Comment by elorest** [comment]
Complete!
