### ISSUE TITLE
Error pages generator

### ISSUE THREAD

**Issue by drujensen** [amberframework/amber#294]
### Description

When first creating a new application, an Error Controller is provided but it isn't hooked up and doesn't do anything without some work.

Create a new generator that will provide the 3 views, the Error Controller, and the registry of the handler in the pipeline.

**Comment by marksiemers** [comment]
Are there two steps to this issue?
1. Create fully functioning `error` generator (probably take cues from `auth` generator)
1. Remove the error controller from being generated with `amber new`

I could probably take this one.

**Comment by marksiemers** [comment]
I have some WIP stashed for this, but waiting on https://github.com/amberframework/amber/pull/330 to get merged in.

@drujensen - Can you confirm my question about the the steps for this issue above?

**Comment by drujensen** [comment]
@marksiemers that is correct.  There are a couple helper methods to inject the pipeline and add the routes.  You can find those used in the Auth generator as well.  Thanks for taking this on.

**Comment by eliasjpr** [comment]
Being addressed in https://github.com/amberframework/amber/pull/345

**Comment by marksiemers** [comment]
Can this be moved to 0.4.0 milestone?

**Comment by marksiemers** [comment]
#415
