### ISSUE TITLE
amber routes missing socket routes

### ISSUE THREAD

**Issue by drujensen** [amberframework/amber#295]
### Description

When i call amber routes in cli, the socket routes does not show in result table.

### Steps to Reproduce

define a socket route in the routes.cr file

run `amber routes`

**Expected behavior:** [What you expect to happen]

to see the socket route

**Actual behavior:** [What actually happens]

no socket route is displayed

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

0.2.7

### Additional Information

This issue was submitted via Gitter by @iambudi

**Comment by faustinoaq** [comment]
I can reproduce it on amber `v0.3.6` too

**Comment by docelic** [comment]
https://github.com/amberframework/amber/pull/494

**Comment by marksiemers** [comment]
#494
