### ISSUE TITLE
undefined constant Amber::Controller::Static when compiling a new app

### ISSUE THREAD

**Issue by pedrohmxavier** [amberframework/amber#296]
### Description

I can't compile the most basic template default/project . Created just using "_amber new app_"
 It gives me an error of "_undefined constant Amber::Controller::Static_" when compiling. 
 Last line of the compiler trace.

```
in macro 'route' /home/pedro/workspace/delegate_web/lib/amber/src/amber/dsl/router.cr:11, line 2:

   1.       __temp_493 = ->(context : HTTP::Server::Context){
>  2.         controller = Amber::Controller::Static.new(context)
   3.         controller.run_before_filter(:index) unless context.content
   4.         unless context.content
   5.           context.content = controller.index.to_s
   6.           controller.run_after_filter(:index)
   7.         end
   8.       }
   9.       __temp_494 = "GET"
  10.       __temp_495 = Amber::Route.new(
  11.         __temp_494, "/*", __temp_493, :index, valve, scope, "Amber::Controller::Static"
  12.       )
  13. 
  14.       router.add(__temp_495)
  15.     

undefined constant Amber::Controller::Static
```

### Steps to Reproduce

1. Create a new app with latest amber version, "amber new app --deps"
2. Run it with "amber watch"

**Expected behavior:**  I excpected the first welcome screen on localhost:3000
**Actual behavior:**  It crashes when compiling

**Reproduces how often:** Everytime

### Versions

I'm running the following versions:

Amber CMD (amberframework.org) - v0.2.7
Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1

### Additional Information

I actually got it to work by putting back the static controller this pull request removed a few days ago.
https://github.com/amberframework/amber/pull/287

**Comment by elorest** [comment]
This is only an issue if you compile amber_cli from master, then run `shards install` which installs the amber 0.2.7 instead of master.

If you compile from master you need to use the master branch in your shard.yml as well. This isn't an issue if you use the version of amber installed from homebrew.

**Comment by pedrohmxavier** [comment]
I get it, but i just follwed the guide on https://www.amberframework.org/guides on _installation_ 
. Its outdated by any chance?

**Comment by elorest** [comment]
Technically that's right but by default you're checking out and compiling from master. Shards still installs from the last release though unless branch is set to master. Sometimes this is an issue. 

Probably we should just change it to download this and unzip it. https://github.com/amberframework/amber/releases/latest

**Comment by pedrohmxavier** [comment]
I re-installed from latest release and it worked great. Thank you very much.

**Comment by elorest** [comment]
I have a pr in to change this documentation.

**Comment by eliasjpr** [comment]
Can someone please update the docs when they get a chance. Thanks!

**Comment by elorest** [comment]
This has been resolved by my update to the documentation last weekend.
