### ISSUE TITLE
Running Amber in Production Mode for docker Instead of Dev

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#303]
### Description

Currently the Amber Dockerfile user `amber watch` as the command to boot up the amber server. It would be nice to have this changed to  `amber r production` instead since it compiles in release mode.

### Steps to Reproduce

Unless the Dockerfile is replaced with the release command it will always run `amber watch`

**Expected behavior:**

I would expect the docker file to run in production mode.

**Actual behavior:** 

It runs in development mode

### Versions

Current version 0.2.7

**Comment by elorest** [comment]
The docker setup as it currently exists is mostly used for development. If someone needs it to run in production they can just swap out the command(s) in their production docker-compose.yml. Along with their database and other containers with will most likely not be running on the same machine like they are in development.

**Comment by drujensen** [comment]
@elorest correct, we focused on development and `docker-compose.yml` overrides the CMD with `amber watch` already.

This request is asking if we should consider having the Dockerfile default to production.  This is the default CMD if someone wanted to launch their product using `docker run` instead.

I agree with @eliasjpr that the expectation by a user would be that the Dockerfile defaults are production mode.  That would be my expectation as well.  This will not affect the `docker-compose.yml` which is focused on development.  WDYT?  Do you agree?

**Comment by elorest** [comment]
`amber run` takes a lot longer than `amber watch`. As such I think its best if we default to development settings since it's hard to predict someones production needs. This convention is followed by most frameworks out there. For instance `rails server` the only server command built into rails is not intended to be used in production mode. Instead we use custom puma, unicorn, or passenger setups for production.

**Comment by drujensen** [comment]
@elorest good points.  I am ok with closing this

@eliasjpr wdyt?
