### ISSUE TITLE
Nested JSON, numbers, and boolean params being parsed as strings

### ISSUE THREAD

**Issue by watzon** [amberframework/amber#310]
### Description

I have been trying for the past couple hours to get this working and finally figured it must be a bug. I am attempting to set up a route to receive a webhook from GitLab/GitHub. These webhooks looks something like this:

```
{
  "action": "opened",
  "issue": {
    "url": "https://api.github.com/repos/octocat/Hello-World/issues/1347",
    "number": 1347,
    ...
  },
  "repository" : {
    "id": 1296269,
    "full_name": "octocat/Hello-World",
    "owner": {
      "login": "octocat",
      "id": 1,
      ...
    },
    ...
  },
  "sender": {
    "login": "octocat",
    "id": 1,
    ...
  }
}
```

Each have several nested objects. This is something that shouldn't be an issue. The problem is that all nested objects get parsed into a string, so the above example becomes this:

```
{
  "action": "opened",
  "issue": "{
    \"url\": \"https://api.github.com/repos/octocat/Hello-World/issues/1347\",
    \"number\": \"1347\",
    ...
  }",
  "repository" : "{
    \"id\": \"1296269\",
    \"full_name\": \"octocat/Hello-World\",
    \"owner\": \"{
      \"login\": \"octocat\",
      \"id\": \"1\",
      ...
    }",
    ...
  },
  "sender": \"{
    \"login\": \"octocat\",
    \"id\": \"1\",
    ...
  }"
}
```

Numbers are also becoming strings which is a slightly smaller problem.

### Steps to Reproduce

1. Create a `POST` route and route it to a controller.
2. In the controller method you're routing to put `pp params.raw_params` and return something.
3. Go to GitHub/GitLab webhooks and create a webhook (for this method you will need ngrok or something. Alternately you could just use Postman or the like.
4. Sent a test hook, or if you went with the Postman method send a JSON payload with nested objects.

**Expected behavior:** Params should be parsed correctly as a hash. Nested objects should become hashes as well rather than strings. Numbers should be numbers if they were sent as numbers, not strings. Booleans should also be boolean values.

**Actual behavior:** Nested objects, numbers, and booleans get stringified.

**Reproduces how often:** Every time.

### Versions

Amber CMD (amberframework.org) - v0.3.0
Windows Subsystem for Linux

### Additional Information

This is most likely due to `raw_params` being typed as `Hash(String, String)`, at least that is my thought. I don't know if there's a way around this, but I feel like there should be or this makes things super difficult to use.

**Comment by eliasjpr** [comment]
@watzon acknowledged. Thank you for submitting this issue. 

I have found the source of the bug and will be submitting a fix sometime today

**Comment by watzon** [comment]
@eliasjpr thank you! I was trying to find a fix myself, but wasn't having any luck

**Comment by eliasjpr** [comment]
I have been experimenting with it and the only thing I see we can do at the moment is renturn an object of JSON::Type

**Comment by watzon** [comment]
Better than what's happening currently

**Comment by elorest** [comment]
@eliasjpr does kemal have this issue? If not we could probably use it's solution. Also shouldn't the params be parsed into a hash instead of json like rails does?

**Comment by eliasjpr** [comment]
Kemal has the same issue base on the tests and code that I saw on the Kemal repo. It is almost identical to what Amber has. 

Here is the solution I am working on so far https://github.com/amberframework/amber/commit/e0fc6a29067dea80b6df08af69c6a88bcd5ec7a4

**Comment by eliasjpr** [comment]
Addressing this issue in this PR https://github.com/amberframework/amber/pull/315

**Comment by watzon** [comment]
Just need @elorest to approve it right?

**Comment by paulcsmith** [comment]
Another thought might be to use https://crystal-lang.org/api/0.23.1/JSON.html#mapping-macro

This gives you nice types and it's really clear what you're getting back. Maybe it doesn't work for your use case, but if it does it might be a good option.

**Comment by watzon** [comment]
@paulcsmith thought I mentioned it above but I guess not, I am using the JSON.mapping macro. The problem is that the result object is not nappa level because everything, even nested objects, are strings.

**Comment by paulcsmith** [comment]
@watzon Oh I see what you are saying 👍 I misunderstood

**Comment by paulcsmith** [comment]
In the meantime then, you may be able to use the request body string directly, instead of the params object. I think JSON.mapping can parse the raw string. I'm not sure, but it might be worth a try.

**Comment by watzon** [comment]
@paulcsmith already tried that, but nested objects become an escaped JSON string which doesn't parse

**Comment by eliasjpr** [comment]
Solved with https://github.com/amberframework/amber/pull/331
