### ISSUE TITLE
[Router] Add routing support for subdomains

### ISSUE THREAD

**Issue by sam0x17** [amberframework/amber#320]
This would be really cool to have as it is difficult / hacky to set up in normal Rails. For a number of reasons, I think it would be very desirable to have first-class support for subdomains in the routing system.

Possible syntax:

```crystal
Amber::Server.configure do |app|
  routes :web do
    subdomain :cloud do
      get "/" CloudHomeController, :index # this would handle cloud.domain.com/
    end
    get "/", HomeController, :index
  end
end
```

I think it would also make a lot of sense to have an application-wide convention where the GET variable `_subdomain` will emulate visiting a particular subdomain in the development and test environments (e.g. `http://localhost:3000/?_subdomain=cloud` would emulate `https://cloud.domain.com/`). This way, it will be possible to test subdomain routes without setting up fancy development/test DNS settings.

**Comment by drujensen** [comment]
Interesting. How would you handle wildcard sub domains?  Would you use an “*” instead of :cloud?

**Comment by sam0x17** [comment]
@drujensen yes, I like that

**Comment by sam0x17** [comment]
@drujensen hell, why not support regexes haha

**Comment by sam0x17** [comment]
the other thing I like about this syntax is you could nest anything inside of it, so if you have something like `us.cloud.site.com` you could do:

```crystal
subdomain :cloud do
  # routes for `cloud.site.com` go here
  subdomain :us do
    #routes for `us.cloud.site.com` go here
  end
end
```

and the idea would be that you can open a subdomain inside of our outside of a routes block:

```crystal
routes :web do
  subdomain :cloud do
    # route for cloud.site.com here
  end
end
```
or equivalently:

```crystal
subdomain :cloud do
  routes :web do
    # route for cloud.site.com here
  end
end
```

**Comment by eliasjpr** [comment]
We should use a Pipe to handle subdomains instead of extending the `router`.

**Comment by robacarp** [comment]
I think I agree with @eliasjpr, the subdomain (or just the whole domain) should be an attribute of the request which can be inspected as part of the request flow. In a pipe, a before/after action, etc.

**Comment by sam0x17** [comment]
I like the idea of having this in the request as well, as that would make it trivial to make subdomain-specific routes

**Comment by eliasjpr** [comment]
Subdomain routing support can be handled using a handler with a pipeline. Amber as a framework helps you in this case by enabling the developer to define different pipelines separating concerns at the request level.
