### ISSUE TITLE
Change name to "Crystal On Rockets"

### ISSUE THREAD

**Issue by da99** [amberframework/amber#321]
The "Amber" names doesn't leave much room for stupid puns. I suggest changing the name to "Crystal On Rockets" for more sensationalist marketing and dumb jokes:

Smug co-worker: "You're on Rails? Too bad. We're on Rockets!"
Book cover: "Explore the galaxy with Crystal On Rockets"

Think of all the visual puns people can create with "Crystal On Rockets": Crystals going to the moon, stars, etc.

Plus, rockets are more popular nowadays compared to train tracks. We can get in early on this re-newed space fad.

 😃

**Comment by faustinoaq** [comment]
Maybe we can use the slogan _Amber: Crystal on Rockets_ BTW Amber is a crystal 😉 

![screenshot_20171022_225234](https://user-images.githubusercontent.com/3067335/31871670-b2bcbf00-b77b-11e7-9680-b7dd02bfb32a.png)

Some rockets logos: (from Open Clip Art Library)

![screenshot_20171022_225324](https://user-images.githubusercontent.com/3067335/31871683-d0c5e97c-b77b-11e7-8e13-bab7f048ea6a.png)

![screenshot_20171022_225501](https://user-images.githubusercontent.com/3067335/31871714-0cfdaf4c-b77c-11e7-855b-830bb9749acc.png)

**Comment by da99** [comment]
@faustinoaq Some people (not me) might want two circular flames at the bottom of the rockets for phallic symbolism and crude jokes.
