### ISSUE TITLE
Error in src/app.cr:1: while requiring "../config/*"

### ISSUE THREAD

**Issue by netwarp** [amberframework/amber#322]
# Problem
#
I can't build, or watch my application.

### Description
`Error in src/FastApp.cr:1: while requiring "../config/*"
require "../config/*"
in config/application.cr:2: while requiring "amber"
require "amber"
in lib/amber/src/amber.cr:8: while requiring "redis": can't find file 'redis' relative to '/var/www/rdv/FastApp/lib/amber/src'
require "redis"
`

### Steps to Reproduce

1. I have installed amber 0.3.0
2. amber new FastApp
3. cd FastApp
4. amber watch

### Versions
ubuntu 16
crystal 0.23.1
amber 0.3.0

Thanks

**Comment by eliasjpr** [comment]
Did you ran ‘shards install’

**Comment by netwarp** [comment]
yes, the dependencies are here but in have a error after shards install:
git command failed: git archive --format=tar --prefix= master | tar -x -f - -C '/var/www/rdv/FastApp/lib/slang' (). Maybe a commit, branch or file doesn't exist?

**Comment by faustinoaq** [comment]
@netwarp I can't reproduce this issue. Try this:

```
amber new FastApp -d sqlite -t ecr --deps
cd FastApp
amber watch
```

**Comment by elorest** [comment]
@netwarp Can't reproduce. In your steps you didn't list running `shards install`. This is very important to do everytime you create a new project.

**Comment by elorest** [comment]
Is redis installed on the server?

**Comment by netwarp** [comment]
It's working. Thanks a lot.

**Comment by marksiemers** [comment]
@netwarp - Can this issue be closed?

**Comment by netwarp** [comment]
@marksiemers - Yes.
I just needed to install dependencies in sudo.
Thanks.

**Comment by rishavs** [comment]
as in `sudo shards install`?

**Comment by rishavs** [comment]
To add, `crystal deps build amby` is also failing. Not sure is this helps, but my root folder and webapp have different name. My root folder is called `diggamer` and the app itself is called `amby`

**Comment by faustinoaq** [comment]
> Syntax error in expanded macro: macro_140603294933216:1: expecting '\n' after '\r'

This error seems to be related to https://github.com/crystal-lang/crystal/issues/5831

/cc @obskyr, @straight-shoota, @ysbaddaden @RX14

**Comment by straight-shoota** [comment]
`shards install` shouldn't be run with `sudo`.

@rishavs This is an entirely different problem, please open a new issue for this. But as @faustinoaq stated, it's probably about incorrect line endings. Does your git config automatically force convert line endings to CR or something? (`git config core.autocrlf`)

**Comment by rishavs** [comment]
Hi @straight-shoota The problem was indeed due to incorrect line ending. My text editor was set to CRLF.
