### ISSUE TITLE
Unable to render layout in directory

### ISSUE THREAD

**Issue by adam-paterson** [amberframework/amber#324]
### Description

Defining a layout in a sub-directory of `src/views/layouts` causes compilation error:

```
expanding macro
in macro 'embed' /Users/adampaterson/Code/garnet-app/lib/kilt/src/kilt.cr:12, line 4:

   1.
   2.
   3.
>  4.       Slang.embed("layouts/new_app/new_application.slang", "__kilt_io__", )
   5.
   6.

expanding macro
in macro 'embed' /Users/adampaterson/Code/garnet-app/lib/slang/src/slang/macros.cr:2, line 1:

>  1.     {{ run("slang/slang/process", "layouts/new_app/new_application.slang", "__kilt_io__") }}
   2.

Error executing run: slang/slang/process "layouts/new_app/new_application.slang" "__kilt_io__"

Got:
```

### Steps to Reproduce

1. Create controller
**src/controllers/new_controller.cr**
```ruby
class NewController < ApplicationController
  LAYOUT = "new_app/new_application.slang"

  def index
    render("new_app/index.slang")
  end
end
```
2. Add route
**config/routes.yml**
```yaml
routes :web do
  get "/new", NewController, :index
end
```
3. Create layout
**src/views/layouts/new_app/new_application.slang**
```slim
body
  == content
```
4. Create view
**src/views/new_app/index.slang**
```slim
h1 New Application
```

5. Build (or amber watch)

**Expected behavior:**
- Layout is rendered with content from view

**Actual behavior:**
- Compilation error

**Reproduces how often:**
- 100%

### Versions
- Crystal 0.23.1 (2017-10-12) LLVM 4.0.1
- Amber CMD (amberframework.org) - v0.3.0
- macOS High Sierra 10.13.1 Beta (17B35a)

### Additional Information
- I've tried to debug this but only have `lldb` setup and have no access to vars in my IDE.

- Replacing `render()` with what the macro should be generating works as expected
```ruby
content = Kilt.render("src/views/new_app/index.slang")
Kilt.render("src/views/layouts/new_app/new_application.slang")
```
- I've tried a combination of `render` including defining all params in my call
- `src/view/layouts/new_application.slang` works when in the parent `layouts` directory

**Comment by faustinoaq** [comment]
I can reproduce this issue

Amber render wrapper is [here](https://github.com/amberframework/amber/blob/aa4f941ee06454dadfc958393603c4dc99dc02a8/src/amber/controller/render.cr#L5)

> I've tried to debug this but only have lldb setup and have no access to vars in my IDE.

Try using `gdb` also see: [Debugging Crystal using GDB](https://stackoverflow.com/questions/46369703/crystal-debugging-with-gdb/46567329#46567329)

**Comment by elorest** [comment]
Why do you want your view to be in a folder named differently from the controller?
```cr
  def index
    render("new_app/index.slang")
  end
```

**Comment by elorest** [comment]
`render` is a magic method that finds the directories for you based upon convention and what controller your in. 

If you controller is called `NewController` then your views should be a `src/views/new/` and your layouts should be in `src/views/layouts/`

If you choose to ignore conventions you have 2 options:

1. Use full paths
   ```cr 
LAYOUT = "src/views/layouts/new_app/new_application.slang"
# and
render("src/views/new/new_app/index.slang")
   ```
2. Just use kilt.
```cr
content = Kilt.render("src/views/new_app/index.slang")
Kilt.render("src/views/layouts/new_app/new_application.slang")
```

**Comment by faustinoaq** [comment]
@elorest but this issue also happens when you try to change the layout location

```crystal
class ApplicationController < Amber::Controller::Base
  LAYOUT = "foo/application.slang"
end
```

**Comment by elorest** [comment]
@faustinoaq true. I addressed that above though. If you want to change the assumed layout location, you need to use the full path. `LAYOUT = "src/views/layouts/new_app/new_application.slang"`

**Comment by elorest** [comment]
Rails also requires you to use the full path if you go outside of the expected folders. Although it does assume `app/views` for you when you hardcode it.

**Comment by elorest** [comment]
@adam-paterson Does that help?

**Comment by adam-paterson** [comment]
@elorest this is the actual layout and view
`src/controllers/admin/base_controller.cr`
`src/views/layout/admin/application.slang`
`src/views/views/admin/index.slang`

I don't believe this breaks convention. If it does I still think a user should be separate I simply want to have all admin controllers in a different directory to the frontend directories. Same issue would apply if I wanted to keep my `layouts` directory clean by separating different application areas.

**Comment by eliasjpr** [comment]
@elorest I think the information is a good candidate to be in the guides.

**Comment by elorest** [comment]
@adam-paterson Other than the layouts everything in that list is within convention. However your steps to reproduce above were all out of convention.

Why are you creating `layouts/admin/application.slang` instead of `layouts/admin.slang` This would fail in rails as well. 

@eliasjpr Good point. I'll do it.

**Comment by elorest** [comment]
https://github.com/amberframework/online-docs/blob/master/getting-started/views/README.md#render-method

**Comment by elorest** [comment]
@adam-paterson Most likely you'll like this.

**Comment by adam-paterson** [comment]
<p align="center"><img src="https://render.bitstrips.com/v2/cpanel/7897753-215157688_23-s4-v1.png?transparent=1&palette=1&width=250"/></p>

Great work @elorest, thank you. Although looking back, you're correct about the path I should be taking for my `admin` layout, this will certainly help when I'm creating other layouts in similar way. `admin/login.slang` for example.
