### ISSUE TITLE
memory leak when not using Docker image on Ubuntu 16.04

### ISSUE THREAD

**Issue by sam0x17** [amberframework/amber#326]
I got this error running a hello world amber app on an ubuntu digital ocean droplet for 24 hours -- the webserver now does not respond and I needed to restart the webserver process:

```
Params:
accept: Too many open files (Errno)
0x4fb307: *CallStack::unwind:Array(Pointer(Void)) at ??
0x6a96e4: accept_impl at /opt/crystal/src/socket.cr 226:11
0x6a94b3: accept? at /opt/crystal/src/socket/tcp_server.cr 100:20
0x69b998: listen at /opt/crystal/src/http/server.cr 163:7
0x632b2e: start at /root/bitfort-server/lib/amber/src/amber.cr 60:7
0x632590: run at /root/bitfort-server/lib/amber/src/amber.cr 40:9
0x63246e: start at /root/bitfort-server/lib/amber/src/amber.cr 21:5
0x4d0b5f: __crystal_main at /root/bitfort-server/src/bitfort.cr 3:1
0x4e40e9: main at /opt/crystal/src/main.cr 12:15
0x7f8776b3e830: __libc_start_main at ??
0x4cf329: _start at ??
0x0: ??? at ??
```

**Comment by sam0x17** [comment]
update: note that I was using `amber watch` in production mode. I have since switched to simply use `amber run`, so maybe this was the reason. I'll update this if the error occurs again

**Comment by eliasjpr** [comment]
Make sure the `ulimit` number is of reasonable size. Also `amber w` is recommended for development use `amber run -e production` it defaults to production anyways.

Let us know if you still experience the error.

**Comment by sam0x17** [comment]
thanks -- I'll post if I have an further problems

**Comment by sam0x17** [comment]
It seems to have happened again @eliasjpr . Also I checked ulimit and it says unlimited

```
200  | GET  "/"  | 496.0µs
Params:
200  | GET  "/"  | 292.0µs
Params:
accept: Too many open files (Errno)
0x418c35: ??? at ??
0x4feae2: ??? at ??
0x413186: ??? at ??
0x434d06: main at ??
0x7faf53261830: __libc_start_main at ??
0x40fe19: _start at ??
0x0: ??? at ??
```
```
root@fearless:~/bitfort-server# ulimit
unlimited
```

**Comment by sam0x17** [comment]
What's weird is when I try to force it to crash by refreshing hundreds of times a minute, it does not crash. Only thing that seems to crash it is if it stays idle for a few hours and then I hit the server again. It will load one time, then crash.

**Comment by sam0x17** [comment]
update: I have tried manually setting my hard and soft ulimits to 100000 from my `.bashrc` and restarting. Maybe this will keep it from crashing...

**Comment by drujensen** [comment]
Are you using a database?

**Comment by sam0x17** [comment]
No database -- literally just a hello world view

**Comment by drujensen** [comment]
@sam0x17 If there is a leak, then you only extended the time before another crash.  Can you determine what file handles are open before it crashes?

```bash
$ lsof -p 97073 | wc -l
```
where `97073` is the process id

**Comment by sam0x17** [comment]
@drujensen I think you are definitely right there is a leak. Here is my graph from the time I started the server in digitalocean:

![screenshot from 2017-10-24 13-55-13](https://user-images.githubusercontent.com/1855021/31959749-8a91c89c-b8c3-11e7-9d34-3cf05b4dc8f1.png)

Memory is increasing linearly over time.

Here is what I got doing lsof:

```
root@fearless:~# ps ax | grep app
 1596 pts/1    S+     0:00 /bin/sh -c PORT=80 AMBER_ENV=production ./app --
 1597 pts/1    S+     0:23 ./app
 8080 pts/0    S+     0:00 grep --color=auto app
root@fearless:~# lsof -p 1596 | wc -l
9
root@fearless:~# lsof -p 1597 | wc -l
1227
```
The second lsof call took a whole minute to return back

**Comment by drujensen** [comment]
What are the handles too that is causing the leak?  Are they IPv4?

`lsof -p 1597`

**Comment by sam0x17** [comment]
@drujensen they are all IPV4 it looks like everything that connects to it it never closes the socket

**Comment by drujensen** [comment]
strange! Who is trying to connect to your "hello world"?   Is your site popular for some reason? Why is the connection not closing after they get a response?  Are these browsers that are hitting your server or is it some sort of spider?

**Comment by sam0x17** [comment]
I have uptime robot pinging it once every 5 minutes. The domain name itself gets maybe 200-300 uniques a day so it's probably just random traffic. Definitely not too much for a $5 DigitalOcean droplet to handle, though.

**Comment by sam0x17** [comment]
What's weird is when I ran this via Docker in Google App Engine this did not happen. On this server I manually installed crystal and amber, so I'm guessing there is something about the Docker image that prevents this leak maybe, because I had it running for weeks in Docker just fine.

**Comment by sam0x17** [comment]
Server is running Ubuntu 16.04 -- it's a digital ocean droplet with the micro plan

**Comment by eliasjpr** [comment]
@drujensen could this be related to the benchmarks issue? 🤔

**Comment by drujensen** [comment]
@sam0x17 can you provide the response headers for your "hello world"?  Maybe just spit out the response to the log. 

I'm interested to see if the `Content-Length` is properly being set.  If the calling browser is expecting more data, the connection will not be closed

**Comment by sam0x17** [comment]
@drujensen feel free to curl it or do whatever you want it's at http://bitfort.io I'm googling right now but not 100% sure how to get the full response headers

**Comment by drujensen** [comment]
Ok, I verified the `Content-Length` returned 1651 which matches the byte count in the response.  Everything looks correct on the response side.  😕

**Comment by sam0x17** [comment]
weird

**Comment by eliasjpr** [comment]
@sam0x17 @drujensen is this still an issue?

**Comment by sam0x17** [comment]
@eliasjpr it is -- I was unable to figure it out so switched to the docker image and haven't had any problems.

**Comment by elorest** [comment]
@sam0x17 You said that on google cloud you weren't having this issue? Was your setup the same, or were you running docker on google cloud?

**Comment by elorest** [comment]
I'm not sure at what point file descriptors get out of control. I've had one running for a few hours and it looks fine, but after a few days it crashed because too many file descriptors were open.

**Comment by sam0x17** [comment]
As long as I'm in docker I don't have this issue. Eventually every web server I've tried this on that isn't docker has this issue. @elorest

**Comment by elorest** [comment]
I wonder what the difference could be. Do the file descriptors still increase inside of docker but the limit is way higher?

**Comment by sam0x17** [comment]
@elorest I don't think so -- I've had my docker image running for almost 2 months. It definitely would have run out of memory by now.

**Comment by elorest** [comment]
Oh yeah. We solved that. It's not actually a memory leak issue. Browsers
are just keeping the connections alive with keep alive. Every person who
visits your page is keeping alive about 6 or 7 connections. Those stay open
until the browser is completely closed.

Docker just has a lot more file descriptors by default so it's not ever
actually getting up to the Limit

**Comment by eliasjpr** [comment]
Referencing the fix for this here https://github.com/amberframework/amber/pull/443

**Comment by sam0x17** [comment]
Yeah in that case I'm going to assume this is fixed

**Comment by faustinoaq** [comment]
@sam0x17 #443 isn't merged yet, but yeah we assume this PR will fix it

BTW, Did you experienced this issue with other Crystal frameworks? or just Amber?

**Comment by sam0x17** [comment]
@faustinoaq I've only tried Amber for any extended period of time
