### ISSUE TITLE
amber encrypt fails for existing apps

### ISSUE THREAD

**Issue by adam-paterson** [amberframework/amber#327]
### Description
Running the `encrypt` command raises `ArgumentError("String contains null byte")` when encrypted environment config already exists

### Steps to Reproduce

1. Generate app with `amber new app`
2. Encrypt config with `amber encrypt`

**Expected behavior:**
- File is decrypted and configured editor is opened for user to edit environment config
- When edited the environment config is encrypted again

**Actual behavior:**
- "`Failed! Make sure to set AMBER_SECRET_KEY env or add hidden file .amber_secret_key`"
- Caused by Crystal's `String` raising `ArgumentError("String contains null byte")`

**Reproduces how often:**
- 100%

### Versions
- Crystal 0.23.1 (2017-10-12) LLVM 4.0.1
- Amber CMD (amberframework.org) - v0.3.0
- macOS High Sierra 10.13.1 Beta (17B35a)

### Additional Information
- None

**Comment by elorest** [comment]
The reason for this error is that the .amber_secret_key has been replaced. So you can't decrypt. We should probably handle this more gracefully though.

**Comment by eliasjpr** [comment]
Closing this issue
