### ISSUE TITLE
Index name needs to be unique

### ISSUE THREAD

**Issue by drujensen** [amberframework/amber#336]
### Description

The generator for reference types needs to include the table name os the index name is unique.

### Steps to Reproduce

```
amber new blog --deps
cd blog
amber g auth user
amber g post user:ref title:string body:text
amber g comment user:ref post:ref body:text
amber db create migrate seed
```

**Expected behavior:** [What you expect to happen]

Indexes created successfully

**Actual behavior:** [What actually happens]

```
$amber db create migrate seed
Created database blog_development
Migrating db, current version: 0, target: 20171028093628
OK   20171028093547_create_user.sql
OK   20171028093608_create_post.sql
An error ocurred executing migration 20171028093628. Error message is: relation "user_id_idx" already exists
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions
0.3.0

**Comment by marksiemers** [comment]
This could be tagged as a good first issue.
