### ISSUE TITLE
make install doesn't work

### ISSUE THREAD

**Issue by netwarp** [amberframework/amber#337]
### Description
I have a fresh ubuntu install. I have installed crystal, nodejs and postgre. 
I have installed all the package required to compile in crystal: https://github.com/crystal-lang/crystal/wiki/All-required-libraries

I have installed these packages too: sudo apt-get install build-essential libreadline-dev libsqlite3-dev libpq-dev libmysqlclient-dev libssl-dev

### Steps to Reproduce

these commands work:
`curl -L https://github.com/amberframework/amber/archive/stable.tar.gz | tar xz
cd amber-stable/
shards install`

the last command doesn't work:
`make install`

#### Error
`0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
♥Makefile:9: recipe for target 
make: *** [build] Interrupt    
                               
ubuntu@ubuntu-xenial:~/amber-st
Building amber in /home/ubuntu/
Unhandled exception in spawn:ob
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
Unhandled exception in spawn:  
fork: Cannot allocate memory (E
0x5c0015: ??? at ??            
0xb50605: ??? at ??            
0xd62e5b: ??? at ??            
0x5c3579: ??? at ??            
0x0: ??? at ??                 
♥Makefile:9: recipe for target 
make: *** [build] Interrupt    `

### Versions
crystal: Crystal 0.23.1
ubuntu: 16

**Comment by elorest** [comment]
You don't have enough memory to compile. Set up a swap file and you'll
easily be able to compile.

**Comment by faustinoaq** [comment]
@elorest I think we should distribute a static linked binary for amber

**Comment by netwarp** [comment]
Yes that works. Thanks a lot.

**Comment by elorest** [comment]
@faustinoaq Static linking with llvm is really hit and miss though. Would we include it for every OS, linux version?

**Comment by elorest** [comment]
Here's how to create a sufficient swap space.

```sh
sudo dd if=/dev/zero of=/swapfile bs=2k count=1024k
sudo mkswap /swapfile
sudo chmod 600 /swapfile
sudo swapon /swapfile
```

@faustinoaq Do you think we should add that too the docs or even the makefile somehow?

**Comment by faustinoaq** [comment]
@elorest I was able to compile some amber projects and I run the binary on CentOS, Ubuntu, ArchLinux without problems.

However @RX14 said for static compilation we should use Alpine Linux because it uses `musl` instead of `libc`, so static linking would be easier on Alpine.

In conclusion, Yes, if we can static compile Amber CLI, we should be able to run everywhere (x64 Linux)
