### ISSUE TITLE
[Nanobox] Populate Amber Guides

### ISSUE THREAD

**Issue by ylluminate** [amberframework/amber#343]
As per [this](https://nanoboxio.slack.com/archives/C65U2B25S/p1509124884000047):

> sanderson: There is now a branch of the guides project that has placeholder guides for crystal and amber: https://github.com/nanobox-io/nanobox-guides/tree/new/crystal 
>
> specifically, we just need actual content for the crystal and amber markdown files: https://github.com/nanobox-io/nanobox-guides/tree/new/crystal/articles/crystal
>
> It's all ruby/rails copy pasta right now
>
> danhunsaker: In other words, everyone @here is invited to dig in, make tweaks, and submit a PR to make these accurate for Crystal/Amber, using Ruby/Rails as the base for getting them working.

https://github.com/nanobox-io/nanobox-guides/tree/new/crystal/articles/crystal

**Comment by eliasjpr** [comment]
I have made some progress on this. I have to yet publish the docs. I am really liking Nanobox as another alternative tool for deployment and managing apps

**Comment by faustinoaq** [comment]
@ylluminate We're using https://amberframework.gitbook.io/amber/ now, Take a look! :tada:

**Comment by drujensen** [comment]
Closing this issue since we are using gitbook now.

**Comment by ylluminate** [comment]
Hmm, but what does this translate into guys? I'm still not clear and https://github.com/nanobox-io/nanobox-engine-crystal has, as of yet, to get any input and so the Nanobox folks appear to be at a standstill...

**Comment by faustinoaq** [comment]
@ylluminate You're rignt we still need to add some documentation here: https://docs.amberframework.org/amber/deployment

**Comment by ylluminate** [comment]
Okay, thanks for the clarification @faustinoaq. Also we probably need to contribute to the Nanobox docs themselves as first noted in order to both get finalization, more visible recognition of Crystal and its frameworks such as Amber, and catch any issues that need to be resolved for them to actually facilitate deployment. Seems like they're not responsive to the Trello issue now, but they also are pretty tied up with some other development issues at the moment from what I can tell given their new funding.

**Comment by eliasjpr** [comment]
We have to add documentation to the Nanobox guides. @ylluminate if you can take ownership of this task that would be of great help

**Comment by drujensen** [comment]
@ylluminate is this something you are still interested in contributing?

**Comment by ylluminate** [comment]
Reason this was closed?

**Comment by drujensen** [comment]
I didn’t get a response. Reopening.

**Comment by ylluminate** [comment]
I apologize, it slipped by my radar.  I'm in the thick of some things that are overly time consuming, but I've reached out to Nanobox for some input from their end as well.  This would be a really nice addition as we really love Nanobox.

**Comment by eliasjpr** [comment]
Nanobox was acquired by Digital Ocean we will halt any work around this until further noticed
