### ISSUE TITLE
Add `amber pipelines` to the CLI

### ISSUE THREAD

**Issue by marksiemers** [amberframework/amber#365]
### Description

I would like to see information about the pipelines for an app from the CLI, similar to the output format for `amber routes` - with information about the pipelines.

### Steps to Reproduce

1. Run `amber pipelines`
2. See output that it is not an option.

**Expected behavior:** [What you expect to happen]

I want to see information about the pipelines for an app, formatted in a table similar to `amber routes`

**Actual behavior:** [What actually happens]

The default output for the amber CLI is output (the help output)

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

All versions

### Additional Information

This is a "nice to have" shouldn't take priority.

**Comment by NeverHappened** [comment]
Created a PR with it. Please review it when you can
https://github.com/amberframework/amber/pull/550
