### ISSUE TITLE
One place for docs and guides

### ISSUE THREAD

**Issue by robacarp** [amberframework/amber#374]
### Description

Currently there are two places for information about working with amberframework, with a lot of overlap, but some differences. 

https://docs.amberframework.org/ is linked from a generated application as well as from the readme on this project.
https://amberframework.org/guides/ is linked from the framework website.

Is one of these old and the other new? If so, can we make some changes to the the right places to link to the same one everywhere? 

🍌

**Comment by faustinoaq** [comment]
Hi @robacarp There is an issue about that here 👉 https://github.com/amberframework/amberframework.org/issues/57

Both, documentations are based on https://github.com/amberframework/online-docs, however https://amberframework.org/guides/ is fetching latest content each time you visit the page, and https://docs.amberframework.org/  needs to be updated manually using gitbook.
