### ISSUE TITLE
Filter security / credential parameters from log files

### ISSUE THREAD

**Issue by fridgerator** [amberframework/amber#379]
### Description

Filter certain parameters from log files: `password`, `password_confirmation`, credit card information, etc

### Additional Information

Exposing passwords to log files is a security risk.  Other frameworks filter certain parameters in the logs.

Rails uses `Rails.application.config.filter_parameters` array

**Comment by faustinoaq** [comment]
Yeah, An issue to take in account on #346

**Comment by fridgerator** [comment]
IMO this should be prioritized, this is as bad as storing passwords in a database as plain text.

**Comment by eliasjpr** [comment]
Addressed in https://github.com/amberframework/amber/pull/450
