### ISSUE TITLE
uncaught exception parsing json if request body is empty

### ISSUE THREAD

**Issue by fridgerator** [amberframework/amber#380]
### Description

If a `GET` request is sent as `application/json` content type but there is no request body currently there is an uncaught exception trying to parse json.

I think empty request bodies should be ok.  Often in a javascript application a user will set the content type for all requests globally, and some requests might not have a request body.

```
Unhandled exception in spawn:
Nil assertion failed (Exception)
0x627d10: not_nil! at /usr/local/share/crystal-0.23.1-3/src/class.cr 65:0
0x7a5ebc: parse_json at /app/lib/amber/src/amber/router/params.cr 88:17
0x7a3aa1: parse_params at /app/lib/amber/src/amber/router/params.cr 33:9
0x7a3947: initialize at /app/lib/amber/src/amber/router/context.cr 36:5
0x7a3913: new at /app/lib/amber/src/amber/router/context.cr 33:3
0x979684: process at /usr/local/share/crystal-0.23.1-3/src/http/server/request_processor.cr 36:19
0x979429: process at /usr/local/share/crystal-0.23.1-3/src/http/server/request_processor.cr 16:3
0x979330: handle_client at /usr/local/share/crystal-0.23.1-3/src/http/server.cr 191:5
0x5d65d3: ~procProc(Nil) at /usr/local/share/crystal-0.23.1-3/src/kernel.cr 167:1
0x5f8bee: run at /usr/local/share/crystal-0.23.1-3/src/fiber.cr 255:3
0x5a05c6: ~proc2Proc(Fiber, (IO::FileDescriptor | Nil)) at /usr/local/share/crystal-0.23.1-3/src/concurrent.cr 61:3
0x0: ??? at ??
```

### Steps to Reproduce

1. Send a `GET` request with `Content-Type` header set to `application/json` without sending a body.

**Comment by faustinoaq** [comment]
Maybe we are using a `.not_nil!` in some place 😅

**Comment by fridgerator** [comment]
This was in 0.3.0, I need to check master to make sure its still an issue

**Comment by elorest** [comment]
Could you show me some example code. I have tests that work for asking for json but json isn't defined.

```cr
respond_with do
  html render(something)
end
```

Should give a 406 if you ask for only json.

**Comment by elorest** [comment]
Interestingly this issue has existed forever. Good catch. 
https://github.com/amberframework/amber/blob/master/src/amber/router/params_parser.cr#L97

**Comment by DmytroStepaniuk** [comment]
Well. The issue still exists in 0.7.2 🤔

**Comment by faustinoaq** [comment]
@DmytroStepaniuk Can you try amber master? 

```
git clone https://github.com/amberframework/amber.git
cd amber
shards build amber
bin/amber
...
```

**Comment by DmytroStepaniuk** [comment]
@faustinoaq 

I've changed `stard.yml`

to this one

```yams
  amber:
    github: amberframework/amber
    # version: 0.7.2
    branch: master
```

and everything works fine. But, anyway, thats kinda strange 🤔

**Comment by DmytroStepaniuk** [comment]
Maintainers! It would be great to release the fix
Issue isn't closed - stop the mission 😂

**Comment by faustinoaq** [comment]
@DmytroStepaniuk Yeah, we're preparing a new release :wink:
