### ISSUE TITLE
error: `undefined method 'get'` in scaffolded specs

### ISSUE THREAD

**Issue by drhuffman12** [amberframework/amber#387]
(FYI, https://gitter.io/amberframework/amber is down ... "can’t be reached".)

### Description

The scaffolded specs fail, noting the following error: `undefined method 'get'`.

### Steps to Reproduce

1. Clone [example_app_amber](https://github.com/drhuffman12/example_app_amber) and switch to the [drhuffman12/example_list_page](https://github.com/drhuffman12/example_app_amber/tree/drhuffman12/example_list_page) branch.

  * See also the steps noted in:
    * [Initial App Setup](https://github.com/drhuffman12/example_app_amber/blob/drhuffman12/example_list_page/doc/tutorial/a.initial_app_setup.md)
    * [Example "Hello World" list page](https://github.com/drhuffman12/example_app_amber/blob/drhuffman12/example_list_page/doc/tutorial/b.example_list_page.md)

2. Build, launch the docker container for the app

```sh
docker-compose build
docker-compose up -d # or without "-d" in a separate terminal
```

2. Shell into the docker container for the app

```sh
docker-compose exec app /bin/bash
```

3.  Based on the steps in the  [Initial App Setup](https://github.com/drhuffman12/example_app_amber/blob/drhuffman12/example_list_page/doc/tutorial/a.initial_app_setup.md) and [Example "Hello World" list page](https://github.com/drhuffman12/example_app_amber/blob/drhuffman12/example_list_page/doc/tutorial/b.example_list_page.md), after running the following steps, you end up with the `undefined method 'get'` error:

```sh
amber db migrate
crystal spec
```

**Expected behavior:** [What you expect to happen]

The specs should run; in particular, the `get "/worlds"` line should not error.

**Actual behavior:** [What actually happens]

Running `crystal spec` on the amber-scaffold-generated controller gives the following error:

```txt
Error in line 2: while requiring "./spec/controllers/world_controller_spec.cr"

in spec/controllers/world_controller_spec.cr:18: undefined method 'get'

      get "/worlds"
```

The Amber-scaffold-generated "spec/controllers/world_controller_spec.cr" file starts with the following code:

```code
01: require "./spec_helper"
02: 
03: def create_subject
04:   subject = World.new
05:   subject.name = "test"
06:   subject.save
07:   subject
08: end
09:
10: describe WorldController do
11:   Spec.before_each do
12:     World.clear
13:   end
14:
15:   describe "index" do
16:     it "renders all the worlds" do
17:       subject = create_subject
18:       get "/worlds"
19:       response.body.should contain "test"
20:     end
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from copy and pasting the output of `amber --version` and `amber --version` from the command line. Also, please include the OS and what version of the OS you're running.

```sh
root@8e729438f739:/app/local# crystal --version
Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1

root@8e729438f739:/app/local# shards --version
Shards 0.7.1 (2017-07-13)

root@8e729438f739:/app/local# amber --version
Amber CMD (amberframework.org) - v0.3.0
```

**Comment by marksiemers** [comment]
Thanks for the report @drhuffman12 
We are aware of this issue, and a fix will go in with this PR: https://github.com/amberframework/amber/pull/381

We hope to cut a released in the next couple days that includes the fix.

**Comment by marksiemers** [comment]
Regarding the gitter chatroom. I think gitter was having issues earlier.

It looks like there was a typo in the link you included, should be `.im` rather than `.io`
https://gitter.im/amberframework/amber

It's working now (gitter)

**Comment by drhuffman12** [comment]
Thanks. I'll keep an eye out for PR #381 to be merged and I'll check out the updated chatroom link.

**Comment by marksiemers** [comment]
@drhuffman12 - Hopefully it will go in today. Did you get the `.io` chatroom url from somewhere that we published? If so, we need to fix that.

Also, in that PR, our tests are now testing our tests - if that makes any sense, so it should minimize the chance of this kind of bug happening again.

**Comment by drhuffman12** [comment]
@marksiemers , When someone [creates a new issue](https://github.com/amberframework/amber/issues/new), the new issue content is pre-populated with various info, starting with a comment which includes the `.io` chatroom:

```txt
<!--
Have you read Amber's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/amberframework/amber/blob/master/.github/CODE_OF_CONDUCT.md
Do you want to ask a question? Are you looking for support? The Amber message board is the best place for getting support: https://gitter.io/amberframework/amber
-->
```

**Comment by drhuffman12** [comment]
@marksiemers , Yes, I was able to get to the `.im` chatroom; thanks.

**Comment by eliasjpr** [comment]
@drhuffman12 noticed that you have been waiting for #381 to be merged. This is now in the master branch and should be good to go.

**Comment by drhuffman12** [comment]
Thanks; I'll check. Am I guessing correctly that I will need to re-generate my scaffolded files; is that correct?

**Comment by marksiemers** [comment]
Since this is part of the CLI, you may have to either wait for the release (hopefully tomorrow) or build from source - https://amberframework.org/guides/getting-started/Installation/README.md#installation

You should be able to delete the spec files and run the scaffold again, and it will leave the existing files as-is.

I would, of course, test that in a separate branch, in case everything is overwritten.

**Comment by eliasjpr** [comment]
Closing this issue since it was waiting for #381 to be merged
