### ISSUE TITLE
Look into the Controller Action implementation in Routes

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#395]
### Description

Currently we have nested procs in order to process the route. It would be nice that we can clean this up and streamline the way actions are called.

> Important: @elorest has done some research on the performance of vs method calls. To his findings procs are slower than method calls.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `amber --version` and `amber --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by elorest** [comment]
https://carc.in/#/r/33k6

**Comment by eliasjpr** [comment]
Addressed with https://github.com/amberframework/amber/pull/396
