### ISSUE TITLE
The stable `.tar.gz` is not available via curl; Cannot build stable branch from source.

### ISSUE THREAD

**Issue by marksiemers** [amberframework/amber#400]
### Description

Building from source according to the guides is not working

### Steps to Reproduce
Using `stable` [per the guides](https://amberframework.org/guides/getting-started/Installation/README.md#installation) does not work
```
$ curl -L https://github.com/amberframework/amber/archive/stable.tar.gz | tar xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   128    0   128    0     0    264      0 --:--:-- --:--:-- --:--:--   264
100    15  100    15    0     0      9      0  0:00:01  0:00:01 --:--:--     0
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```
This is because that file is not found:
```
$ curl -L https://github.com/amberframework/amber/archive/stable.tar.gz
404: Not Found
```
Using a version does work:
```
$ curl -L https://github.com/amberframework/amber/archive/v0.3.5.tar.gz | tar xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   128    0   128    0     0    252      0 --:--:-- --:--:-- --:--:--   252
100  149k  100  149k    0     0   113k      0  0:00:01  0:00:01 --:--:--  468k
```
**Expected behavior:** [What you expect to happen]

Grabbing the stable version downloads the stable branch and decompresses it

**Actual behavior:** [What actually happens]

The file is not found

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

stable for amber

**Comment by elorest** [comment]
Fixed. Removed last night while cleaning up. SHA's also changed for tags. Fixed now.
