### ISSUE TITLE
brew install amber-crystal/amber/amber raisesSHA256 mismatch

### ISSUE THREAD

**Issue by CaDs** [amberframework/amber#401]
### Description
Installing Amber through brew with 
```brew install amber-crystal/amber/amber```
raisesSHA256 mismatch

### Steps to Reproduce

```
$brew install amber-crystal/amber/amber
==> Installing amber from amber-crystal/amber
==> Downloading https://github.com/amberframework/amber/archive/v0.3.5.tar.gz
Already downloaded: /Users/cads/Library/Caches/Homebrew/amber-v0.3.5.tar.gz
Error: SHA256 mismatch
Expected: 5bc48be991083b3d5d41ed7630a6ec29163d2bab4b29f74979ce495a30888fe1
Actual: 11061c5876d2af0901fcc1dfa26e1700e6e7757fa729f545c25efd0238f3bfa0
Archive: /my_root_path/Library/Caches/Homebrew/amber-v0.3.5.tar.gz
To retry an incomplete download, remove the file above.
```
Deleting the file and retrying doesn't solve it either.

**Expected behavior:** To get amber installed

**Actual behavior:** An error is raised

**Reproduces how often:** 100%

### Versions

v0.3.5  ?

### Additional Information

I guess brew is pointing to the wrong file since according to this post
https://amberframework.org/blog/2017/10/18/amber-0.3.0-has-been-released-including-enhancements-and-bug-fixes
Latest stable version of amber should be 0.3.0.

**Comment by robacarp** [comment]
I believe this is true. @marksiemers reported amberframework/homebrew-amber#35 a few hours ago.

**Comment by marksiemers** [comment]
@CaDs - This is working for me now, can you confirm it is working for you as well?

**Comment by elorest** [comment]
This is resolved. Was caused but cleaning the repo, which caused the content of release.tar.gz to change.

**Comment by CaDs** [comment]
@elorest  @robacarp  @marksiemers working fine now. 

Thanks a lot
