### ISSUE TITLE
`make` on master fails

### ISSUE THREAD

**Issue by robacarp** [amberframework/amber#409]
### Steps to Reproduce

1. `git clone git@github.com:amberframework/amber.git amber_upstream`
2. `cd amber_upstream`
3. `make`

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

```
Error in src/amber/cli.cr:1: while requiring "cli": can't find file 'cli' relative to '/Users/robert/Documents/repositories/amber_upstream/src/amber'

require "cli"
^

make: *** [build] Error 1
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

💯

**Comment by robacarp** [comment]
Bah, I think I need more coffee.

**Comment by elorest** [comment]
Did you run shards install?
