### ISSUE TITLE
Implement Test Generators for System, Controller Tests

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#414]
We now support System Tests and Controller tests. It would be nice to have generators to generate a skeleton test file.

...more details to come.

**Comment by eliasjpr** [comment]
I have started this and will open a work in progress PR in the online docs and reference it here soon

**Comment by marksiemers** [comment]
@eliasjpr - What do you think of using the error tests as a starting point: https://github.com/amberframework/amber/blob/master/src/amber/cli/templates/error/spec/controllers/%7B%7Bname%7D%7D_controller_spec.cr.ecr

**Comment by eliasjpr** [comment]
Closing this in favor of #640
