### ISSUE TITLE
[RFC] Standardize naming for pipe, pipeline, handler, middleware.

### ISSUE THREAD

**Issue by marksiemers** [amberframework/amber#420]
### Description

This mostly has to do with the folder that custom pipes are placed in. The `auth` generator uses `handlers` but there are preferences for other names, and it doesn't seem to be consistent.

If a naming convention is chosen, it may have an effect beyond just the folder name.

AFAIK, these are the potential options for names:
Could we get a vote on those names (for the folder), we can change the auth generator to use it as well - I may be able to incorporate that into the PR that I have going for it:
- handlers
- pipes
- pipelines
- middleware

**Comment by faustinoaq** [comment]
Let use pipes

`src/pipes` 👉 `Amber::Pipe`
`src/controllers` 👉 `Amber::Controller`

**Comment by eliasjpr** [comment]
pipes 👍

**Comment by drujensen** [comment]
Crystal uses `handlers` - https://crystal-lang.org/api/0.24.1/HTTP/Handler.html

but I like the metaphor of `plug`ging a `pipe` into a `pipeline`.

**Comment by docelic** [comment]
Yes, yes, I mean pipes were "standardized" in Amber, and the underlying concept of handlers is not visible.

**Comment by robacarp** [comment]
I'm all for pipes and pipelines, but `plug`sounds like the opposite of what it's accomplishing. I know you plug a lamp into the wall, but when I read plug I think about stopping things from leaking.

 What about connect, include, attach, link, etc?

**Comment by eliasjpr** [comment]
When designing the api I thought of connect as off when someone is connecting pipes together, but `plug` is shorter less typing and still means the same in the context of plugging together pipes.

**Comment by marksiemers** [comment]
This may be taking the analogy too far, but don't you `plumb` pipes together?

**Comment by eliasjpr** [comment]
Resolved #681 #664
