### ISSUE TITLE
Have anyone experienced cpu overloading? 

### ISSUE THREAD

**Issue by codingphasedotcom** [amberframework/amber#422]
I've noticed this 2 nights in a row while working on amber I don't know if its a crystal problem or amber problem. 
Literally have my amber application running on a terminal and a chrome tab opened. 
and for whatever reason my cpu is running at 100%. Everything is super slow can't even open activity monitor.

I'm using a new macbook pro 13inch 
2.9ghz 
8gb ram
versions of crystal and amber are both the latest ones.

**Comment by elorest** [comment]
Have you confirmed that amber is what's using 100% CPU?

**Comment by robacarp** [comment]
I’ve noticed heavy load when running with Sentry and just dismissed it to that. Never actually looked at the numbers though.

**Comment by drujensen** [comment]
I have ran top against amber and I don't see Amber taking any cpu cycles.

@codingphasedotcom can you run `top` and order (o) by cpu to verify its amber?

- What database are you using?
- Is there any polling going on?
- Websockets?

**Comment by faustinoaq** [comment]
I can reproduce it:

1) Try a websocket app, by example [ambrockets](https://github.com/faustinoaq/ambrockets)
2) Stop amber server but keep open chrome tab with websocket app
3) Wait some seconds (websocket reconection goes crazy)
4) See resource usage, almost 100% of CPU and RAM

![screenshot_20171201_115934](https://user-images.githubusercontent.com/3067335/33493822-52434076-d68f-11e7-8b64-0005a92e59f6.png)

@fridgerator Is `amber.js` reconecting properly?

**Comment by drujensen** [comment]
ok, so its client side javascript that is causing the CPU to go to 100%, not on the server, correct?

My guess is when you make a code change, Sentry is restarting the server and the client is not reconnecting correctly to the socket.

**Comment by fridgerator** [comment]
So its the browser using the cpu and not amber?

The reconnect timeout logic must be wrong, I should have time to check it out tonight or this weekend 👍

**Comment by faustinoaq** [comment]
@fridgerator You can try a workaround commenting [amber.js#L110](https://github.com/amberframework/amber/blob/master/assets/js/amber.js#L110)

However I found another issue, when using ambrockets, after reconnecting to server a can't send messages, I need to join channel again using chrome console.

Currently ambrockets client is using:

```js
import Amber from 'amber';

let socket = new Amber.Socket('/chat');
let messages = document.getElementById('messages');
let message = document.getElementById('message');

socket.connect().then(() => {
    let channel = socket.channel('chat_room:hello');

    channel.join();

    channel.on('message_new', payload => {
        let p = document.createElement('p');
        p.innerText = payload.message;
        p.innerHTML = `<b>${payload.user.trim()}: </b>` + p.innerText;
        messages.append(p);
        messages.scrollTop = messages.scrollHeight;
    });

    $('#form-message').on('submit', event => {
        event.preventDefault();
        channel.push('message_new', {
            user: $('.user').text(),
            message: message.value
        });
        message.value = '';
    });
});
```

but reconnect algorithm inside `amber.js` is doing this:

```js
      this.ws.onclose = () => {
        if (this.attemptReconnect) this._reconnect()
      }
```

```js
  _reconnect() {
    this.reconnectTimeout = setTimeout(() => {
      this.reconnectTries++
      this.connect(this.params)  // => How can I preserve current state? What about .then(...)?
      // this._reconnect() // => Commenting this line fix crazy reconnect behavior 
    }, this._reconnectInterval())
  }
```

So, `_reconnect` is working but channel setup disappear after reconnection, How can I preverse channel setup?

BTW, it happens after in every Sentry reload, using `amber watch` 😅

**Comment by fridgerator** [comment]
@faustinoaq I know why the socket reconnect goes crazy (see above PR).

That sounds like a separate issue / feature request.

I think on successful socket re-connect, we can loop through the `socket.channels` and re-join them.

And on channel.leave, remove the channel from the `socket.channels`

**Comment by faustinoaq** [comment]
Yeah, your PR fix this issue 🎉 

About channel issue, I added `.then(...)` code to `amber.js` and it rejoins successfully allowing me to send messages again without reload the browser:

```js
  _reconnect() {
    clearTimeout(this.reconnectTimeout)
    this.reconnectTimeout = setTimeout(() => {
      this.reconnectTries++
      this.connect(this.params).then(() => {
        this.channel('chat_room:hello').join();
      })
      this._reconnect()
    }, this._reconnectInterval())
  }
```

**Comment by codingphasedotcom** [comment]
Sorry went on vacation over the weekend and came back to see you guys already fixed it. @faustinoaq is like my guardian angel when it comes to crystal thanks again bro. @faustinoaq are you using linux or mac?

**Comment by faustinoaq** [comment]
@codingphasedotcom Yeah, already fixed on master, just wait for next amber version, meanwhile, as workaround you can add `clearTimeout(this.reconnectTimeout)` after line 106 here 👉 https://github.com/amberframework/amber/blob/v0.3.6/assets/js/amber.js#L106
