### ISSUE TITLE
Minimal configuration no longer works

### ISSUE THREAD

**Issue by fridgerator** [amberframework/amber#424]
### Description

In master, the [minimal configuration example](https://amberframework.org/guides/getting-started/Installation/minimal-configuration.md#minimal-configuration) no longer works.

It fails with the error `environment file not found for ./config/environments/development (Amber::Exceptions::Environment)`

Do we want to keep the option of running amber from a single file?  I thought it was pretty cool, but whether or not it provides any real world value, I dont know.

If its not a goal, then this is not an issue but we should remove the example.

**Comment by faustinoaq** [comment]
I vote for remove it

**Comment by robacarp** [comment]
I kind of like the idea of being able to make small, single file type servers with Amber, but if it's not working it should be removed until a working example can be made.

**Comment by elorest** [comment]
Remove it. Examples of should be in the CLI where are they can be tested.
Single file minimal configuration is also possible and Rails which is
useful for testing against rails environments in some cases. Mini test
rails uses this approach. I don't think we should have officially support
this example though as it's too hard to keep in sync without having it as
part of the tested framework.

**Comment by drujensen** [comment]
my vote would be to fix the `file not found` issue.  we should check to see if it exists before trying to load it.

**Comment by elorest** [comment]
If we want to leave it that's great but it has no place being in the docs
before `amber new`

**Comment by eliasjpr** [comment]
This has been removed

**Comment by faustinoaq** [comment]
> my vote would be to fix the file not found issue. we should check to see if it exists before trying to load it

Hi, minimal configuration example works again, tested on `v0.6.3`:

```
➜  onefile tree -L 1
.
├── lib
├── one.cr
├── shard.lock
└── shard.yml

1 directory, 3 files
➜  onefile cat one.cr    
require "amber"

class HelloController < Amber::Controller::Base
  def index
    "hello world"
  end
end

Amber::Server.configure do |app|
  pipeline :api do
  end

  routes :api do
    get "/", HelloController, :index
  end
end

Amber::Server.start
➜  onefile crystal one.cr
12:37:34 Server     | (INFO) [Amber 0.6.3] serving application "Amber_app" at http://localhost:3000
12:37:34 Server     | (INFO) Server started in development.
12:37:34 Server     | (INFO) Startup Time 00:00:00.000181000
```
