### ISSUE TITLE
Remove amber run

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#435]
### Description

We already have other commands for running crystal apps:

1. `crystal run src/app.cr` to run main file (development)
2. `shards build app` to install and build the project (production/development)

Keeping `amber watch` for detecting changes, recompiling and restarting the server during development

### Steps to Reproduce

1. `amber run`
2. Compare to `crystal run`
3. Very similar

**Expected behavior:** `amber run` is useless, let's use `crystal run`

**Actual behavior:** `amber run` exists.

**Reproduces how often:** 100%

### Versions

0.3.6

### Additional Information

I don't recommend to use `amber run` on production, best use `shards build` and then execute the binary.

**Comment by faustinoaq** [comment]
@amberframework/contributors

**Comment by eliasjpr** [comment]
Addressed with #452
