### ISSUE TITLE
Allow a controller to specify multiple `before_action` or `after_action` blocks

### ISSUE THREAD

**Issue by opiation** [amberframework/amber#436]
### Description

Currently, if 2 or more `before_action` blocks are defined in a single controller, only the last one is applied before controller actions.  It would be useful if they would all be kept and effective as it would allow for more elaborate macros to be used for conveniences likes resource loaders.

### Steps to Reproduce

```crystal
class PostController < ApplicationController
  before_action do
    only :index { puts "Never gets called." }
  end

  before_action do
    only :index { puts "Does get called." }
  end

  def index
    render "index.ecr"
  end
end
```

**Expected behavior:**

```
> Never gets called.
> Does get called.
```

**Actual behavior:**

```
> Does get called.
```

**Reproduces how often:** Always

### Versions

MacOS X 10.12.6
Amber CMD (amberframework.org) - v0.3.0

### Additional Information

Here's an example where this may be especially useful:

```crystal
class ApplicationController < Amber::Controller::Base
  macro load_resource(type_name)
    @{{type_name.id}} : {{type_name.camelcase.id}} | Nil = nil

  private def load_{{type_name.id}}
    @{{type_name.id}} = {{type_name.camelcase.id}}.find params["id"]
  end

  before_action do
    only [:edit, :show, :update] { load_{{type_name.id}} }
  end
end

class PostController < ApplicationController
  load_resource :post
  
  before_action do
    only :index { puts "Another useful pre-action behavior" }
  end

  def show
    # Use @post
  ...
end
```

**Comment by opiation** [comment]
From what I understand, this is the case because `before_action` and `after_action` macros each [define a single controller method `before_filters` and `after_filters` respectively](https://github.com/opiation/amber/blob/master/src/amber/dsl/callbacks.cr) which registers all the filters defined in the blocks passed to the macros.  Invoking said macros again defines `before_filters` or `after_filters` again, effectively superseding the previous definition.

I don't current have any ideas for a simple solution that allows `before_action` and `after_action` to be used in the same way, assuming this feature request is desirable.  I suspect however, that an effective solution may require that filters be registered at compile time and run at runtime instead of being both registered **and** run at runtime.

**Comment by eliasjpr** [comment]
@opiation thank you for submitting the issue. 

This could probably be an easy fix by calling super before the callback in the current scope gets called. I will take a shot a this, and if it turns out to be an easy fix we will go with it. 

Please feel free to propose a solution if you have one in mine.

We truly appreciate your feedback Nick! :)

**Comment by eliasjpr** [comment]
@opiation Im back. 

Maybe the following can help you accomplish what you are looking for.

When looking at at the example code you provided I wondered if there is an alternative solution instead of using multiple before actions. 

```crystal
# Note you will need to define a base type for all the classes that is being loaded via this mechanism
class ApplicationController < Amber::Controller::Base
  macro load_resources(type_name)
    if [:edit, :show, :update].includes? request_handler.action
      @{{type_name.id}} : @{{type_name.id}} : {{type_name.camelcase.id}} | Nil = {{type_name.camelcase.id}}.find params["id"]
    end
  end
end
```

```crystal
class PostController < ApplicationController
  # This returns a @post if the action matches :edit, :show, :update
  load_resource :post

  before_action do
     only :index { puts "Another useful pre-action behavior" }
  end
end
```

Hope this is helpful.
