### ISSUE TITLE
Can't seem to 'amber w' a newly generated project

### ISSUE THREAD

**Issue by Maast3r** [amberframework/amber#439]
### Description
 So I'm brand new to Crystal and Amber (so if I made a dumb mistake or forgot something please let me know), and I'm trying to make a fun project just to fool around with them. I followed the Crystal instructions to download Crystal for Ubuntu, and then the [Amber installation guide](https://amberframework.org/guides/getting-started/Installation/README.md#installation).

Next I followed the [Amber New Command](https://amberframework.org/guides/getting-started/cli/new.md#cli-new) and couldn't successfully run step 4, `amber w`.

### Steps to Reproduce

1. amber n test
2. cd test
3. shards build
4. amber w

**Expected behavior:**  It spins up an Amber app at localhost:3000

**Actual behavior:** It errors out on a 'signed cookie' variable. 
![image](https://user-images.githubusercontent.com/6621645/33787787-8038aa70-dc34-11e7-84ad-68fc7c58232e.png)

**Reproduces how often:** This problem occurs with every new project I make.

### Versions
![image](https://user-images.githubusercontent.com/6621645/33787959-3ebdb2a6-dc35-11e7-9ff9-60a78ddf8769.png)
![image](https://user-images.githubusercontent.com/6621645/33787966-493e952e-dc35-11e7-892d-82b2fcf04e43.png)
![image](https://user-images.githubusercontent.com/6621645/33787976-52003302-dc35-11e7-8b46-65e0c2de05bc.png)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by elorest** [comment]
@Maast3r this issue is caused when you compile from master because the generated shard.yml points to the last release. Master has diverged from last release so generated code will error against `0.3.6`.

Solutions:

1. Rebuild amber from stable branch and regenerate project.
1. Modify your generated shard.yml to point to `branch: master` instead of `version: ~>0.3.6`

**Comment by Maast3r** [comment]
That worked! Thanks for your help!
