### ISSUE TITLE
Sqlite DB can not be created from CLI

### ISSUE THREAD

**Issue by lukeholder** [amberframework/amber#446]
### Description

Creation of sqlite fails with cli commands

### Steps to Reproduce

1. create new project using sqlite

2. run `amber db create`

Get response saying:

`For sqlite3, the database will be created during the first migration.`

3. run `amber db create migrate`

Get response:

`Connection refused: sqlite3:./db/bigbirdoz_development.db`

4. run `amber db migrate`

Get response:

`Connection refused: sqlite3:./db/bigbirdoz_development.db`

**Expected behavior:**

The sqlite DB file should be created.

**Actual behavior:** 

Database is not being create in create or migrate commands.

**Reproduces how often:** 100%

### Versions

Amber CLI (amberframework.org) - v0.3.6

Crystal 0.23.1 (2017-10-12) LLVM 4.0.1

**Comment by lukeholder** [comment]
Looks like the error is due to no scaffolding being created before trying to migrate.

**Comment by faustinoaq** [comment]
@lukeholder yeah, `db/migrations` directory and sql files are created after amber scaffolding.

Maybe we can output some message saying, `No migration files were found` r something similar, WDYT?

**Comment by lukeholder** [comment]
@faustinoaq yes, it would make sense to say `No migration files were found`.

That new error combined with `For sqlite3, the database will be created during the first migration.` will clarify.

**Comment by eliasjpr** [comment]
Addressed here https://github.com/amberframework/amber/pull/452
