### ISSUE TITLE
Fix code style using ameba linter

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#465]
### Description

```
 ../ameba/bin/ameba 
Inspecting 166 files.

.........................F...F...............................................................F...................................F.............F....F.................                                                           

spec/amber/extensions/number_extension_spec.cr:6:8
LargeNumbers: Large numbers should be written with underscores: -5.542_3

spec/amber/router/router_spec.cr:129:9
VariableNames: Var name should be underscore-cased: route_a, not routeA

spec/amber/router/router_spec.cr:130:9
VariableNames: Var name should be underscore-cased: route_b, not routeB

spec/amber/router/router_spec.cr:131:9
VariableNames: Var name should be underscore-cased: route_c, not routeC

spec/amber/router/router_spec.cr:132:9
VariableNames: Var name should be underscore-cased: route_d, not routeD

spec/amber/router/router_spec.cr:134:20
VariableNames: Var name should be underscore-cased: route_a, not routeA

spec/amber/router/router_spec.cr:135:20
VariableNames: Var name should be underscore-cased: route_b, not routeB

spec/amber/router/router_spec.cr:136:20
VariableNames: Var name should be underscore-cased: route_c, not routeC

spec/amber/router/router_spec.cr:137:20
VariableNames: Var name should be underscore-cased: route_d, not routeD

spec/amber/router/router_spec.cr:140:80
VariableNames: Var name should be underscore-cased: route_a, not routeA

spec/amber/router/router_spec.cr:144:78
VariableNames: Var name should be underscore-cased: route_b, not routeB

spec/amber/router/router_spec.cr:148:79
VariableNames: Var name should be underscore-cased: route_c, not routeC

spec/amber/router/router_spec.cr:152:82
VariableNames: Var name should be underscore-cased: route_d, not routeD

src/amber/cli/commands/exec.cr:36:9
UnlessElse: Favour if over unless with else

src/amber/support/message_verifier.cr:13:5
RedundantBegin: Redundant `begin` block detected

src/amber/router/pipe/error.cr:7:7
RedundantBegin: Redundant `begin` block detected

src/amber/router/pipe/cors.cr:16:7
RedundantBegin: Redundant `begin` block detected

Finished in 104.38 milliseconds 

166 inspected, 17 failures.
```

### Steps to Reproduce

1. Clone amber framework repo
2. Execute [ameba](https://github.com/veelenga/ameba) tool
3. See output

**Expected behavior:** No errors

**Actual behavior:** 17 failures.

**Reproduces how often:** always

### Versions

`v0.5.0`

### Additional Information

> Ameba is a static code analysis tool for the Crystal language. It enforces a consistent Crystal code style, also catches code smells and wrong code constructions

by @veelenga

**Comment by veelenga** [comment]
@faustinoaq thanks for lifting this up.

Ameba is able to report a bag of useful stuff, but it is still a new tool and lacks of a bunch of features:

* more difficult rules, to detect more interesting cases (unreachable code, unused variable, unused method etc)
* semantic analysis. Crystal allows to use built-in type inference mechanism, which would help to report much more stuff knowing everything about types.  
* inline code disabling/configuring see https://github.com/veelenga/ameba/issues/28
* editor support. Currently it is possible to use [crystal-vim](https://github.com/rhysd/vim-crystal) together with [syntastic](https://github.com/vim-syntastic/syntastic) (see https://github.com/rhysd/vim-crystal/pull/43), but also planned to be added to [ale](https://github.com/w0rp/ale), also emacs and atom plugins.

Probably, it does not bring too much value for now, but it is planned to be grown in future.

You can run it on CI and also add to application template and force amber projects to have a consistent code style. But before you do the last, please ensure you generate application template consistent with Ameba (probably, a small test for verification would help).

Let me know if i can help 💚
