### ISSUE TITLE
CSRF token usability problems

### ISSUE THREAD

**Issue by infernalmaster** [amberframework/amber#467]
Amber generates new CSRF token for every request. So when user have site opened in few tabs and did some POST action on one of them, it will create new token and invalidate token for all other tabs.
And this also creates some problems with POST Ajax action, because I need to update token inside every form.

 I looked at Rails sources and it generates one token on session start https://github.com/rails/rails/blob/5.1.3/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L373 . Then it generates masked token for every request that is used inside html https://github.com/rails/rails/blob/5.1.3/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L291 . So I don't understand this part: Why it generates masked token if it can be easily unmasked? 

Good article about rails csrf: https://medium.com/rubyinside/a-deep-dive-into-csrf-protection-in-rails-19fa0a42c0ef

So I for my needs I just simply patched pipe to used persistent token without masking (as I said I don't understand the purpose of mask). https://github.com/infernalmaster/brendari/blob/master/src/handlers/csrf.cr Maybe this is less secure but much more easy to use

**Comment by eliasjpr** [comment]
@infernalmaster can you please open a PR with your proposed fix if we find it viable we would most likely approve the PR and merge to the codebase.

**Comment by infernalmaster** [comment]
With this PR token regeneration on every request can be turned of like that

```
plug Amber::Pipe::CSRF.new(false)
```

This should be mentioned in docs or maybe this value can be `false` by default.

**Comment by infernalmaster** [comment]
I read more about rails implementation and it's done like that to prevent http://breachattack.com. And I should improve code to prevent this type of attacks.

**Comment by infernalmaster** [comment]
So I did it like Rails do. IMHO performance of module `TokenOperations` can be improved. Old functionality can be turned on like that: 

```
Amber::Pipe::CSRF.token_strategy = Amber::Pipe::CSRF::RefreshableToken
```

I leaved it because it much faster than new one.

**Comment by elorest** [comment]
@infernalmaster what problems does refreshing every time have? Ajax forms should still be loaded dynamically. Even if they're stored just once per session you have to make sure that the ajax forms have the correct csrf. 

Refreshing every time is more secure because for long logins CSRF attacks could get smart and start sending the the correct csrf along with the post.

**Comment by infernalmaster** [comment]
I have form with file upload widget. Widgets sends files with Ajax to server then returns filename on server. Then one of form fields with that filename. With refreshable token:
1. every ajax response should also return new token ([example](https://github.com/infernalmaster/brendari/commit/37f50ec3fe57b1bc7b51fccde70ff59520f8b34a#diff-6d43edfe62cf142fe55afe9f57ac3bc0R15) )
2. csrf token inside html page should be updated with that value ([example](https://github.com/infernalmaster/brendari/commit/37f50ec3fe57b1bc7b51fccde70ff59520f8b34a#diff-0f0b4b2da7f8c959bd7dd2adb0ea5e30R24))

As you can see it's not so hard to handle that but needs some extra work. Maybe this workflow can be optimized with few helper functions

And problems with multiple browser tabs can be handled only for same browser. CSRF token can be updated through local storage listener for all tabs. Maybe this is not so important If this will be handled with more user-friendly message, because user just needs to refresh page to get new token.

**Comment by eliasjpr** [comment]
Ref issue https://github.com/amberframework/amber/issues/467

**Comment by eliasjpr** [comment]
Fixed with https://github.com/amberframework/amber/pull/474
