### ISSUE TITLE
Can't install Amber from source

### ISSUE THREAD

**Issue by netwarp** [amberframework/amber#468]
Hi,
I try to install Amber from source on a new virtual machine.
These commands work: 
`curl -L https://github.com/amberframework/amber/archive/stable.tar.gz | tar xz`
`cd amber-stable/`
`shards install`

But the last command does not work :  `make install`

This is my error message: 

> Error in src/amber/cli.cr:1: while requiring "cli"
require "cli"
in lib/cli/src/cli.cr:1: while requiring "./lib"
require "./lib"
in lib/cli/src/lib.cr:7: while requiring "./lib/*"
in lib/cli/src/lib/ios.cr:1: while requiring "./ios/*"
require "./ios/*"
in lib/cli/src/lib/ios/pipe.cr:10: IO is not a module, it's a class
include IO
Makefile:11: recipe for target 'build' failed

OS: ubuntu 16
How could I fix it ?
Thanks.

**Comment by netwarp** [comment]
Sorry I didn't see the last closed issues. The framework is not compatible yet with the new crystal's version.

**Comment by eliasjpr** [comment]
Amber 0.6.0 was recently released addressing the compatibility issue with crystal 0.24.1, please confirm so we can close this issue.

**Comment by netwarp** [comment]
Yes 👍
