### ISSUE TITLE
Npm and Amber watch seem to hold on to old data.

### ISSUE THREAD

**Issue by IanEarley** [amberframework/amber#475]
### Description

Npm and Amber watch seem to hold on to old data.
Changes are not reflected upon refresh of page.

### Steps to Reproduce

1. Run amber w 
2. make a change to project
3. attempt to refresh the page.

**Expected behavior:** Content updates to show changes

**Actual behavior:** No changes rendered (note: terminating amber watch and refreshing the page still renders server info in terminal)

**Reproduces how often:** 90%

### Versions

Amber Version - v0.6.0
Crystal Version - 0.24.1

OS - Gnome version 3.26.2

### Additional Information

running with crystal on different port is a way around this for now.

**Comment by elorest** [comment]
Seems to be related in someway to NPM. I can kill all crystal/amber processes and it still renders code to my browser.

**Comment by eliasjpr** [comment]
Somehow addressed with https://github.com/amberframework/amber/pull/457
