### ISSUE TITLE
Wishlist: Add named arguments to Amber::Pipe::Static.new

### ISSUE THREAD

**Issue by docelic** [amberframework/amber#478]
It would be great to have Amber::Pipe::Static accept named arguments.

This way one could write something like:

plug Amber::Pipe::Static.new( "./public", directory_listing: false)

Instead of non-intuitive positional arguments:

plug Amber::Pipe::Static.new( "./public", false, false)

**Comment by elorest** [comment]
This initializer is just borrowed from https://github.com/crystal-lang/crystal/blob/e2a1389e8165fb097c785524337d7bb7b550a086/src/http/server/handlers/static_file_handler.cr#L20

It should already work with named arguments.

**Comment by docelic** [comment]
Indeed, named arguments work.

plug Amber::Pipe::Static( "directory", directory_listing: false)

There is a bug present, though, which makes "directory_listing: false" having to be specified to disable directory listings, even though Amber (ineffectively) did try to default to false.

This will be fixed in an upcoming PR.
