### ISSUE TITLE
Logging offsets the amber routes table

### ISSUE THREAD

**Issue by marksiemers** [amberframework/amber#479]
### Description

Top border of `amber routes` output is pushed over due to logging label

### Steps to Reproduce

Run `amber routes` on any application with at least one route defined.

**Expected behavior:** [What you expect to happen]

Output of routes table to be as it was before.

**Actual behavior:** [What actually happens]

Top border is offset by logging label `Class`

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Amber CLI (amberframework.org) - v0.6.0

Crystal 0.24.1 (2017-12-26)
LLVM: 5.0.1
Default target: x86_64-apple-macosx

System Version: macOS 10.13.2 (17C88)
Kernel Version: Darwin 17.3.0

### Additional Information

<img width="682" alt="screen shot 2018-01-05 at 12 14 02 pm" src="https://user-images.githubusercontent.com/1305439/34626675-9668f6d0-f212-11e7-914c-71e37a48d834.png">

**Comment by marksiemers** [comment]
Adding a newline before the border may fix it, unless we want to suppress the `12:13:39 Class	|` output

**Comment by docelic** [comment]
Yes, the approach with newline is used in #494 which fixes this issue along the way.

**Comment by marksiemers** [comment]
Should be resolved in #494
