### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by kalicki** [amberframework/amber#486]
REST or GraphQL or Hybrid?
Trend in this new year is the migration of great webservices to GraphQL, it would be interesting to explore this in Amber. Native or separate lib.

Idea:
http://graphql-ruby.org
https://github.com/ziprandom/graphql-crystal by @ziprandom

_A feature that would be very interesting_

**Comment by eliasjpr** [comment]
This is duplicate of https://github.com/amberframework/amber/issues/265
