### ISSUE TITLE
make install not working

### ISSUE THREAD

**Issue by netwarp** [amberframework/amber#487]
### Description
Make install display this error: 
main_module:(.text+0xe99): undefined reference to `SSL_library_init'
main_module:(.text+0xe9e): undefined reference to `SSL_load_error_strings'
main_module:(.text+0xea3): undefined reference to `OPENSSL_add_all_algorithms_noconf'
main_module:(.text+0xea8): undefined reference to `ERR_load_crypto_strings'
O-penS-S-L-5858S-S-L-5858C-ontext.o: In function `*OpenSSL::SSL::Context::default_method:Pointer(Void)':
OpenSSL::SSL::Context:(.text+0x2): undefined reference to `SSLv23_method'

Error: execution of command failed with code: 1: `cc "${@}" -o '/home/ubuntu/amber-stable/bin/amber'  -rdynamic  -lsqlite3 `command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lyaml -lpcre -lm -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`

### Steps to Reproduce
curl -L https://github.com/amberframework/amber/archive/stable.tar.gz | tar xz
cd amber-stable/
shards install
make install

### Versions
Crystal: latest
Amber: latest
Ubuntu: 16

**Comment by eliasjpr** [comment]
Can you please use this link https://github.com/amberframework/amber/archive/v0.6.1.tar.gz. 

If you are trying to install amber an alternative installation can be performed using homebrew for Mac OS. 

`brew install amberframework/amber/amber`

**Comment by elorest** [comment]
Stable is the same as 0.6.1.

**Comment by elorest** [comment]
Make sure to install openssl dev. On Linux before building.

**Comment by netwarp** [comment]
openssl dev is missing.
I've done: apt-get build-dep nginx
The installation works. 
Thanks :)

**Comment by eliasjpr** [comment]
Can we close this?
