### ISSUE TITLE
README Information on production mode

### ISSUE THREAD

**Issue by Xosmond** [amberframework/amber#488]
I have noticed that there is not information on running Amber on production mode.

By the way, 
 - I was asking on how to log to a file instead of STDOUT? 
 - How to use correctly "process_count" (when I changed it to 2, I got an DB::Connection refuse)
Thanks

**Comment by eliasjpr** [comment]
Hellow @Xosmond 

> I was asking on how to log to a file instead of STDOUT?
Assuming that you have a directory in your project called `/logs` with a file `production.log`

In your config/application.cr 

```crystal
Amber::Server.configure do |settings|
  if Amber.env.production?
    log_file = File.open("./logs/production.log", "w")
    settings.logger = ::Logger.new(log_file)
  end
end
```

> How to use correctly "process_count" (when I changed it to 2, I got an DB::Connection refuse)

It could be very possible that you have not generated any models or migration yet. Scaffold a migration or model using amber cli `amber g scaffold Posts title:text` then run `amber db create migrate`

Hope this help. If not feel free to chat on gitter https://gitter.im/amberframework/amber or continue the thread here

**Comment by Xosmond** [comment]
@eliasjpr After some debugging, I can see that when I change `process_count` to two and i call `amber watch`, amber starts in development mode instead of production nevertheless `AMBER_ENV` variable

Anybody have an idea on why?

**Comment by elorest** [comment]
Amber watch should never be used for anything but development.

**Comment by Xosmond** [comment]
@elorest Yeah, but I was just making some benchmarks and understanding it.

**Comment by faustinoaq** [comment]
There is something about compiling amber for production:

you need to set `AMBER_ENV` in both, compilation and running phase.

```
AMBER_ENV=production shards build myapp
AMBER_ENV=production ./bin/myapp

# or

export AMBER_ENV=production

shards build myapp
./bin/myapp
```

So, `amber watch` doesn't work in production because it doesn't read `AMBER_ENV` variable when your project gets compiled.

> Thats why I was getting DB::ConnectionRefused because DB url on development file was not for production environment.

Did you solve this? 😅

**Comment by Xosmond** [comment]
@faustinoaq  I'm don't agree with you because of this:

Lets create an app with a basic post migration and then create an migrate the **production database** (using `AMBER_ENV=production amber db create migrate`).

Lets debug a little:
development.yml
```
....
process_count: 1
redis_url: "redis://localhost:6379"
database_url: postgres://localhost:5432/miracle_development
....
```
production.yml
```
....
process_count: 1
redis_url: "redis://localhost:6379"
database_url: postgres://localhost:5432/miracle
....
```

I run `AMBER_ENV=production amber watch` I got:
```
01:17:29 (INFO) Server	| [Amber 0.6.1] serving application "Miracle" at http://0.0.0.0:3000
01:17:29 (INFO) Server	| Server started in production.
01:17:29 (INFO) Server	| Startup Time 00:00:00.001172000
```
🙌 

Now lets change `process_count` on production file to `2`:
development.yml
```
....
process_count: 1
redis_url: "redis://localhost:6379"
database_url: postgres://localhost:5432/miracle_development
....
```
production.yml
```
....
process_count: 2
redis_url: "redis://localhost:6379"
database_url: postgres://localhost:5432/miracle
....
```

I run `AMBER_ENV=production amber watch` I got:
```
....
(DB::ConnectionRefused)
 (DB::ConnectionRefused)
  from lib/pg/src/pg/connection.cr:16:9 in 'initialize'
  from lib/pg/src/pg/connection.cr:7:5 in 'new'
....
```

So I changed `database_url` on development file to the same that is defined on production file:
development.yml
```
....
process_count: 1
redis_url: "redis://localhost:6379"
database_url: postgres://localhost:5432/miracle
....
```
production.yml
```
....
process_count: 2
redis_url: "redis://localhost:6379"
database_url: postgres://localhost:5432/miracle
....
```

I run `AMBER_ENV=production amber watch` I got:
```
01:18:56 (INFO) Server	| [Amber 0.6.1] serving application "Miracle" at http://0.0.0.0:3000
01:18:56 (INFO) Server	| [Amber 0.6.1] serving application "Miracle" at http://0.0.0.0:3000
01:18:56 (INFO) Server	| Server started in development.
01:18:56 (INFO) Server	| Server started in development.
01:18:56 (INFO) Server	| Startup Time 00:00:00.000888000
01:18:56 (INFO) Server	| Startup Time 00:00:00.000897000
```

Another test with 4 processes:
development.yml
```
....
process_count: 1
redis_url: "redis://localhost:6379"
database_url: postgres://localhost:5432/miracle
....
```
production.yml
```
....
process_count: 4
redis_url: "redis://localhost:6379"
database_url: postgres://localhost:5432/miracle
....
```

```
01:21:01 (INFO) Server	| [Amber 0.6.1] serving application "Miracle" at http://0.0.0.0:3000
01:21:01 (INFO) Server	| [Amber 0.6.1] serving application "Miracle" at http://0.0.0.0:3000
01:21:01 (INFO) Server	| [Amber 0.6.1] serving application "Miracle" at http://0.0.0.0:3000
01:21:01 (INFO) Server	| Server started in development.
01:21:01 (INFO) Server	| Server started in development.
01:21:01 (INFO) Server	| Server started in development.
01:21:01 (INFO) Server	| Startup Time 00:00:00.001076000
01:21:01 (INFO) Server	| Startup Time 00:00:00.001055000
01:21:01 (INFO) Server	| Startup Time 00:00:00.000848000
01:21:01 (INFO) Server	| [Amber 0.6.1] serving application "Miracle" at http://0.0.0.0:3000
01:21:01 (INFO) Server	| Server started in development.
01:21:01 (INFO) Server	| Startup Time 00:00:00.000647000
```

As we can see, amber is starting on development mode and using development `database_url` but is running the processes that are defined on production file.

**Comment by eliasjpr** [comment]
Fixed with #502

**Comment by Xosmond** [comment]
Great!

**Comment by faustinoaq** [comment]
> @faustinoaq I'm don't agree with you because of this:

Yes, I was a bit confused. Thank you for clarify me 👍
