### ISSUE TITLE
[CLI] Add amber update/upgrade to CLI

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#489]
### Description

I would be nice to have the Amber CLI update automatically when a new release is available. This will allow people to perform updates without much overhead if they have already the amber cli installed.

More details to come...

**Comment by robacarp** [comment]
Automatically upgrading an application would be great but even if all this command did was summarize manual steps recommended to update an app from the previous release, it would be very helpful.

**Comment by eliasjpr** [comment]
I am closing this since using `homebrew` and `linuxbrew` seems to be working well
