### ISSUE TITLE
Fix code amber auth example

### ISSUE THREAD

**Issue by maac4422** [amberframework/amber#493]
![captura de pantalla 2018-01-08 a la s 9 44 04 p m](https://user-images.githubusercontent.com/15006454/34702731-5b5e0cf8-f4bd-11e7-9565-ee7bde89378a.png)

Inside create method the first line need be fixed, should be like this: 
user = User.new(params.to_h.select(["email"]))

**Comment by eliasjpr** [comment]
Thank you for opening this issue. I believe this could be outdated since we have made some improvements around params.i will take a look at

**Comment by docelic** [comment]
It seems to me that the code in git master has this parts reworked, yes, and that the issue reported is no longer present.

**Comment by eliasjpr** [comment]
We have updated the Auth Recipe to demonstrate the `amber g auth` command.
