### ISSUE TITLE
Amber Watch - shouldn't start any server if compilation fails

### ISSUE THREAD

**Issue by robacarp** [amberframework/amber#499]
### Description

When developing with `amber w`, the server compiles and restarts automatically. However if the server has started once, and a successive restart fails to compile, the watch will just restart the old version of the server.

With the new logging, one request is enough to make the compiler errors disappear, and it can be confusing why new changes aren't showing up.

### Steps to Reproduce

1. build app, run `amber watch`, ensure app starts successfully
2. make a change to the app which will fail to compile.
3. observe compilation fails and then the server starts

**Expected behavior:** 

I think it makes sense to terminate the server and wait for a new change to retry compiling.

**Actual behavior:** 

Server starts with old code.

**Reproduces how often:** 100%

### Versions

```
> amber --version
Amber CLI (amberframework.org) - v0.6.0
> crystal --version
Crystal 0.24.1 (2017-12-26)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
```

![image](https://user-images.githubusercontent.com/208647/34793621-4bbcfa8c-f609-11e7-9efe-ebacf9b4edf8.png)

**Comment by faustinoaq** [comment]
Hi, fixed [here](https://github.com/amberframework/amber/pull/457/files#diff-9b4b623c272084b77e1c74c4e3111a48R36).

I'm just failed fixing [this](https://github.com/amberframework/amber/pull/457/files#r158740400). (I don't know how/why this happen 😅 )

**Comment by robacarp** [comment]
@faustinoaq with all the different work floating around with the watcher, I was hoping that this issue was already being worked on. Thank you!

**Comment by eliasjpr** [comment]
We should also add Process.new(args...).wait to avoid NPM from starting before the `amber w` is complete. Also I was considering that we change the order of the processes, NPM install first then Amber Watch. WDYGT?

**Comment by faustinoaq** [comment]
> We should also add Process.new(args...).wait to avoid NPM from starting before the amber w is complete. 

I think [this](https://github.com/amberframework/amber/blob/master/src/amber/cli/helpers/process_runner.cr#L70) is making `amber watch` a bit slow. I  [changed it](https://github.com/amberframework/amber/pull/457/files#diff-9b4b623c272084b77e1c74c4e3111a48R71) to run NPM once and in parallel, so we can have both as fast as possible watching the project files.

> I'm not sure the process order matters to me. I'd rather have both start as soon as possible so the server refresh time is as fast as possible.

I agree 👍

**Comment by faustinoaq** [comment]
I think, this is fixed on `v0.6.2`:

```
09:02:08 Watcher | Watching file: ././src/blog.cr
09:02:08 Watcher | Watching file: ././src/controllers/home_controller.cr
09:02:08 Watcher | Watching file: ././src/controllers/application_controller.cr
09:02:08 Watcher | Watching file: ././config/routes.cr
09:02:08 Watcher | Watching file: ././config/application.cr
09:02:08 Watcher | Watching file: ././src/views/layouts/application.slang
09:02:08 Watcher | Watching file: ././src/views/layouts/_nav.slang
09:02:08 Watcher | Watching file: ././src/views/home/index.slang
09:02:08 Watcher | Building project Blog...
Syntax error in src/blog.cr:5: for empty hashes use '{} of KeyType => ValueType'

{}
^

09:02:08 Watcher | Compile time errors detected. Shutting down...
```

**Comment by eliasjpr** [comment]
@faustinoaq which PRs address these issues?

**Comment by eliasjpr** [comment]
https://github.com/amberframework/amber/pull/525
