### ISSUE TITLE
Trim watcher logs

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#509]
### Description

`amber watch` logs a too loud. Suggested by @robacarp 

![watcher](https://i.imgur.com/sHic1AH.png)

I think we can reduce them to one line like `Watcher | Watching project files...` and using the file name only for Watcher updates like `Watcher | Watching: src/models/user.cr`

### Steps to Reproduce

1. Create a new amber project
2. Install dependencies
3. Execute `amber watch`

**Expected behavior:** Cleaner logs

**Actual behavior:** So many logs

**Reproduces how often:** 100%

### Versions

`v0.6.1`

### Additional Information

I know we can filter logs using environment settings but it would remove all Watcher logs.

**Comment by eliasjpr** [comment]
I was thinking we don't have to display the files at all, just a count of files would be fine or the directories being watched.

**Comment by faustinoaq** [comment]
For some reason this is still an issue on `v0.6.2` 😞
