### ISSUE TITLE
Create ORM initializer during 'amber new'

### ISSUE THREAD

**Issue by docelic** [amberframework/amber#519]
Currently, the file "config/initializers/granite.orm" (or the equivalent for crecto) is created only when the first migration is created, rather than on app creation.

The negative consequences of this are:

1) Database commands do not work until at least one migration (or anything that includes it, like a model) is created
2) If the user later renames the file, when the next migration is created it will get re-created with the original name and possibly cause a problem
3) At least for granite, the initializer is currently duplicated in both 'migration' and 'auth' code

The reason why this seems to have initially been done on a migration rather than on app creation, is that migration templates already have two separate directories (for granite and crecto), while the app template directory doesn't.

So, moving the ORM initializer file to a common location would be a simple task, but the real question is where exactly to move it, and how to then make the ORM-specific version be inserted during 'amber new', with only minimal/optimal changes to the current code.

**Comment by docelic** [comment]
Also, if the initializer is created during app creation, then also the following line must be added to the top of it (example of granite+pg):

require "granite_orm/adapter/pg"

(If that's not present, and no model is created, then nothing will call "require" and the Granite::ORM which is mentioned in the initializer won't exist.)

**Comment by drujensen** [comment]
@docelic Great catch!  I will update the PR #521

**Comment by docelic** [comment]
@drujensen awesome, great idea how to solve it in #521.
