### ISSUE TITLE
Amber should run an endless loop if server start fails

### ISSUE THREAD

**Issue by docelic** [amberframework/amber#520]
To reproduce:

Run  crystal src/app.cr  in one terminal and make it run successfully.

Run the same thing in another terminal, and due to address/port already being in use, it will start an endless loop trying to start the app.

**Comment by elorest** [comment]
This issue has already been opened and solved. https://github.com/amberframework/amber/issues/469

What version of amber are you running?

**Comment by elorest** [comment]
Just to verify I tested it with the last 2 version of amber and it worked as expected.
