### ISSUE TITLE
Directory db/migrations/ doesn't exist in default app structure

### ISSUE THREAD

**Issue by docelic** [amberframework/amber#522]
Directory db/migrations doesn't exist in default app structure.

This causes commands like 'amber db status' to fail with:

```
Applied At                  Migration
=======================================
Error opening directory 'db/migrations': No such file or directory
```

Is this something we want to fix, by e.g. just creating the empty directory?

**Comment by faustinoaq** [comment]
Maybe we can check if `db/migrations` exists first ?

Something like:

```crystal
if Dir.exists?("db/migrations")
  # execute db status
else
  # print message about running amber db create migrate
end
```

WDYT?
