### ISSUE TITLE
Homebrew install of v.0.6.3 fails with SHA256 mismatch

### ISSUE THREAD

**Issue by nicbet** [amberframework/amber#523]
### Description

==> Upgrading 1 outdated package, with result:
amber v0.6.3
==> Upgrading amber
==> Downloading https://github.com/amberframework/amber/archive/v0.6.3.tar.gz
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/amber-v0.6.3.tar.gz
Error: SHA256 mismatch
Expected: 94e42decca606b3e62386f32394aca7a8cc14386e265530cd77e8487f1b2e8df
Actual: f65711e2fdc473bd77142acce8c383e591d87ab666f81f1008973b4b2aebf353

### Steps to Reproduce

1. `brew update`
2. `brew upgrade amber`

**Expected behavior:** amber v.0.6.3 is installed

**Actual behavior:** fails with above error message

**Reproduces how often:** 100%, as tested on two different Mac machines (one is 10.12.6, other 10.13.3)

### Versions

v.0.6.3

**Comment by eliasjpr** [comment]
Can you please try running 

brew tap amberframework/amber 

Then 

brew install amber

**Comment by elorest** [comment]
@nicbet Can you try a `brew upgrade amber` again?

I changed it back to where I know it worked and it works for me.

**Comment by elorest** [comment]
@eliasjpr It was your suggestion a few months ago to automatically use the last release? I spent quite a bit of time on that because the only way to get it is from the API. 

How are people hitting the github rate limit. I can't imagine there are more than 100 installs a day or something. We can change it if we need to but I was surprised to run into a merge conflict where that had all be changed.

**Comment by elorest** [comment]
@nicbet Elias's answer above should work.

**Comment by eliasjpr** [comment]
I have learnt more about Homebrew and it’s inner workings since we last tried to get Amber to ship with homebrew. 

For instance the way we were testing for the version is something that the homebrew core team do not approve/recommends for formulas. Another thing learnt was that the version automatically gets parsed out from the url, one of the reason why we don’t need it if we pass the full release url

If I made the suggestion in the past to use the version it was because I had a different understanding than now. Sorry about that

**Comment by nicbet** [comment]
@elorest The instructions provided by @eliasjpr did not resolve the issue (had 0.3.6 already installed through tap, re-tapping did as far as I can tell nothing).

 However, deleting the already downloaded archive of v.0.6.3 and re-issuing `brew upgrade amber` did indeed complete successfully this time around.

```
nicbet@Smortjebroed  ~  brew tap amberframework/amber                                                                                                
==> Tapping amberframework/amber
Cloning into '/usr/local/Homebrew/Library/Taps/amberframework/homebrew-amber'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Tapped 1 formula (29 files, 24.1KB)

nicbet@Smortjebroed  ~  brew install amber                                                                                                           
==> Installing amber from amberframework/amber
Error: amber v0.3.6 is already installed
To upgrade to v0.6.3, run `brew upgrade amber`

nicbet@Smortjebroed  ~  brew upgrade amber                                                                                                           
==> Upgrading 1 outdated package, with result:
amberframework/amber/amber v0.6.3
==> Upgrading amberframework/amber/amber
==> Downloading https://github.com/amberframework/amber/archive/v0.6.3.tar.gz
Already downloaded: /Users/nicbet/Library/Caches/Homebrew/amber-v0.6.3.tar.gz
Error: SHA256 mismatch
Expected: f65711e2fdc473bd77142acce8c383e591d87ab666f81f1008973b4b2aebf353
Actual: 188790b260accb35e4f077abd1c37eafef9aedd9b580194a56e6d95edb4f5e51
Archive: /Users/nicbet/Library/Caches/Homebrew/amber-v0.6.3.tar.gz
To retry an incomplete download, remove the file above.

nicbet@Smortjebroed  ~  rm /Users/nicbet/Library/Caches/Homebrew/amber-v0.6.3.tar.gz                                                                 

nicbet@Smortjebroed  ~  brew upgrade amber                                                                                                           
==> Upgrading 1 outdated package, with result:
amberframework/amber/amber v0.6.3
==> Upgrading amberframework/amber/amber
==> Downloading https://github.com/amberframework/amber/archive/v0.6.3.tar.gz
==> Downloading from https://codeload.github.com/amberframework/amber/tar.gz/v0.6.3
######################################################################## 100.0%
==> shards install
==> make install PREFIX=/usr/local/Cellar/amber/v0.6.3
🍺  /usr/local/Cellar/amber/v0.6.3: 5 files, 5.0MB, built in 1 minute 24 seconds
```

**Comment by drujensen** [comment]
I think this is caused from retagging the version.

**Comment by eliasjpr** [comment]
I believe this has been resolved

**Comment by elorest** [comment]
brew untap amberframework/amber
brew install amberframework/amber/amber
