### ISSUE TITLE
Model: add -m option to change model: granite, crecto or jennifer

### ISSUE THREAD

**Issue by elorest** [amberframework/amber#54]
Implemented in a way that separates the behavior that we want to express (entities) from the persistence layer (repositories and database). This design helps keep the interface of our objects small and therefore keeps them fast and reusable.

**Comment by elorest** [comment]
Perhaps we should remain ORM/REPO agnostic and add generators for different libraries?

**Comment by eliasjpr** [comment]
At the moment, I think this is the best we can do until we have time to discuss technical details.

**Comment by jwoertink** [comment]
It's actually pretty interesting that there's no built in model. This doesn't have to be another MVC. Having it handle routes, controllers, views, middleware, etc.. is quite a bit already. Being able to just plug in your own way of handling models and other business logic type stuff would be nice. Maybe there could be a separate shard for a "amber" type way of handling this stuff, but by default not in the amber shard.

**Comment by oz** [comment]
That being said, seeing how the router is inspired from Phoenix, I though I'd find [Crecto](https://github.com/Crecto/crecto) in there too. As long as it is easy to swap parts, I think that an "all-in-one" opinionated model makes sense (even if I had a different opinion on the ORM :wink:).

**Comment by eliasjpr** [comment]
@oz We are considering to support Crecto for a Repo pattern type of models and Granite/Jennifer for Active Record Pattern with generators we still thinking about this one

**Comment by drujensen** [comment]
Here is the example app created by @fridgerator for using crecto with amber:
https://github.com/fridgerator/amber_crecto_example

**Comment by drujensen** [comment]
I am going to close this since we support `granite` and `crecto`.  We can open a new ticket if someone wants to add `jennifer`.
