### ISSUE TITLE
Improvements needed to 'cors' pipe

### ISSUE THREAD

**Issue by docelic** [amberframework/amber#540]
In the 'cors' pipe, at the top we have:

        ...
        @allow_headers = "accept, content-type",
        @allow_methods = "GET, HEAD, POST, DELETE, OPTIONS, PUT, PATCH",

These two variables being strings is a problem because later, methods and header names are checked for being "allowed" by doing allow_headers.includes?(word).

Since includes? on Strings includes substrings, this incorrectly makes e.g. header name "acc" be allowed because that's a substring of "accept".

It seems like the easy fix here would be to just turn those two to arrays and the rest would work as expected. (Unless we do not actually want these configurable, in which case they should be constants.)

**Comment by drujensen** [comment]
@docelic These variables need to be configurable.   Maybe we can parse them into an array during initialization?

**Comment by docelic** [comment]
@drujensen Done so in the latest commit on #539
