### ISSUE TITLE
Underscore is not a valid character for DigitalOcean machines.

### ISSUE THREAD

**Issue by gabrielengel** [amberframework/amber#546]
Hi!

Whenever we try to create a machine on digitalOcean that contains `_` it will fail

https://github.com/amberframework/amber/blob/211dd91b3aac9832a4b42fd8e29e9d7d9f9d2a65/src/amber/cli/commands/deploy.cr#L38

```rb
# We could only remove `|_` from the regexp:
@server_name = "...".gsub(/[^\w\d\-]/, "")
```

Is there any reason to keep underscores on the server name?

**Comment by eliasjpr** [comment]
PR https://github.com/amberframework/amber/pull/548

**Comment by eliasjpr** [comment]
PR https://github.com/amberframework/amber/pull/548

**Comment by marksiemers** [comment]
How fun, postgresql doesn't like dashes `-` and digital ocean doesn't like underscores `_`

I wonder what heroku doesn't like.
