### ISSUE TITLE
Prevent Index out of bounds error when running `amber db migrate` with no migrations

### ISSUE THREAD

**Issue by marksiemers** [amberframework/amber#554]
### Description

When running `amber db migrate` and there are no migration files, you get a runtime, `Index out of bounds` error.

This could be fixed in micrate, but also, we can prevent it in the CLI.

This is particularly a problem with deploying to heroku, as the buildpack automatically runs migrations.

### Steps to Reproduce

Create a new amber project and run `amber db create migrate`

**Expected behavior:** [What you expect to happen]

No run-time error and maybe a warning about no migrations being present.

**Actual behavior:** [What actually happens]

Runtime error: `Index out of bounds`

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Additional Information

Likely this is the best place to check if any migration files exist: https://github.com/amberframework/amber/blob/master/src/amber/cli/commands/database.cr#L42

Issue with micrate: https://github.com/juanedi/micrate/issues/26

Micrate is no longer actively maintained, but amberframework may take over.

**Comment by eliasjpr** [comment]
@marksiemers we can either maintain micrate or migrate.

**Comment by eliasjpr** [comment]
We should have a check on amber regardless of the `shard` used
