### ISSUE TITLE
[Assets] Asset helper w/ cached assets

### ISSUE THREAD

**Issue by JoshJuncker** [amberframework/amber#555]
It seems that Amber currently lacks a default convention for caching/versioning bundled assets as well as referencing those cached assets from views (think sprockets in rails).  Since Amber already relies on webpack, it would make sense to configure webpack for caching/fingerprinting in production and set up a crystal asset helper that is included in views to easily reference these files (ex. javascript_pack_tag, stylesheet_pack_tag, asset_pack_path, asset_pack_url). 

A good reference for doing so would be https://github.com/rails/webpacker, however it obviously doesn't have to be the exact same.  It still allows configuration/customization, but comes with a preferred set of defaults out of the box.

**Comment by eliasjpr** [comment]
@JoshJuncker thanks for the good suggestion. 

Would you mind opening a PR with the proposed changes, I think is a good contribution

**Comment by robacarp** [comment]
@eliasjpr what do you think of putting code / functionality like this in external shards?

**Comment by JoshJuncker** [comment]
@eliasjpr Would you guys want the program to fail to compile if you try to reference an asset that doesn't exist?

**Comment by elorest** [comment]
I think it would probably make sense to build into amber since it depends on configuration in a generated amber project. Also the more shards were dependent on the more brittle our project becomes

**Comment by drujensen** [comment]
#574 will address this issue if someone wants to pickup the mantle and bring this home.

**Comment by jackturnbull** [comment]
@drujensen I can take a look, although I can't promise much! Do you know what needs doing? Is it mainly the conflicts?

**Comment by jackturnbull** [comment]
PR Raised: https://github.com/amberframework/amber/issues/555
