### ISSUE TITLE
Create other github repository for amber websocket js helper

### ISSUE THREAD

**Issue by roquie** [amberframework/amber#567]
Amber helpers [for js](https://github.com/amberframework/amber/tree/master/assets/js) is not possible to use outside of framework (if Amber use only for API and javascript app located in other repo). May be create a npm package for this?

**Comment by drujensen** [comment]
yeah, we don't have an npm package (yet).  You can grab a minimized version if you don't want to use the npm webpack alias.  https://github.com/amberframework/amber/blob/master/assets/js/amber.min.js
