### ISSUE TITLE
Crecto integration

### ISSUE THREAD

**Issue by wontruefree** [amberframework/amber#575]
### Description

The template Crecto integration seems to have a few bugs.

### Steps to Reproduce

default install of amber
amber new a project with the `-m crecto`

**Expected behavior:** 
`amber database create migrate` should work with no errors
`amber watch` start the server

**Actual behavior:**
failures on multi type including nil

**Reproduces how often:**
every time I do a new setup

**Comment by faustinoaq** [comment]
Duplicated of #560 , solved by #563
