### ISSUE TITLE
[Mailer] Avoid mail delivery on development environment

### ISSUE THREAD

**Issue by gabrielengel** [amberframework/amber#581]
### Description

As a developer, I am not interested in actually delivering e-mails on my developing machine. Printing them to the console will be good enough. The way I found around this is by creating a new `BaseMailer` with a `deliver` method - that will be invoked by child classes.

Main change will be that all `mailers` will be inherited by the base mailer. Something like this:

```crystal
class BaseMailer < Quartz::Mailer  
  def deliver
    if ENV["AMBER_ENV"] == "development"
      puts @message.body
    else
      super
    end
  end
end

class UserWelcomeMailer < BaseMailer
   # initialize, deliver... etc.
end
``` 

### Steps to Reproduce

1. Create a new amber app
2. Create a mailer
3. Inject above code and inherit `YourMailer` from `BaseMailer`
4. Invoke `YourMailer.new.deliver`

### Doubts

- Should this class live in the app or inside Amber?
- Should we generate alongside with the app?
- Should we do this at all?

**Comment by drujensen** [comment]
@gabrielengel I recommend using mailcatcher or something similar and pointing your development environment smtp setting to that.  There is a docker image that you can add to the docker-compose.yml if you want to use it.  https://hub.docker.com/r/drujensen/mailcatcher/

**Comment by eliasjpr** [comment]
Can we close this issue?

**Comment by eliasjpr** [comment]
Closing this since there seems to be Amber setting and Quartz Mailer settings to handle this case

**Comment by elorest** [comment]
Looks good.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005
