### ISSUE TITLE
Incorrect handling of Accept header

### ISSUE THREAD

**Issue by grig191** [amberframework/amber#584]
### Description

Using following code in controller
```crystal
  def example_action
    ...
    respond_with do
      text("...")
      json("...")
    end
  end
```
Will act like expected when looking in browser, but when using `curl` or `wget` or another HTTP client, will always return HTTP code 406: Not Acceptable
The reason for this is incorrect handling of Accept HTTP Header: HTTP clients set this to "*/*", indicating that they can handle of types of data returned by server. Amber server can't understand this and returns error 406

Workaround for this was permanently setting this header to my browser's, but this is not valid fix.

**Expected behavior:** Return valid response
**Actual behavior:** Incorrect handling of HTTP Header "Accept" when set to "*/*"

### Versions

Using latest crystal and amber versions:
```
Crystal 0.24.1 (2017-12-22)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```
```
Amber CLI (amberframework.org) - v0.6.4
```

**Comment by eliasjpr** [comment]
Can you please post the curl example used? You can also make your curl requests as  localhost:3000/index.json for example and the response will be of content type JSON

**Comment by eliasjpr** [comment]
We can add */* as part of the accept headers to be handle

**Comment by grig191** [comment]
As far is I know, adding .json to request url returned to me 404, I will try again later.
I managed to fix it by handling */* in pull request #586

**Comment by eliasjpr** [comment]
@elorest might want to jump in this conversation as well

**Comment by elorest** [comment]
.json still works as expected for me.
