### ISSUE TITLE
Error in params.valid?

### ISSUE THREAD

**Issue by docelic** [amberframework/amber#590]
Do we have a bug somewhere in params.valid?

With controller code like this:

```
params.validation do
  required(:name) { |n| n.size > 10 }
end
params.valid?
render("index.ecr")
```

This correctly returns false if parameter "name" is provided, but is not longer than 10 chars.
But if parameter "name" is missing altogether, instead of returning false, Amber raises:

ERROR: The name param was not found, make sure is typed correctly. (Amber::Exceptions::Validator::InvalidParam)

(And also there seems "it" is missing in the error text.)

**Comment by eliasjpr** [comment]
Need to use optional instead of required

**Comment by docelic** [comment]
But valid? shouldn't raise. Validate! should raise while valid? should only return true/false.
It makes no sense that a value missing causes a raise on valid?, but only results in false is value is present but does not pass validation. Don't you think?

**Comment by eliasjpr** [comment]
Correct, based on the method definition `valid?` does not raise an error. What's causing it is that **required** is expecting `:name` to always be present in the request payload. You must use optional in this case since it is not a `required` parameter or define another set of parameters for the specific controller action.

See https://github.com/amberframework/amber/blob/master/src/amber/validators/params.cr#L100

**Comment by docelic** [comment]
What I am saying is -- do we agree that the point of "valid?" is to check whether the parameters are valid or not, without raising an exception?

If yes, then the code inside 'def valid?' should be wrapped in begin..end and return 'false' if an exception is raised by 'require'.

If not, then this means that valid? can raise, and that users cannot simply call valid? to test validity of arguments, but they need to wrap valid? in begin...end themselves.

I will submit a PR to make this work the way I think it should work, so maybe it will become clearer with an example.

Thanks!

**Comment by docelic** [comment]
https://github.com/amberframework/amber/pull/593
