### ISSUE TITLE
Crecto logs are blocking amber logs

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#617]
### Description

This line `Crecto::DbLogger.set_handler(Amber.settings.logger)` is blocking amber logs output.

### Steps to Reproduce

1. Create a new amber project using crecto model
2. Compile and execute it
3. Some logs aren't displayed at all

**Expected behavior:** All logs are displayed, even crecto ones.

**Actual behavior:** Neither amber nor crecto logs are displayed, just watcher ones by amber::cli

**Reproduces how often:** 100%

### Versions

amber `v0.6.5`

### Additional Information

![vokoscreen-2018-02-02_12-11-14 1](https://user-images.githubusercontent.com/3067335/35747554-ab698c90-0818-11e8-9504-6c795d1349fa.gif)

/cc @fridgerator @eliasjpr

**Comment by faustinoaq** [comment]
See more here: https://youtu.be/rbWEvHmVnOs?t=278

**Comment by eliasjpr** [comment]
Is there a solution for this on our side Or do we have to ping @fridgerator?

**Comment by faustinoaq** [comment]
Maybe we can try using `Crecto::DbLogger.set_handler(Amber.settings.logger.dup)`, I tested it and works without issues.
