### ISSUE TITLE
Teeplate version error

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#635]
### Description

Hey, I'm getting a dependency error:

```
Fetching https://github.com/amberframework/teeplate.git
Error resolving teeplate (~> 0.5.0)
```

But teeplate doesn't have tag 0.5.0: https://github.com/amberframework/teeplate/tags

And we are using it: https://github.com/amberframework/amber/blob/stable/shard.yml#L37

### Steps to Reproduce

1. Try to install amber dependencies
2. See dependency error

**Expected behavior:** Dependencies were installed

**Actual behavior:** Dependencies error

**Reproduces how often:** 100%

### Versions

v0.6.5

### Additional Information

Dependency error is also shown in Travis

**Comment by faustinoaq** [comment]
Closing this, teeplate v0.4.5 is v0.24.1 incompatible

teeplate v0.5.0 was released here: https://github.com/mosop/teeplate/pull/10

**Comment by robacarp** [comment]
@faustinoaq I recreated the amberframework/teeplate repo from msop just recently. It may need a release cut.
