### ISSUE TITLE
Should generated apps run migrations against the test database at the start of a spec run?

### ISSUE THREAD

**Issue by robacarp** [amberframework/amber#646]
### Description

I have this code in my spec_helper and it's saved me a ton of headache:

```crystal
require "micrate"
Micrate::DB.connection_url = Amber.settings.database_url
Micrate::Cli.run_up
```

Is that something worth adding to the generator?

**Comment by eliasjpr** [comment]
I won't mind adding this to the generators

**Comment by docelic** [comment]
Oh this would be nice because "amber db" supports only a subset of micrate's commands/options.
