### ISSUE TITLE
[Router] Allow posting array of fields from form

### ISSUE THREAD

**Issue by imdrasil** [amberframework/amber#675]
### Description

As a developer
I would like to get an opportunity to submit array of values.

### Steps to Reproduce

From template:

```html
<form method="post" action="/user">
<!-- ... -->
<input type="checkbox" value="admin" name="role[]">
<input type="checkbox" value="owner" name="role[]">
</form>
```

Controller code:

```crystal
def create
  user_params["role"] # ["admin", "owner"]
end
```

**Comment by robacarp** [comment]
@eliasjpr is this different from the updates to params that recently merged in?

**Comment by eliasjpr** [comment]
@robacarp no

@imdrasil you have to use  user_params.fetch_all?("role")

Duplicate of https://github.com/amberframework/amber/issues/592

**Comment by eliasjpr** [comment]
Closing this issue since this was address with #592
