### ISSUE TITLE
Field validators not working as expected

### ISSUE THREAD

**Issue by danielRomero** [amberframework/amber#688]
### Description

I think field validators in controllers doesn't work as expected.

I'm trying to understand how it works with a new fresh installation following the sample application described in the guides

https://amberframework.org/guides/getting-started/quickstart/zero-to-deploy.md#zero-to-deploy

### Steps to Reproduce

create sample application
`amber new test-amber -d pg -m granite -t ecr`

create scaffold
`amber g scaffold Pet name:string breed:string age:integer`

migrate database
`amber db create migrate`

----------------------------

**Case 1: Validation optional without block**

`optional(:age)`

Result: Not compile

Message:
`in src/controllers/pet_controller.cr:71: undefined method 'optional'`

**Ok**, the block is mandatory and must return Bool
https://github.com/amberframework/amber/blob/master/src/amber/validators/params.cr#L59

----------------------------

**Case 2: Validation optional returning true**

`optional(:age) { |f| true }`

- Field empty in form

Result: Resource not created

Flash message: `Could not create Pet!`

- Field filled  in form

Result: Resource created

Flash message: `Created Pet successfully.`

----------------------------

**Case 3: Validation optional returning false**

`optional(:age) { |f| false }`

- Field empty in form
Result: Resource not created

Application error
`ERROR: Validation failed. [Amber::Validators::Error(@param="age", @value="", @message="Field age is required")] (Amber::Exceptions::Validator::ValidationFailed)`

- Field filled  in form

Result: Resource not created

Application error
`ERROR: Validation failed. [Amber::Validators::Error(@param="age", @value="32", @message="Field age is required")] (Amber::Exceptions::Validator::ValidationFailed)`

----------------------------

**Expected behavior:** When an optional param is missing in the request, the resource must be saved

### Versions

```
Crystal 0.24.1 (2018-01-27)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
```

```
Amber CLI (amberframework.org) - v0.6.7
```

```
shards:
  amber:
    github: amberframework/amber
    version: 0.6.7
```

**Comment by faustinoaq** [comment]
@danielRomero Thank you for reporting this issue!

BTW, @eliasjpr Why params validators and granite validators looks so different? :sweat_smile:

**Comment by faustinoaq** [comment]
Related issue here: https://github.com/amberframework/amber/issues/698

**Comment by drujensen** [comment]
This has been fixed.  The block is now optional.
