### ISSUE TITLE
[Controller] Set custom status_code in respond_with

### ISSUE THREAD

**Issue by rdelandesen** [amberframework/amber#690]
### Description

By developing an API (for example), I am used to customizing the status code of the HTTP response.

**E.g.:**
- `201` for `create` action
- `400` for a call with missing or invalid parameters
- `403` if unauthorized etc.

It seems that it is not possible to customize the status code using `Amber::Controller::Helpers::Responders::Content # respond_with`

### Solution

Add a `status_code` attribute:

```
# /lib/amber/src/amber/controller/helpers/responders.cr

@status_code : Int32 = 200

def status_code(@status_code : Int32)
end

# respond_with
set_response(body: content.body, status_code: content.status_code, content_type: content.type)
```

Call:

```
respond_with do
  status_code 201
  json pet.to_json
end
```

What do you think about it?
(BTW, I take this opportunity to say congratulations for your work!)

**Comment by elorest** [comment]
@rdelandesen 

What do you think of this syntax?

```cr
respond_with(201) do
  json pet.to_json
end
```

It might also be good to make this method public.

https://github.com/amberframework/amber/blob/master/src/amber/controller/helpers/responders.cr#L89

Should be a pretty easy fix. Do you want to submit a PR for that or should I?
