### ISSUE TITLE
Shards installer error: Failed to clone https://github.com/amberframework/smtp.cr.git

### ISSUE THREAD

**Issue by lebogan** [amberframework/amber#712]
I am attempting to use the amber framework with crystal 0.24.2 on a Fedora 27 vm. The shards just wont install. It looks like there is some dependency on smtp.cr.git being in the amberframework repo.

Is this a bug or am I just not doing this right?

Thanks.

**Comment by elorest** [comment]
Could you walk us through producing this error?

**Comment by lebogan** [comment]
I commented out the quartz-mailer and the shards install succeeded.

My previous command and result:
```
[sample (master)]$ shards install
Fetching https://github.com/amberframework/amber.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/jeromegn/slang.git
Fetching https://github.com/stefanwille/crystal-redis.git
Fetching https://github.com/amberframework/cli.git
Fetching https://github.com/mosop/optarg.git
Fetching https://github.com/mosop/callback.git
Fetching https://github.com/mosop/string_inflection.git
Fetching https://github.com/amberframework/teeplate.git
Fetching https://github.com/juanedi/micrate.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/jwaldrip/shell-table.cr.git
Fetching https://github.com/askn/spinner.git
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-mysql.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/amberframework/granite-orm.git
Fetching https://github.com/amberframework/quartz-mailer.git
Fetching https://github.com/amberframework/smtp.cr.git
Username for 'https://github.com': lebogan
Password for 'https://lebogan@github.com': 
Failed to clone https://github.com/amberframework/smtp.cr.git
```

**Comment by lebogan** [comment]
quartz-mailer: removing the version reference to ~> 0.4.0 in shard.yml works. Or setting branch: master works.

**Comment by faustinoaq** [comment]
Thank you for open this issue.

Oh, This was a breaking change, we renewed our email shard, so the old email related shards were removed.

see: https://github.com/amberframework/amber/pull/604

> Should I close this issue?

Yes, I just created a label `kind:breaking-change`, so next release should document it better :wink:

**Comment by elorest** [comment]
Because of this breaking change we should definitely jump to 0.8.0 now lol.

**Comment by robacarp** [comment]
Yeah, I've hit this category of bug elsewhere when we deleted or renamed an old shard. I think it makes sense to deprecate old shards for a while before simply nuking them.
