### ISSUE TITLE
Indentation issues in amber generator

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#748]
### Description

I found some issues in generated code

1. `config/routes.cr`:

![screenshot_20180411_104313](https://user-images.githubusercontent.com/3067335/38627666-23b5f864-3d75-11e8-91f5-3c45e86f2d01.png)

2. 1. `src/models/**`:

![screenshot_20180411_104455](https://user-images.githubusercontent.com/3067335/38627771-6081dfa6-3d75-11e8-8ee1-2bf294867a5a.png)

3. `src/controllers/**`:

![screenshot_20180411_104540](https://user-images.githubusercontent.com/3067335/38627811-7b3ba412-3d75-11e8-900f-ceb4efc1d586.png)

![screenshot_20180411_104639](https://user-images.githubusercontent.com/3067335/38627885-9ee8d4ac-3d75-11e8-80f7-f0f422d472f1.png)

### Steps to Reproduce

1. Create a new amber project
2. Do some scaffolding
3. Use `crystal tool format --check`

**Expected behavior:** Generated files are formatted well

**Actual behavior:** Generated files aren't formatted well

**Reproduces how often:** 100%

### Versions

v0.7.2

### Additional Information

`crystal tool format --check` output

```
➜  forum crystal tool format --check
Error: formatting './config/routes.cr' produced changes
Error: formatting './config/application.cr' produced changes
Error: formatting './config/initializers/database.cr' produced changes
Error: formatting './src/controllers/session_controller.cr' produced changes
Error: formatting './src/controllers/user_controller.cr' produced changes
Error: formatting './src/controllers/home_controller.cr' produced changes
Error: formatting './src/controllers/application_controller.cr' produced changes
Error: formatting './src/pipes/authenticate.cr' produced changes
Error: formatting './src/models/user.cr' produced changes
Error: formatting './src/models/tasks.cr' produced changes
```

^ This doesn't check `.ecr` or `.slang` files, so we should be careful with the indentation on these files.

**Comment by faustinoaq** [comment]
@epergo Did your PR (https://github.com/amberframework/amber/pull/780) fix this? :sweat_smile:

**Comment by epergo** [comment]
Wops, I didn't see this issue. I only fixed `config/routes.cr` indentation.

**Comment by faustinoaq** [comment]
@epergo No problem, Thank you!
