### ISSUE TITLE
Add support for before and after hooks in amber generators

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#749]
### Description

This will allow us to run commands before and/or after generation of an artifact and they could be specified in a yaml file in the recipe

### Steps to Reproduce

Not applicable

### Versions

v0.7.2

### Additional Information

Also, this will allow us to run external tools to perform task like code formatting, installing new dependencies and so on.

**Comment by drujensen** [comment]
@damianham What about allowing for a list of recipes in priority order?
```
basic/granite
djensen/react
```
This would require searching for the template in `djensen/react` first and if not found, searching in `basic/granite`

This would allow you to override templates and/or add new templates without requiring you to copy everything from scratch.

**Comment by drujensen** [comment]
It would be nice to be able to fork a recipe and include it as a shard.  The  priority search order could be the shard priority order.

**Comment by drujensen** [comment]
@damianham Is there anyway we can avoid creating our own packaging manager?  `recipe.yml` is just a pre-cursor to another dependency management and version control.

**Comment by damianham** [comment]
I see it as just a way to specify some configuration items for the recipe, principally the parent recipe that the recipe extends.  I don't think we will have the ability to specify a version of the parent recipe that a recipe extends as the release version will apply to all recipes so therefore I don't foresee the ability to manage dependencies of a recipe.  There may be a recipes that add dependencies to the generated application's shards.  I think that would be performed by the after_app hook.
