### ISSUE TITLE
Usability issues with amber deploy

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#756]
### Description

`amber deploy` is a nice tool but the user experience can be improved:

1. Better error messages
2. Print debug info using `--debug` flag
3. Exiting if the command failed: the most important, because right now all the commands are executed until the end, no mater if authentication fails or repository is incorrect.

### Steps to Reproduce

Work in progress...

### Versions

Work in progress...

### Additional Information

Work in progress...

**Comment by eliasjpr** [comment]
Closing this issue since we will be removing amber deploy

**Comment by faustinoaq** [comment]
@eliasjpr `amber deploy` still requires to be removed, I'm already working on that :+1:

**Comment by eliasjpr** [comment]
Amber Deploy command was removed
