### ISSUE TITLE
render macro doesn't allow template to be a variable

### ISSUE THREAD

**Issue by robacarp** [amberframework/amber#762]
### Description
[Nested / namespaced controllers expect their views to be in a different place than I do](https://github.com/amberframework/amber/issues/763), but perhaps I'm doing it wrong. 

However, while working around that issue, I ran into this:

```crystal
class User::InvitesController < ApplicationController
  def local_render(template)
    render template, folder: "user/invites"
  end

  def edit
    local_render "edit.slang"
  end
end
```

```text
macro didn't expand to a valid program, it expanded to:

================================================================================
--------------------------------------------------------------------------------
   1.       
   2.         Kilt.render(""src/views/user/invites/#{template}"")
   3.       
   4.     
--------------------------------------------------------------------------------
Syntax error in expanded macro: render_template:2: expecting token ')', not 'src'

        Kilt.render(""src/views/user/invites/#{template}"")
```

**Expected behavior:**

It seems reasonable to allow a template to be specified as a variable and passed into the macro.

**Actual behavior:** 

Templates must be specified as string literals or the application won't compile.

**Comment by drujensen** [comment]
what happens if you remove the quotes?
```
render template, folder: user/invites
```

**Comment by elorest** [comment]
By very definition no macro can accept a variable....

**Comment by robacarp** [comment]
@elorest [I'm not sure what you mean](https://carc.in/#/r/3wbx), I pass variables to macros regularly

**Comment by elorest** [comment]
Do you have an example? How would you pass a runtime variable into a compile time macro?

**Comment by elorest** [comment]
@robacarp Your macro isn't doing anything with the variable. Just creating code that later calls it at runtime. 

This is different from render, which has to actually load the template at compile time and parse it into and html string builder for interpolation. 

See:

https://github.com/jeromegn/slang
https://github.com/crystal-lang/crystal/blob/80a975cf0a98a4ce8464d0069145131667becd70/src/ecr/macros.cr#L1

**Comment by robacarp** [comment]
Is this also different from my example above? It isn't doing anything with the variable either.

**Comment by faustinoaq** [comment]
@robacarp I notice it since I was working with Kemal, macros and `render` itself are a bit "special", you can use some variables (macro vars, constants,etc) only if they have a literal type inside and aren't dynamic, so you can try something like this:

```crystal
class User::InvitesController < ApplicationController
  macro local_render(template)
    render template, folder: "user/invites"
  end

  def edit
    local_render "edit.slang"
  end
end
```

**Comment by faustinoaq** [comment]
Well, If we want to use dynamic templates then liquid.cr is a nice option :wink:

**Comment by drujensen** [comment]
I don't this is something we can fix.  closing.
