### ISSUE TITLE
templates on nested/namespaced controllers are in an unexpected place

### ISSUE THREAD

**Issue by robacarp** [amberframework/amber#763]
Perhaps I'm missing the configuration Amber is opinionated about here, but this tripped me up.

### Description

I'm using a namespaced controller, `User::InvitesController` and it's stored in `controllers/user/invites_controller.cr`. I would think my views would be stored in `views/user/invites/<view>`.

Here is a simplified version of my file tree:

```text
▾ src/
  ▾ controllers/
    ▾ user/
        users_invites_controller.cr
      user_controller.cr
  ▾ views/
    ▾ user/
      ▾ invites/
          edit.slang
        edit.slang
        new.slang
```

The controller definition is:

```crystal
class User::InvitesController < ApplicationController
  def edit
    invite = Invite.new
    render "edit.slang"
  end
end
```

However, this code fails to compile with:

```text
    Slang template: src/views/user/users_invites/edit.slang doesn't exist. (Exception)
```

### Workaround

The current API provides a `folder` attribute for #render, and this works:

```crystal
    render "edit.slang", folder: "user/invites"
```

### Versions

Amber CLI (amberframework.org) - v0.7.2
Crystal 0.24.2 (2018-03-10)
LLVM: 5.0.1
Default target: x86_64-apple-macosx

**Comment by Adam-Stomski** [comment]
@robacarp i believe it takes path to the controller not the name so if you have `users_invites_controller.cr` it works like that
I've got
```ruby
module App
  class ProjectsController < ApplicationController
    def index
      render("index.ecr")
    end
   end
end
```
in `controlers/app/projects_contoller.cr` and view `views/app/projects/index.ecr` and it works.
I would never think this is a bug 😄

**Comment by elorest** [comment]
@robacarp the path for your controller from Rails conventions I built this off of should be `views/users/invites_controller.cr`. Because you have an extra user it looks for the path to views to be the same. Hope that helps.

**Comment by robacarp** [comment]
@elorest I think you meant `controllers/users/invites_controller.cr` and that makes sense, like what @Adam-Stomski said. thanks
