### ISSUE TITLE
[CLI] Amber Deploy AWS

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#767]
### Description

As a framework user I would like to deploy to AWS using the built in `amber deploy aws`

### Example

```bash
amber -d aws -id {aws_access_key_id} -key {aws_secret_access_key}
```

**Comment by faustinoaq** [comment]
Thank you for open this issue! :+1: 

In fact, the right command would be

```
# some other authentication steps are required before and during deployment
amber deploy --init --service aws # for first time
amber deploy --service aws # to push changes
```

A ssh url is provided as well, when deployment is finished

**Comment by faustinoaq** [comment]
@eliasjpr We still need the right documentation to deploy to AWS, maybe we can open an issue on docs repo, WDYT?
