### ISSUE TITLE
[CLI] Amber Deploy Azure

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#768]
### Description

As a framework user I would like to deploy to AZURE using the built in `amber deploy azure`

### Example

```bash
amber -d azure
```
See https://docs.docker.com/machine/drivers/azure/#authentication

**Comment by faustinoaq** [comment]
Thank you for open this issue! :+1: 

The right command would be

```
# some other authentication steps are required during deployment
amber deploy --init --service azure # for first time
amber deploy --service azure # to push changes
```

**Comment by faustinoaq** [comment]
@eliasjpr We still need the right documentation to deploy to Azure, maybe we can open an issue on docs repo, WDYT?
