### ISSUE TITLE
[CLI] Amber Deploy Google Compute Engine

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#769]
### Description

As a framework user I would like to deploy to Google Compute Engine using the built in `amber deploy azure`

### Example

```bash
amber -d gce
```
See https://docs.docker.com/machine/drivers/gce/

**Comment by faustinoaq** [comment]
@eliasjpr Thank you for open this issue! :+1: 

In fact, the right command would be

```
amber deploy --init --service google # for first time
amber deploy --service google # to push changes
```

**Comment by faustinoaq** [comment]
@eliasjpr We still need the right documentation to deploy to GCE, maybe we can open an issue on docs repo, WDYT?
