### ISSUE TITLE
New API generator

### ISSUE THREAD

**Issue by drujensen** [amberframework/amber#792]
### Description

The ability to generate an API scaffolding should be simple to add to an existing project.   

As @elorest mentioned, Amber is well suited to support both `api` and `web` in the same project using pipelines.  Also, my current project will require both.  I need an administrative backend and an API interface for external interaction.

Something like `amber g api post` or `amber g scaffold_api post` or both.

**Comment by drujensen** [comment]
This is related to #269

**Comment by eliasjpr** [comment]
Tracking issue #269
