### ISSUE TITLE
Amber new generates project with Granite::ORM

### ISSUE THREAD

**Issue by jaysneg** [amberframework/amber#793]
### Description

**Amber new** generates project with Granite::ORM

### Steps to Reproduce

1. Amber new APP_NAME

**Expected behavior:** it will use Granite 

**Actual behavior:** Granite::ORM

**Reproduces how often:** always

### Versions

~ $ amber --version
Amber CLI (amberframework.org) - v0.7.2

**Comment by faustinoaq** [comment]
This will be fixed on next version, see: #789

**Comment by elorest** [comment]
It still works with Granite::ORM doesn't it? So this isn't really a bug?

**Comment by jaysneg** [comment]
@elorest at docs examples Granite without ORM

**Comment by faustinoaq** [comment]
> at docs examples Granite without ORM

@jaysneg Yeah, The new Granite Docs doesn't have the `::ORM` part :sweat_smile: 

Although, you can still use it with current amber version `v0.7.2`, because is using an old granite version.

Next version will update that, please see #789
