### ISSUE TITLE
JSON parser request.body is sometimes null

### ISSUE THREAD

**Issue by fridgerator** [amberframework/amber#800]
### Description

Returning JSON from a controller action `{ok: "ok"}.to_json` throws an error [link](https://pastebin.com/ipdaMQcM).

Amber logs a `200` response, however the browser shows a `500` response.

In [`amber/router/parsers/json.cr`](https://github.com/amberframework/amber/blob/master/src/amber/router/parsers/json.cr#L5) my request body is nil, and this `.not_nil!` is causing the exception

### Steps to Reproduce

I tried to reproduce this with a fresh amber install using jquery `$.ajax` but couldnt.  However my project is using [vue-resource](https://github.com/pagekit/vue-resource) and it happens consistently.

@damianham Also mentioned in gitter this would occasionally happen to him while working on the react recipe

### Versions

* Amber - master branch [link](f6ea26f8d620c42dec33c81b77c90fc74cef5a36)
* Crystal - 0.24.2

**Comment by fridgerator** [comment]
I patched my local environment so I could continue to work, and used the 2nd option

**Comment by faustinoaq** [comment]
> I patched my local environment so I could continue to work, and used the 2nd option

Can u send a PR about this? :sweat_smile:

**Comment by c910335** [comment]
I think server should return 400 because the request header contains `Content-Type: application/json` and the request body is not a valid JSON, which is `nil`.

If your request body is empty, you should not set the `Content-Type` header.

**Comment by fridgerator** [comment]
@faustinoaq I can if its the right way to fix this.  I wasn't sure though.

@c910335 It is a `DELETE` request, and there is no body.  This seems to be the behavior of [vue-resource](https://github.com/pagekit/vue-resource).  The content type is set for all requests, not conditionally based on if there is a body or not.
