### ISSUE TITLE
Increase PageSpeed Insights results on amberframework.org

### ISSUE THREAD

**Issue by GuskiS** [amberframework/amber#801]
### Description

Amber main page has styles/javascript that are render blocking, see [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Famberframework.org%2F&tab=desktop)

### Steps to Reproduce

1. Visit [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Famberframework.org%2F&tab=desktop)
2. Check results

**Expected behavior:** Not to be render blocking

**Actual behavior:** Blocks render

**Reproduces how often:** Always

### Versions

Not sure which version website uses.

### Additional Information

This can be solved by adding `rel="preload"`, see [MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content)

Also, this can be set to fonts as well (they start to download only after CSS has been parsed), but then it requires a bit of changes, see [this video (from 22:30)](https://youtu.be/Mv-l3-tJgGk?t=22m30s).

It might be useful to have view helpers that would do this automatically, similar to what [rails have](https://apidock.com/rails/ActionView/Helpers/AssetTagHelper/stylesheet_link_tag). (this would be great if it would work with webpack [hashing feature](https://webpack.js.org/guides/caching/))

**Comment by dwightwatson** [comment]
![image](https://user-images.githubusercontent.com/1100408/49562498-ee547a80-f96f-11e8-936d-416d58ba3b5c.png)

It seems the site has a score of 100 now,  is there anything further to do?

**Comment by GuskiS** [comment]
Nice, but there still can be made improvements, see `Diagnostics`.
Also, mobile section is 90%
