### ISSUE TITLE
Page reloading on Firefox in development

### ISSUE THREAD

**Issue by idabmat** [amberframework/amber#802]
### Description

On Firefox (v60) I get the following warning in the console :

>The page was reloaded, because the character encoding declaration of the HTML document was not found when prescanning the first 1024 bytes of the file. The encoding declaration needs to be moved to be within the first 1024 bytes of the file.

### Steps to Reproduce

1. Create a new amber app with `amber new`
2. Start the app with `amber watch`
3. Open http://localhost:3000 with Firefox and console pane open

**Expected behavior:** The page should not have to be reloaded

**Actual behavior:** The page is reloaded

**Reproduces how often:** 100%

### Versions

- amber `v0.7.2`
- crystal `0.24.1`
- firefox `60.0.1`

### Additional Information

This seems to be caused by the `<script>` tag for live reload in development that gets inserted by Amber before the `<html>` tag.

**Comment by faustinoaq** [comment]
Hi @idabmat Thank you for report this issue! :+1: 

I already working on some refactoring for `amber watch`, see: #476 

Also I'm testing it with multiples browsers (Chrome, Fixefox, Edge, and others) :wink: 

This will be fixed before next release

**Comment by faustinoaq** [comment]
As workaround you can remove reload pipe `Amber::Pipe::Reload` in your `config/routes.cr` file

**Comment by drujensen** [comment]
This seems to be fixed.  I tested with FF 64.  We can reopen if this is still broken

**Comment by drujensen** [comment]
This is still an issue.  Reopening.

**Comment by drujensen** [comment]
Actually, I am going to create a new issue. It's behavior is slightly different than this.
