### ISSUE TITLE
params parser error

### ISSUE THREAD

**Issue by jaysneg** [amberframework/amber#805]
### Description

params did not parse multi query params

?brand[]=adidas&brand[]=dc

### Steps to Reproduce

create form 
with elements

input name="brand[]" type="checkbox" value="1"
input name="brand[]" type="checkbox" value="2"

**Expected behavior:** params[:brand] will be array 

**Actual behavior:** params[:brand] did not exist. params["brand[]"] present 

**Reproduces how often:** always

### Versions

0.7.2

**Comment by jaysneg** [comment]
request.query_params

it returns HTTP::Params(@raw_params={"brand[]" => ["2xist", "2xu", "31-phillip-lim"]})

**Comment by jaysneg** [comment]
How to get {"brand[]" => ["2xist", "2xu", "31-phillip-lim"]} ?

**Comment by faustinoaq** [comment]
```
request.query_params.to_h # => {"brand[]" => ["2xist", "2xu", "31-phillip-lim"]}
```

BTW, Can you ask this again on [StackOverflow](https://stackoverflow.com/questions/tagged/amber-framework) ? I think this would be useful for Amber Community :wink: 

If so, please use the tags `crystal-lang` and `amber-framework` :+1:

**Comment by jaysneg** [comment]
@faustinoaq 

```
request.query_params.to_h # => {"brand[]" => "2xist"}
```

this method did not work correctly

**Comment by jaysneg** [comment]
@faustinoaq i can ask it at  StackOverflow but does it make sense if it bug?

**Comment by faustinoaq** [comment]
> i can ask it at StackOverflow but does it make sense if it bug?

I don't think this is a bug, but just design decisions, /cc @eliasjpr

**Comment by jaysneg** [comment]
@faustnoaq if it’s feature it better add to docs.
I spand time to understend how to get hash of arrays of params it is not obviouse that you need use ‘request.raw_params.fetch_all(“brand[]”)’ to get {“brand[]” => [“brand1”, “brand2”, ....]}

**Comment by faustinoaq** [comment]
@jaysneg Yeah, I think we can add more documentation on [Request & Response](https://amberframework.gitbook.io/amber/guides/controllers/request-and-response-objects) section :sweat_smile: 

![screenshot_20180521_065134](https://user-images.githubusercontent.com/3067335/40306198-680140e2-5cc3-11e8-9d04-c9cf80d8865a.png)

We have an **Edit on Github** button now, so feel free to contribute opening more issues and even PRs :wink:

**Comment by jaysneg** [comment]
cool
