### ISSUE TITLE
Error: amberframework installation fails under crystal installed with asdf-crystal 

### ISSUE THREAD

**Issue by zenny** [amberframework/amber#807]
Hi,

With crystal installed with asdf-crystal (https://github.com/marciogm/asdf-crystal) plugin, amber fails to build at 'shards install':

```
Dependencies are satisfied
Building: ameba
Error target ameba failed to compile:
/usr/bin/ld: cannot find -levent
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/DATA/zenny/Downloads/gitrepos/crystal-projects/amber-stable/lib/ameba/bin/ameba'  -rdynamic  -lyaml -lpcre -lm -lgc -lpthread /home/zenny/.asdf/installs/crystal/0.24.2/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`

Makefile:7: recipe for target 'build' failed
make: *** [build] Error 1
```
Even created a request to asdf-crystal developer to create a similar plugin at https://github.com/marciogm/asdf-crystal/issues/13.

Cheers,
/z

**Comment by faustinoaq** [comment]
Hi @zenny 

Try `shards install --production` and `shards build -v`

Then copy `bin/amber` to your `/usr/local/bin` path

**Comment by robacarp** [comment]
I would guess this is a problem with the crystal asdf plugin. The error is here:

`/usr/bin/ld: cannot find -levent` which is a problem with how the Crystal dependency on libevent is specified.
