### ISSUE TITLE
Generate specs for Crecto

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#817]
### Description

Currently `amber new app -m crecto` doesn't generate specs

You can see there isn't spec folder on https://github.com/amberframework/amber/tree/master/src/amber/cli/templates/model/crecto/src/models 

### Steps to Reproduce

1. `amber new app -m crecto`
2. `crystal spec`

**Expected behavior:** Execute controllers and models specs based on crecto

**Actual behavior:** Error fixed by #816 but still no specs

**Reproduces how often:** 100%

### Versions

amber master (https://github.com/amberframework/amber/commit/bf55c441f862ba0603b4a4a9023d3e8421e35358)

### Additional Information

@damianham already added this missing specs to basic crecto recipe, see: https://github.com/amberframework/recipes/tree/master/basic/crecto/model/spec/models (it has some bugs, I already working on some fixes :wink: )

**Comment by eliasjpr** [comment]
Fixed #837
