### ISSUE TITLE
Move src/locales to config/locales like Rails

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#819]
### Description

Currently locales are on `src/locales` would nice to follow Rails convention here and move this folder to `config/locales`

### Steps to Reproduce

Not applicable

### Versions

Amber master (https://github.com/amberframework/amber/commit/975dc592b9fd40f94d6cff1c5d34512283d01fd0)

### Additional Information

Related comment here: https://github.com/amberframework/amber/pull/814#issuecomment-392279084 

/cc @eliasjpr @docelic

**Comment by eliasjpr** [comment]
I don't see the added benefit, besides 3 rails conventions. I can swing either way with this.

**Comment by conradwt** [comment]
@faustinoaq Is it also make a good idea to move the src/${project-name}.cr to the root of the project folder and rename to `config.cr`?  Then all the application specific files would be in the `src` directory and all the `Amber` specific files will be in the `config` directory.  In general, if `Amber` wants to standardize its layout based on Rails, this would definitely be a good time to do it prior to 1.0.

**Comment by faustinoaq** [comment]
@conradwt Well, the main file inside `src/` folder is a crystal idea, by example, if you try to create an amber project from scratch without amber cli (1) you can use `crystal init app myapp` and a "main" file is automatically generated on `src/` folder and added to `shard.yml` target, so you can do `shards build myapp` to compile your project.

(1) https://docs.amberframework.org/amber/cookbook/from-scratch

**Comment by eliasjpr** [comment]
@conradwt the `src/{project_name}.cr` is a crystal convention that we are supporting. As per the `src/locales` I understand that people are used to Rails convention but I don't the value that it brings by moving it outside, to me it does not make much difference and it works, for that reason I think this is not an **issue**.

**Comment by eliasjpr** [comment]
@faustinoaq can you provide the added benefits of moving this to config/locales to the description of this issue so we can weight on if this is truly worth while. 

One added benefit I see is:
- It seems that it would be easier to load translations from the config direction than from the source directory

**Comment by faustinoaq** [comment]
> can you provide the added benefits of moving this to config/locales to the description of this issue so we can weight on if this is truly worth while.

I just realize this issue is not that important. I mean, `src/locales` is ok :sweat_smile: 

> It seems that it would be easier to load translations from the config direction than from the source directory

Well, I think is the same, also any dev can setup the locales folder by modifying `settings.load_path += ["./src/locales"]` on `config/initializers/i18n.cr`

This is just an structure suggestion, maybe we should keep the current setup, WDYT?

>> It was originally @eliasjpr's suggestion that we put it in src/locale. 

BTW, also seems you suggested the `src/locales` folder :wink: 

Ref: https://github.com/amberframework/amber/pull/814#issuecomment-392279691

**Comment by conradwt** [comment]
@faustinoaq Coming from Rails 5.2, I would recommend that every folder within `src` should be loaded by default because it would be odd and this functionality would have to be documented in `Amber` docs.  Then developers will try to work around this by adding unrelated sources to auto-loaded  folders (i.e. models, controller, or others) to reduce the maintinenance.  One solution requires two edits versus one.  Just something to consider as one works out the design.

Which brings up an new question? Is it possible to create umbrella like applications similar to Phoenix/Elixir?  For example, I would ideally would like to structure my applications as follows:

In Elixir, one would use the following structure:

https://elixirschool.com/en/lessons/advanced/umbrella-projects

In Rails, one can do the Rails Engines bit but I prefer the Elixir approach here where everything for that application resides under the specific app's folder.  Just thinking out loud here.

**Comment by faustinoaq** [comment]
@conradwt Yeah I have also seen that on Django (apps), I think Amber doesn't support unbrella projects yet :sweat_smile:

**Comment by eliasjpr** [comment]
@conradwt I believe the `src/locales` gets loaded by default since is required by the `src/{app}.cr` file, I haven't confirm but I almost certain. 

Also im :100: with you about the apps being all self-contained in the `src` directory. We have an open issue about how to support modular apps #277

**Comment by faustinoaq** [comment]
> We have an open issue about how to support modular apps #277 feel free to contribute to any ideas you have.

@eliasjpr Maybe we can follow @damianham approach on this, WDYT?, see: [Modular recipe](https://github.com/amberframework/recipes/tree/master/misc#modular) (BTW, I don't think we should use a recipe, but consider a modular structure like this)

See: [Why we should use external repos, instead of a monolithic repository](https://github.com/amberframework/amber/issues/899#issuecomment-401548851)

**Comment by eliasjpr** [comment]
> @eliasjpr Maybe we can follow @damianham approach on this, WDYT?, see: Modular recipe (BTW, I don't think we should use a recipe, but consider a modular structure like this)

This is out of scope. Amber strictly follow MVC the way rails does it if someone would like to structure their apps like the modular example you presented that is fine, but it is not part of the conventions Amber has set for the apps. 

On another note, I do believe we should add support for a modular approach to mount another app like plugins. For now, I think this is not a big issue having the locales in the src directory.

**Comment by eliasjpr** [comment]
Maybe this can be closed?
