### ISSUE TITLE
Parsing Error: The -m option must be one of granite, crecto.

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#827]
### Description

I'm trying to implement Jennifer Recipe, I got this error when I tried to execute:

```
amber new app -d sqlite -t slang -m jennifer
Parsing Error: The -m option must be one of granite, crecto.

amber new OPTIONS NAME

Generates a new Amber project

Arguments:
  NAME  name of project

Options:
  -d          database
              one of:
                pg
                mysql
                sqlite
              (default: pg)
  --deps      installs deps, (shards update)
  -m          model type
              one of:
                granite
                crecto
              (default: granite)
  --no-color  Disable colored output
  -r          recipe
  -t          template language
              one of:
                slang
                ecr
              (default: slang)
  -h, --help  show this help
```

Would be nice to print just a warning and use the given model even if this doesn't exist, this can be very useful to support new models/ORMs with recipes.

### Steps to Reproduce

1. `amber new app -d sqlite -t slang -m jennifer`

**Expected behavior:** Print a warning and generate files

**Actual behavior:** Exit and doesn't generate the project at all

**Reproduces how often:** 100%

### Versions

Amber master (https://github.com/amberframework/amber/commit/764c7b87e60bbcaba9dba4814bbb110a138521e9)

### Additional Information

Related PRs: #766 https://github.com/amberframework/recipes/pull/20

**Comment by drujensen** [comment]
@faustinoaq I don't understand your expected behavior.  If we don't support `-m jennifer`, why would it continue generating the app?  This would be considered an invalid option, correct? Why would it continue generating code?

It seems like the current behavior is the expected behavior.  What am I missing?

**Comment by imdrasil** [comment]
@faustinoaq I'm not sure if this is a good idea. I believe in future there will be recipes which provide only part of functionality (instead of full application setup) and then an opportunity to specify model will be necessary.
