### ISSUE TITLE
Calling "g scaffold" multiple times on the same model adds multiple items to views/layouts/_nav

### ISSUE THREAD

**Issue by redcodefinal** [amberframework/amber#831]
### Description
Calling `amber g scaffold` on the same model multiple times will add mutliple menu items to `views/layouts/_nav` 

### Steps to Reproduce

1. Make a new amber project, set up db, etc.
2. `amber g scaffold ImAModel name:string`
3. `amber g scaffold ImAModel name:string`
4. `amber watch`
5. Visit `127.0.0.1:3000`
6. Should be multiple of the same menu item in the header menu.

**Expected behavior:** Not to make multiple nav items for the same item

**Actual behavior:** Makes multiple nav items for the same item

**Reproduces how often:** 100%

### Versions

Amber CLI (amberframework.org) - v0.7.2

### Additional Information

Nope

**Comment by eliasjpr** [comment]
Thanks for reporting this issue. It is a known issue and it would be great if someone can dedicate some time to prevent this from happening. Would you like to take on this task @redcodefinal?

**Comment by pynixwang** [comment]
@eliasjpr do  not add to _nav will prevent this happening.

this feature is almost useless.

**Comment by drujensen** [comment]
#1018 enables interactive mode so it will warn you if you try to run the same generator twice.  Adding a new resource to the navigation isn't useless.  If you don't like the current generators, you can always create your own recipes.
