### ISSUE TITLE
Wrong link on amber new --help

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#833]
### Description

`amber new --help` outputs:

```
...
 -h, --help  Show this help
 -r          Use a named recipe.  See documentation at https://amberframework.org.
...
```

https://amberframework.org is not a direct link to recipe documentation, we should use https://amberframework.gitbook.io/amber/cli/recipes instead.

### Steps to Reproduce

1. `amber new --help`

**Expected behavior:** See direct link to recipe docs

**Actual behavior:** See amber main website link on recipe flag help

**Reproduces how often:** 100%

### Versions

Amber master (https://github.com/amberframework/amber/commit/21afa103b85cefcda1f983fc7aa479b5ede3a801)

### Additional Information

Commented on https://github.com/amberframework/docs/pull/84

**Comment by eliasjpr** [comment]
Fixed #836
