### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#835]
### Description

Crystal has a pretty nice [CHANGELOG.md](https://github.com/crystal-lang/crystal/blob/master/CHANGELOG.md), would be nice to create one for amber from version 0.1.0 to 0.8.0:sweat_smile: 

### Steps to Reproduce

Not applicable

### Versions

Not applicable

### Additional Information

Not applicable

**Comment by eliasjpr** [comment]
Fixed with https://github.com/amberframework/amber/releases/tag/v0.8.0
