### ISSUE TITLE
Split TFB tests and add more use-cases

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#840]
### Description

Hi amber community!

Recently I have been reviewing latest TFB tests (https://tfb-status.techempower.com) and I notice all fastest frameworks (JVM and .NET ones) have many individual tests and use-cases, so they have more possibility to be in top ten.

What I propose is:

1. Add individual tests for json and plaintext like `amber-plaintext` and `amber-json` (no DB here)
2. Add individual test for all DB stuff using Postgres and MySQL like `amber-pg` and `amber-mysql`
3. Add an extra test for crecto model like:: `amber-crecto-pg`, `amber-crecto-mysql`

WDYT?

### Steps to Reproduce

Not applicable

### Versions

Not applicable

### Additional Information

Not applicable

**Comment by drujensen** [comment]
@faustinoaq I hate that about the techempower benchmarks because it makes it difficult to see the real results of each framework.  I don't want to contribute to the noise in their benchmark.
