### ISSUE TITLE
@wait_for command on docker-compose.yml doesn't work

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#841]
### Description

We're using `@wait_for` to wait for database on `docker-compose.yml`, although, this command doesn't work as expected.

https://github.com/amberframework/amber/blob/ce6dec47a0e3c8fe6863a10819d0591700dd4813/src/amber/cli/templates/app/docker-compose.yml.ecr#L2-L6

I'm getting this error with a working database on port `5432`

```
nc: getaddrinfo for host "db" port 5432: Name or service not know
```

I guess checking database port  is not very reliable nor standard, I propose to use something like `pg_isready`:

```
➜  ~ pg_isready
/run/postgresql:5432 - accepting connections
```

I don't know a similar command on MySQL, though :sweat_smile: 

### Steps to Reproduce

1. Setup your database (postgres)
2. Test `@wait_for` comand in your docker machine

**Expected behavior:** Return 0 status code

**Actual behavior:** Returns non-zero status code because `nc` can't detect pg port

**Reproduces how often:** 100%

### Versions

Amber master (https://github.com/amberframework/amber/commit/ce6dec47a0e3c8fe6863a10819d0591700dd4813)

### Additional Information

```
sh-4.4$ systemctl status postgresql
● postgresql.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-06-08 05:48:43 EST; 2 days ago
  Process: 6930 ExecStartPre=/usr/bin/postgresql-check-db-dir ${PGROOT}/data (code=exited, status=0/SUCCESS)
 Main PID: 6932 (postgres)
    Tasks: 7 (limit: 4915)
   Memory: 21.2M
   CGroup: /system.slice/postgresql.service
           ├─6932 /usr/bin/postgres -D /var/lib/postgres/data
           ├─6934 postgres: checkpointer process   
           ├─6935 postgres: writer process   
           ├─6936 postgres: wal writer process   
           ├─6937 postgres: autovacuum launcher process   
           ├─6938 postgres: stats collector process   
           └─6939 postgres: bgworker: logical replication launcher   

Jun 08 05:48:43 pc systemd[1]: Starting PostgreSQL database server...
Jun 08 05:48:43 pc postgres[6932]: 2018-06-08 05:48:43.917 EST [6932] LOG:  listening on IPv6 address "::1", port 5432
Jun 08 05:48:43 pc postgres[6932]: 2018-06-08 05:48:43.917 EST [6932] LOG:  listening on IPv4 address "127.0.0.1", port 5432
Jun 08 05:48:43 pc postgres[6932]: 2018-06-08 05:48:43.920 EST [6932] LOG:  listening on Unix socket "/run/postgresql/.s.PGSQL.5432"
Jun 08 05:48:43 pc postgres[6932]: 2018-06-08 05:48:43.957 EST [6933] LOG:  database system was shut down at 2018-06-03 13:37:47 EST
Jun 08 05:48:43 pc postgres[6932]: 2018-06-08 05:48:43.986 EST [6932] LOG:  database system is ready to accept connections
Jun 08 05:48:43 pc systemd[1]: Started PostgreSQL database server.
sh-4.4$ 
sh-4.4$ nc -q 1 db 5432
nc: getaddrinfo for host "db" port 5432: Name or service not known
```

**Comment by robacarp** [comment]
I'd recommend using something like [wait-for-it.sh](https://github.com/vishnubob/wait-for-it)

**Comment by drujensen** [comment]
@robacarp `wait-for-it.sh` uses netcat under the covers.  https://github.com/vishnubob/wait-for-it/blob/master/wait-for-it.sh#L36   I haven't had an issue with using netcat to look for the port to be available.

@faustinoaq I think maybe your test is not running in the docker container so you don't have a reference to the hostname `db`?  Can you provide more details?

**Comment by drujensen** [comment]
Closing this issue
