### ISSUE TITLE
Add more Frameworks to Benchmarks

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#842]
### Description

Is a bit unfair to have Hanami with 0RPS in latest TFB Round 16: (default test: Fortunes)

![screenshot_20180610_070847](https://user-images.githubusercontent.com/3067335/41201416-1ff09da6-6c7d-11e8-8821-778c37764a90.png)

I'd suggest to remove Hanami temporally and add more Ruby-like/Nice-designed frameworks to Benchmark section on README page. 

![screenshot_20180610_070757](https://user-images.githubusercontent.com/3067335/41201407-01de296e-6c7d-11e8-8cce-e7f040119f35.png)

### Steps to Reproduce

Not applicable

### Versions

Not applicable

### Additional Information

Some new frameworks could be:

- Django (python)
- Flask (python)
- Sinatra (ruby)
- Phalcom (PHP)
- Laravel (PHP)
- Symphony (PHP)
- Express (Node)

@amberframework/contributors WDYT?

**Comment by faustinoaq** [comment]
Link here: https://www.techempower.com/benchmarks/#section=data-r16&hw=ph&test=fortune&f=hq0ycn-yy9kvz-zih7gf-zik0un-m6h1j3-xan9xb-yelnge-2c9vh

**Comment by waghanza** [comment]
@faustinoaq is it not more `accurate` to compare `amber` to other `crystal` **frameworks**, or even `go` / `rust` ones ?

**Comment by eliasjpr** [comment]
I think this should include compile languages GO, JAVA, SCALA, KOTLIN, it very unfair to only include dynamic, interpreted languages
