### ISSUE TITLE
Incompatible with Crystal 0.25.0

### ISSUE THREAD

**Issue by lucifer1004** [amberframework/amber#847]
### Submitting questions

Current Amber seems to be incompatible with the newly released crystal 0.25.0

### Description

After installing crystal 0.25.0 on MacOS X 10.13.5, the amber project which ran successfully with crystal 0.24.2_1 failed to start.

### Steps to Reproduce

1. create a new project following the [https://docs.amberframework.org/amber/getting-started/quick-start](Quick-Start guide)
2. run `amber watch`

**Expected behavior:** [What you expect to happen]

The application server should start.

**Actual behavior:** [What actually happens]

02:01:09 Watcher    | (INFO) Watching 17 files (server reload)...
02:01:09 Watcher    | (INFO) Building project Todo...

```sh
Error in src/todo.cr:1: while requiring "../config/*"

require "../config/*"
^

in config/application.cr:1: while requiring "./initializers/**"

require "./initializers/**"
^

in config/initializers/database.cr:1: while requiring "granite_orm/adapter/pg"

require "granite_orm/adapter/pg"
^

in lib/granite_orm/src/adapter/pg.cr:1: while requiring "./base"

require "./base"
^

in lib/granite_orm/src/adapter/base.cr:1: while requiring "../granite_orm"

require "../granite_orm"
^

in lib/granite_orm/src/granite_orm.cr:3: while requiring "./granite_orm/base"

require "./granite_orm/base"
^

in lib/granite_orm/src/granite_orm/base.cr:3: while requiring "./fields"

require "./fields"
^

in lib/granite_orm/src/granite_orm/fields.cr:4: undefined constant JSON::Type

  alias Type = JSON::Type | DB::Any
               ^~~~~~~~~~

02:01:10 Watcher    | (INFO) Compile time errors detected. Shutting down...

```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Versions

You can get this information from copy and pasting the output of `amber --version` and `crystal --version` from the command line. Also, please include the OS and what version of the OS you're running.

MacOS X: 10.13.5
crystal: 0.25.0
amber: 0.7.2

### Additional Information

I've tried to replace `JSON::TYPE` with `JSON::ANY` in both `lib/granite_orm/src/granite_orm/fields.cr` and `lib/pg/src/pg/decoder.cr`, but after doing that, there was still error with `lib/i18n/src/i18n/backend/yaml.cr` which I was unable to figure out.

**Comment by robacarp** [comment]
Thanks for the bug. We are tracking this in #826
