### ISSUE TITLE
[Shard] Update Teeplate Shard to 0.6.1

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#853]
### Description

Teeplate shard is out of date current shard version is v0.5.0. Crystal 0.25.0 has change the `File` api and drop support the `stat` method and replaced with `info`

Amber spec are currently are failing because of this
`lib/teeplate/src/lib/file_tree/macros/directory.cr:33: undefined method 'stat' for File:Class`

**Comment by faustinoaq** [comment]
Fixed on #826

**Comment by eliasjpr** [comment]
Closing this in favor of #826 and #857
