### ISSUE TITLE
Unexpected behavior on Cluster mode

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#858]
### Description

If I run an amber app with `process_count: 2` I get 3 processes. This is unexpected :sweat_smile: 

### Steps to Reproduce

1. Run an amber app with `process_count: 2` in background (ex: using a service)
2. use `ps aux` to see how many app processes are forked

**Expected behavior:** 2 processes are forked

**Actual behavior:** 3 processes are forked

**Reproduces how often:** 100%

### Versions

amber v0.7.2

### Additional Information

![screenshot_20180616_112114](https://user-images.githubusercontent.com/3067335/41500464-627fc85c-7157-11e8-9ee1-28611b1bca27.png)

**Comment by zhangkaizhao** [comment]
Hi. I run into a similar issue and had to use a temporary solution.
Here is my pull request for the [Which is the fastest?](https://github.com/the-benchmarker/web-frameworks) project: [[Crystal] Temporarily fix multi-processing mode of Amber server #1392](https://github.com/the-benchmarker/web-frameworks/pull/1392) just now.

**Comment by eliasjpr** [comment]
We can now compile amber using the `-Dpreview_mt` flag to enable multi thread. I have tested this and it works. 

### See issue #1148

**Comment by codered** [comment]
Since there has been no feedback on this issue in several years and a workaround has been provided, we can safely close it. The child issue has been resolved as well.
