### ISSUE TITLE
How can i upload file?

### ISSUE THREAD

**Issue by set** [amberframework/amber#873]
How can I upload an image or file in Amber?

**Comment by faustinoaq** [comment]
> How can I upload an image or file in Amber?

This question has been asked multiples times recently, so  I just created a basic cookbook, please see: 

https://docs.amberframework.org/amber/cookbook/file-upload

PS: Please use stackoverflow to ask questions about `amber-framework`, see: 

https://stackoverflow.com/questions/tagged/amber-framework
