### ISSUE TITLE
[Proposal][CLI] Use complete database name for PostgreSQL

### ISSUE THREAD

**Issue by conradwt** [amberframework/amber#875]
I would like to recommend using complete database name when specifying the PostgreSQL database option:

replace 

```
  -d, --database  # Preconfigure for selected database. Options: pg | mysql | sqlite
                  (default: pg)
```

with

```
  -d, --database  # Preconfigure for selected database. Options: postgresql | mysql | sqlite
                  (default: postgresql)
```

**Comment by drujensen** [comment]
@conradwt maybe we can support both?  alias the `postgresql` to `pg` or vise versa.

**Comment by conradwt** [comment]
@drujensen The reason why I mentioned this was because `pg` refers to `Proctor & Gamble` and their site is `us.pg.com`.  The site for `PostgreSQL` is `https://www.postgresql.org`.

**Comment by drujensen** [comment]
@conradwt The driver we are using is called pg (`require "pg"`)so I think its appropriate to keep this consistent.  If someone creates a different `postgresql` driver, we can consider using its name instead.
