### ISSUE TITLE
Generate Amber executables using CI

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/amber#877]
### Description

Currently we need to compile amber from source, would be nice to generate executables and include them on release page. (idea suggested by @conradwt)

### Steps to Reproduce

Not applicable

### Versions

Amber v0.7.2

### Additional Information

We can use something like Crystal (1) or Scry (2)

1. https://github.com/crystal-lang/crystal/releases
2. https://github.com/crystal-lang-tools/scry/releases

**Comment by conradwt** [comment]
@faustinoaq I was thinking that `master` branch would serve as the `main` line for the project aka the-source-of-truth.  Next, developers would always submit PR with associated tests in which the CI would process.  If everything builds successfully and all tests pass, the PR goes green and a manager can review, tag, and merge into `master` which CI generates an executable binary under the releases’ section.  This follows the approach outlined in detailed for Travis here:

https://github.com/SAPDocuments/Tutorials/blob/master/tutorials/ci-best-practices-ci-cd/ci-best-practices-ci-cd.md

**Comment by faustinoaq** [comment]
@conradwt Interesting reference, maybe we should review some things on our release process,

By @elorest here: https://github.com/amberframework/amber/issues/759#issuecomment-381851226

---------------

My release process which is mostly scripted goes as follows.

1. Create release branch.
2. run `crelease 0.x.x` which does the following (https://github.com/elorest/CRelease)
  a. updates versions in shard.yml and src/version.cr
  b. changes template shard.yml.ecr to point to version instead of master.
  c. creates and pushes tags.
  d. pushes released code to stable.
  e. changes template shard.yml.ecr to point to master again.
3. merge back into master without squashing the 2 commits.

-------------

**Comment by drujensen** [comment]
Building amber for all different target platforms would be needed.  Closing this.  Let me know if you think this is still a needed feature and we can re-open it.
