### ISSUE TITLE
Consistent code style for amber scaffolds

### ISSUE THREAD

**Issue by shobhitic** [amberframework/amber#892]
### Description

I have generated multiple scaffolds and the one thing that I always change is the way methods are being called. Specifically `render` and `redirect_to`.

Everywhere, `render` is called using paranthesis :-

```
render("new.ecr")
```
But `redirect_to` is called without using paranthesis :-

```
redirect_to "/articles"
```
I've hunted down the issue and would like to fix it to use a consistent style.

Which is the preferred style for Amber?

### Steps to Reproduce

Simply create a scaffold.

```
$ amber g scaffold articles title:string body:text
```

**Expected behavior:** 

Consistent code style for method calls.

**Actual behavior:** 

Mixed style. `render` uses parenthesis and `redirect_to` does not.

**Reproduces how often:** Always.

### Versions

Amber CLI (amberframework.org) - v0.8.0

Crystal 0.25.0 (2018-06-20)

LLVM: 5.0.1
Default target: x86_64-apple-macosx

**Comment by eliasjpr** [comment]
Thank you for pointing this out. You can proceed without paréntesis I think that’s the preferred way for the project.

**Comment by faustinoaq** [comment]
Yeah, I think we don't have a code guide about calling methods/macros with/without parens

BTW, I found this about ruby: https://github.com/rubocop-hq/ruby-style-guide#method-invocation-parens

`render` without parens is ok :+1:

**Comment by shobhitic** [comment]
Without parenthesis it is then.

**Comment by shobhitic** [comment]
Created a PR for scaffolds. I've actually found this at many other places in templates. Will keep sending PRs as I fix them.
