### ISSUE TITLE
respond_with json method doesn't work

### ISSUE THREAD

**Issue by shobhitic** [amberframework/amber#895]
### Description

I was trying to send a JSON response from controller, and so I used `respond_with` method and `json` method in the block. Compiler threw an undefined method error which looked like this :-

```
in src/controllers/app_controller.cr:18: undefined method 'json'

      respond_with { json "{}" }
```

This is actually the documented usage as well, so I am not sure what could have been different about my code.

### Steps to Reproduce

1. Create an application and a controller where in a get request you respond with JSON using the method `respond_with { json "{}" }`.
2. Try to compile/run the application with `amber w`.
3. You'll be greeted with this error.

**Expected behavior:** It should compile and return the string as a response.

**Actual behavior:** Doesn't compile.

**Reproduces how often:** Always when I've tried it.

### Versions

Amber CLI (amberframework.org) - v0.8.0

Crystal 0.25.0 (2018-06-20)

LLVM: 5.0.1
Default target: x86_64-apple-macosx

### Additional Information

According to our gitter chat -

@faustinoaq thinks that "new proc type in `respond_with` helpers just broke something"

**Comment by eliasjpr** [comment]
This seems to be intentional as the `"{}"` is a string see https://github.com/amberframework/amber/blob/master/src/amber/controller/helpers/responders.cr#L38 you might want to pass an empty Hash or Array.

**Comment by faustinoaq** [comment]
@eliasjpr I think we can use method overloading instead of union types.

Something like this:

```cr
def json(json : String)
  # ...
end

def json(json : ProcType)
  # ...
end

def json(json : Hash(Symbol | String, String))
  # ...
end
``` 

WDYT?

**Comment by shobhitic** [comment]
My bad. I guess I can simply `JSON.parse(json_host.data)` here.

**Comment by eliasjpr** [comment]
@shobhitic you must do `JSON.parse("{}")` and it should work see https://play.crystal-lang.org/#/r/4eh5

**Comment by shobhitic** [comment]
@eliasjpr Yes, I had done that, but it didn't compile without the `.to_json` method call.

**Comment by drujensen** [comment]
Fix merged.  closing.

**Comment by elorest** [comment]
Tested original question above and it works.
