### ISSUE TITLE
[Proposal] Add Code of Conduct

### ISSUE THREAD

**Issue by conradwt** [amberframework/amber#896]
## Proposal

Please add link on the `README.md` to the `Code of Conduct` which applies to `amber` repository and all of its subprojects' repositories (i.e. amberframework author).

## Examples

- [Rails](https://rubyonrails.org/conduct/)

- [Golang](https://golang.org/conduct)

**Comment by faustinoaq** [comment]
@conradwt We already have a Code of Conduct, see:

> We have adopted the Contributor Covenant to be our CODE OF CONDUCT for Amber.

Ref: https://github.com/amberframework/amber#community

Also here: https://docs.amberframework.org/amber/code-of-conduct

**Comment by conradwt** [comment]
@faustinoaq Missed it as I was looking towards the bottom the page.  Closing this issue.
