### ISSUE TITLE
OpenSSL Issue Prevents 0.8.0 Build On Ubuntu - Following Amber Quick Start Guide  

### ISSUE THREAD

**Issue by lbmaxwell** [amberframework/amber#904]
### Description
Unable to build amber, apparently due to some issue with openssl1.1.0.

### Steps to Reproduce

bmaxwell@ubuntu01:~/Downloads$ date
Fri Jun 29 22:05:42 EDT 2018
bmaxwell@ubuntu01:~/Downloads$ crystal -v
Crystal 0.25.1 [b782738ff] (2018-06-27)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
bmaxwell@ubuntu01:~/Downloads$ uname -a
Linux ubuntu01 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
bmaxwell@ubuntu01:~/Downloads$ sudo apt-get install build-essential libreadline-dev libsqlite3-dev libpq-dev libmysqlclient-dev libssl-dev libyaml-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
libreadline-dev is already the newest version (7.0-3).
libsqlite3-dev is already the newest version (3.22.0-1).
libyaml-dev is already the newest version (0.1.7-2ubuntu3).
libmysqlclient-dev is already the newest version (5.7.22-0ubuntu18.04.1).
libpq-dev is already the newest version (10.4-0ubuntu0.18.04).
libssl-dev is already the newest version (1.1.0g-2ubuntu4.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
bmaxwell@ubuntu01:~/Downloads$ curl -L https://github.com/amberframework/amber/archive/stable.tar.gz | tar xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   128    0   128    0     0    780      0 --:--:-- --:--:-- --:--:--   775
100  173k  100  173k    0     0   496k      0 --:--:-- --:--:-- --:--:--  496k
bmaxwell@ubuntu01:~/Downloads$ cd amber-stable/  
bmaxwell@ubuntu01:~/Downloads/amber-stable$ shards install
Fetching https://github.com/amberframework/amber-router.git
Fetching https://github.com/mosop/cli.git
Fetching https://github.com/mosop/optarg.git
Fetching https://github.com/mosop/callback.git
Fetching https://github.com/mosop/string_inflection.git
Fetching https://github.com/elorest/compiled_license.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/TechMagister/liquid.cr.git
Fetching https://github.com/phoffer/inflector.cr.git
Fetching https://github.com/amberframework/micrate.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-mysql.git
Fetching https://github.com/will/crystal-pg.git   
Fetching https://github.com/stefanwille/crystal-redis.git
Fetching https://github.com/ysbaddaden/pool.git   
Fetching https://github.com/jwaldrip/shell-table.cr.git
Fetching https://github.com/jeromegn/slang.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/mosop/teeplate.git
Fetching https://github.com/veelenga/ameba.git
Installing amber_router (0.1.0)
Installing cli (0.7.0)
Installing optarg (0.5.8)
Installing callback (0.6.3)
Installing string_inflection (0.2.1)
Installing compiled_license (0.1.3)
Installing kilt (0.4.0)
Installing liquid (0.3.0)
Installing inflector (0.1.8)
Installing micrate (0.3.3)
Installing db (0.5.0)
Installing mysql (0.5.0)
Installing pg (0.15.0)
Installing redis (2.0.0)
Installing pool (0.2.3)
Installing shell-table (0.9.2)
Installing slang (1.7.1)
Installing sqlite3 (0.10.0)
Installing teeplate (0.6.1)
Installing ameba (0.7.0)
Postinstall make bin
bmaxwell@ubuntu01:~/Downloads/amber-stable$ make
Building amber in /home/bmaxwell/Downloads/amber-stable/bin/amber
_main.o: In function `__crystal_main':                
main_module:(.text+0xfe6): undefined reference to `SSL_library_init'
main_module:(.text+0xfeb): undefined reference to `SSL_load_error_strings'
main_module:(.text+0xff0): undefined reference to `OPENSSL_add_all_algorithms_noconf'
main_module:(.text+0xff5): undefined reference to `ERR_load_crypto_strings'
_main.o: In function `~procProc(Pointer(Void), Nil)@/usr/share/crystal/src/openssl/ssl/hostname_validation.cr:66':
main_module:(.text+0x2d3d2): undefined reference to `sk_free'
_main.o: In function `~proc2Proc(Pointer(Void), Nil)@/usr/share/crystal/src/openssl/ssl/hostname_validation.cr:66':
main_module:(.text+0x2d3e2): undefined reference to `sk_free'
_main.o: In function `~proc3Proc(Pointer(Void), Nil)@/usr/share/crystal/src/openssl/ssl/hostname_validation.cr:66':
main_module:(.text+0x2d3f2): undefined reference to `sk_free'
_main.o: In function `~proc4Proc(Pointer(Void), Nil)@/usr/share/crystal/src/openssl/ssl/hostname_validation.cr:66':
main_module:(.text+0x2d402): undefined reference to `sk_free'
_main.o: In function `~proc5Proc(Pointer(Void), Nil)@/usr/share/crystal/src/openssl/ssl/hostname_validation.cr:66':
main_module:(.text+0x2d412): undefined reference to `sk_free'
_main.o:main_module:(.text+0x2d422): more undefined references to `sk_free' follow
O-penS-S-L-5858S-S-L-5858C-ontext.o: In function `*OpenSSL::SSL::Context::default_method:Pointer(Void)':
OpenSSL::SSL::Context:(.text+0x2): undefined reference to `SSLv23_method'
O-penS-S-L-5858S-S-L-5858H-ostnameV-alidation.o: In function `*OpenSSL::SSL::HostnameValidation::matches_subject_alternative_name<String, Pointer(Void)>:OpenSSL::SSL::HostnameValidation::Result':
OpenSSL::SSL::HostnameValidation:(.text+0x126): undefined reference to `sk_pop_free'
OpenSSL::SSL::HostnameValidation:(.text+0x180): undefined reference to `sk_pop_free'
OpenSSL::SSL::HostnameValidation:(.text+0x19a): undefined reference to `sk_num'
OpenSSL::SSL::HostnameValidation:(.text+0x1e4): undefined reference to `sk_value'
OpenSSL::SSL::HostnameValidation:(.text+0x2e5): undefined reference to `sk_pop_free'
OpenSSL::SSL::HostnameValidation:(.text+0x382): undefined reference to `sk_pop_free'
OpenSSL::SSL::HostnameValidation:(.text+0x4b9): undefined reference to `sk_pop_free'
OpenSSL::SSL::HostnameValidation:(.text+0x59c): undefined reference to `sk_pop_free'
OpenSSL::SSL::HostnameValidation:(.text+0x66d): undefined reference to `sk_pop_free'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/bmaxwell/Downloads/amber-stable/bin/amber'  -rdynamic  -lsqlite3 -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lyaml -lpcre -lm -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
Makefile:17: recipe for target '/home/bmaxwell/Downloads/amber-stable/bin/amber' failed
make: *** [/home/bmaxwell/Downloads/amber-stable/bin/amber] Error 1

**Expected behavior:** 
make to work
**Actual behavior:** 
error related to  SSL
**Reproduces how often:**
Every time 
### Versions
bmaxwell@ubuntu01:~/Downloads/amber-stable$  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
bmaxwell@ubuntu01:~/Downloads/amber-stable$ uname -a
Linux ubuntu01 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
bmaxwell@ubuntu01:~/Downloads/amber-stable$ crystal -v
Crystal 0.25.1 [b782738ff] (2018-06-27)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu

amber 0.8.0

You can get this information from copy and pasting the output of `amber --version` and `crystal --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information
New to Crystal and Amber. Very excited about the language, but I've not been able to try Amber yet! Realize this is a young project, but thanks for your awesome work so far. This looks very promising.

**Comment by grig191** [comment]
It is not related to amber, but installing `libssl1.0-dev` should fix the issue!
