### ISSUE TITLE
Class names for referenced classes not correctly capitalized

### ISSUE THREAD

**Issue by ZeroPointEnergy** [amberframework/amber#907]
### Description

When I scaffold a resource which has a reference to a class with more than one word as it's name it does not get capitalized correctly.

### Steps to Reproduce

1.  amber new someapp
2.  cd someapp
3.  shards install
4.  amber generate scaffold **SomeResource** sometext:text
5.  amber generate scaffold SomeOtherResource sometext:text **some_resource:reference**
6.  amber watch

**Expected behavior:**

The application should compile and the view "src/views/some_other_resource/_form.slang" should contain:

`SomeResource.all.map{...`

**Actual behavior:**

The compilation fails because the class in the template is not capitalized correctly

`Some_resource.all.map{...`

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Amber CLI (amberframework.org) - v0.8.0
Crystal 0.25.0 (2018-06-25)

LLVM: 6.0.0
Default target: x86_64-pc-linux-gnu

**Comment by drujensen** [comment]
We should support submodules in the generators as well:

`amber g scaffold Api/Post ...` or `amber g scaffold Api::Post ...` 

A reference `api_post:ref` should map to `ApiPost`

A reference `api/post:ref` should map to `Api::Post`

wdyt?

**Comment by ZeroPointEnergy** [comment]
@drujensen The inflector seems to be capable of capitalizing api/post -> Api::Post correctly. At least in the _form reference field this would now work, but it obviously breaks in a lot of other places since the templates will use api/post as variable name. I guess this will take some work to get subclasses supported.

**Comment by drujensen** [comment]
@ZeroPointEnergy yeah, I just wanted to point this out since we will want support for both eventually.  Thanks for your PR. 💯
