### ISSUE TITLE
can't install on arch

### ISSUE THREAD

**Issue by cocodrino** [amberframework/amber#908]
Hi, good day I'm trying to install amber in my arch (manjaro actually) using yaourt and fails, also I tried compile by hand following the instructions in the amber page, with the make command I get (in both cases the message is the same)

```shell

➜  amber-stable sudo make install 
[sudo] password for yo: 
Building amber in /home/yo/Documentos/proyectos/amber/amber-stable/bin/amber
Error in src/amber/cli.cr:5: while requiring "./cli/commands"

require "./cli/commands"
^

in src/amber/cli/commands.cr:4: while requiring "./templates/template"

require "./templates/template"
^

in src/amber/cli/templates/template.cr:6: while requiring "./app"

require "./app"
^

in src/amber/cli/templates/app.cr:3: expanding macro

    directory "#{__DIR__}/app"
    ^~~~~~~~~

in lib/teeplate/src/lib/file_tree/macros/directory.cr:52: instantiating 'String:Class#build()'

s = String.build do |sb|
           ^~~~~

in /usr/lib/crystal/string.cr:269: instantiating 'String::Builder:Class#build(Int32)'

    String::Builder.build(capacity) do |builder|
                    ^~~~~

in /usr/lib/crystal/string.cr:269: instantiating 'String::Builder:Class#build(Int32)'

    String::Builder.build(capacity) do |builder|
                    ^~~~~

in lib/teeplate/src/lib/file_tree/macros/directory.cr:52: instantiating 'String:Class#build()'

s = String.build do |sb|
           ^~~~~

in lib/teeplate/src/lib/file_tree/macros/directory.cr:57: instantiating 'pack_ecr(Int32, String::Builder, String, String)'

      pack_ecr i, sb, abs, $1
      ^~~~~~~~

in lib/teeplate/src/lib/file_tree/macros/directory.cr:33: undefined method 'info' for File:Class

  ____files << ::Teeplate::StringData.new("#{rel}", io.to_s, File::Permissions.from_value(#{File.info(abs).permissions.value}))
```

do you know what could be the issue here??? thank you so much

**Comment by drujensen** [comment]
Looking at the api docs for Crystal 0.25.1 here  https://crystal-lang.org/api/0.25.1/File.html#info , you can see that there is a `File.info` class method.

What version of Crystal do you have?

**Comment by cocodrino** [comment]
hi @drujensen   thanks for the fast answer, seems that would be an issue with my crystal version...I've crystal 0.24.2, this is the last version in the arch repositories, I'm installing crystal with homebrew now, hopefully I can install it...thanks

**Comment by cocodrino** [comment]
by the way...how is the best way for manage versions and update crystal???

**Comment by faustinoaq** [comment]
Hi, I use https://github.com/pine/crenv by @pine :+1:

**Comment by cocodrino** [comment]
thank you so much guys, after update crystal I was able to install amber...works great...thank you

**Comment by faustinoaq** [comment]
BTW, you can use our AUR package as well, see: https://aur.archlinux.org/packages/amber/
