### ISSUE TITLE
Cannot define value for integer column from session

### ISSUE THREAD

**Issue by set** [amberframework/amber#911]
My post route method;
```
def grupEklePost
  grup = Gruplar.new
  grup.ad = params[:ad]
  grup.okul = session[:okulId]
  grup.save
  flash[:ok] = "ok"
  redirect_to "/gruplar"
end
```

My Model;
```
class Gruplar < Granite::Base
  adapter pg
  table_name gruplars

  # id : Int64 primary key is created for you
  field ad : String
  field okul : Int32
  timestamps
end
```
and when I ``amber watch``command;
````
instantiating 'OkulController#grupEklePost()'
in src/controllers/okul_controller.cr:92: no overload matches 'Gruplar#okul=' with type (String | Nil)
Overloads are:
 - Gruplar#okul=(okul : Union(Int32 | Nil))
Couldn't find overloads for these types:
 - Gruplar#okul=(okul : String)

   grup.okul = session[:okulId]
        ^~~~

Rerun with --error-trace to show a complete error trace.
01:55:53 Watcher    | (INFO) Compile time errors detected. Shutting down...
````
What is this?

**Comment by drujensen** [comment]
@set It looks like you are trying to assign a `(String | Nil)` to a `(Int32 | Nil)` union type.  You will need to convert it to an `Int32` first.  Consider using `to_i` method on the `String` class.  Also, you will need to verify that its not `Nil`.

```
if okuId =  session[:okulId]
  grup.okul = okuId. to_i
else
  # handle the case when its Nil here
end
```

Here is the API documentation for `to_i`: https://crystal-lang.org/api/0.25.1/String.html#to_i%28base%3AInt%3D10%2Cwhitespace%3Dtrue%2Cunderscore%3Dfalse%2Cprefix%3Dfalse%2Cstrict%3Dtrue%29-instance-method

**Comment by set** [comment]
@drujensen that's not working...
````
instantiating 'OkulController#gruplar()'
in src/controllers/okul_controller.cr:80: undefined method 'to_i' for Nil (compile-time type is (String | Nil)) (did you mean 'to_s'?)
````

**Comment by drujensen** [comment]
@set are you sure you checked for `Nil` first? If not, it will try to find the `to_i` method on `Nil` and this will throw an exception.

**Comment by set** [comment]
This method not working if user not create session. Crystal not compiling project because "you haven't got session[:okulId]" but I'm not starting project for create a session.

**Comment by robacarp** [comment]
@set were you able to get a solution to your problem?

**Comment by set** [comment]
@robacarp you must define session in initialize. Session will not work If you created another controller.
