### ISSUE TITLE
Permissions Problem During Manual Installation

### ISSUE THREAD

**Issue by jimm** [amberframework/amber#914]
### Description

I installed Amber on a Mac manually by downloading the tarball from Github and running `shards install` then `sudo make install`. The `sudo` is necessary because the `amber` binary is moved into `/usr/local/bin` which is owned by root. (I believe Homebrew changes the owner of `/usr/local/bin` but I don't use Homebrew.)

When I first ran `amber watch` it failed with the `you've found a bug in the Crystal compiler` error. The root problem was in the first line of output:

```
Error setting time to file '/Users/jimm/.cache/crystal/opt-local-lib-crystal-ecr-process.cr': Operation not permitted
```

The problem: the `sudo make install` operation installed some directories (listed below) in `~/.cache/crystal` as root --- I believe as a byproduct of the `build` make step. When I ran `amber watch` as an ordinary user, the attempt to update those files failed. Manually changing the owner of some files in `~/.cache/crystal` from root to myself fixed the problem.

The three directories created by the `build` target:
- Users-jimm-src-amber-stable-lib-teeplate-src-lib-file_tree-macros-directory.cr
- Users-jimm-src-amber-stable-src-amber-cli.cr
- opt-local-lib-crystal-ecr-process.cr

I believe the `build` target should make sure that all operations in the `~/.cache` directory are done using the logged-in user (you could use `$SUDO_USER` if it is defined, else use `$USER`). Either that, or the `install` target could detect the owner of the target directory and use the `sudo` command if necessary, meaning that I could run `make install` without the `sudo`.

### Steps to Reproduce

```sh
curl -L https://github.com/amberframework/amber/archive/stable.tar.gz | tar xz
cd amber-stable/
shards install
sudo make install   # <= here's the necessary deviation from Quick Start
cd /tmp
amber new pet-tracker
cd pet-tracker
amber g scaffold Pet name:string breed:string age:integer
amber db create migrate
amber watch
```

**Expected behavior:** `amber watch` should run with no errors.

**Actual behavior:** The permissions problem described above prevents the app from starting.

**Reproduces how often:** Every time, until permissions were fixed manually.

### Versions

- Amber v0.8.0
- Crystal v0.25.0 (installed via MacPorts)
- MacOS 10.13.5

**Comment by jimm** [comment]
### Additional Information

I use MacPorts, so when #890 is finished I won't have to install Amber manually.

**Comment by robacarp** [comment]
@jimm if you do `make && sudo make install`, is there any difference in the ownership of those files?

My guess is that the .cache/crystal folder is what needed the chown?

**Comment by jimm** [comment]
@robacarp your suggestion worked great: running `make && sudo make install` causes the permissions to be correct for the `.cache` files (owned by me) and the executable installation (owned by root). Why didn't I think of that much simpler solution instead of suggesting something much more complex? :-)

The `~/.cache/crystal` directory already existed before I installed Amber, so it was already owned by me and there were other directories in that directory owned by me. Only the three new subdirectories created by the `build` target were owned by root.

Perhaps a mention of this problem and/or a splitting of the Quick Install's make instruction into two (`make && sudo make install`) would be sufficient?

I'm happy to close this ticket. I'd offer to create a PR for the rewording of the Quick Install instructions but I'm not sure where that text lives.
