### ISSUE TITLE
How to configure CORS

### ISSUE THREAD

**Issue by hansy** [amberframework/amber#915]
Amber v0.8.0
Crystal 0.25.1

This might be a dumb question, but where and how do I initialize/configure CORS after enabling the CORS  pipeline (via `plug Amber::Pipe::CORS.new` in `config/routes.cr`? My browser is throwing the timeless "CORS header ‘Access-Control-Allow-Origin’ missing" error. Without me doing anything, doesn't the default initialization include the "*" Origin wildcard (which allows all Origins)? 

Am I missing something?

**Comment by drujensen** [comment]
@hansy the CORS pipeline requires `Origin` header.  You can see the `match` method here:
https://github.com/amberframework/amber/blob/master/src/amber/pipes/cors.cr#L120

So if you are using a curl command:
```
curl \
  -i 'http://localhost:3000/posts' \
  -X GET \
  -H "Content-Type:application/json" \
  -H 'Accept: application/json' \
  -H "Origin:localhost"
```

**Comment by drujensen** [comment]
maybe we just move https://github.com/amberframework/amber/blob/master/src/amber/pipes/cors.cr#L123 above https://github.com/amberframework/amber/blob/master/src/amber/pipes/cors.cr#L120

**Comment by hansy** [comment]
@drujensen Thanks for the quick reply! Yeah I saw it requires the Origin header; I'm sending the request through the browser, which automatically adds the Origin header (inspecting the request through the console confirms this). 

Actually, your suggestion to try via curl helped me debug. The issue was:

```
routes :api do
  resources "fields", FieldsController, except: [:show, :new, :edit]
end
```

I didn't realize `resources` requires a path (should be `resources "/fields"`), which was throwing everything off. My dumb ruby brain ftw. Sorry for the inconvenience and thank you for your time and contributions to this project.

**Comment by drujensen** [comment]
@hansy glad to hear you found it.  We tried to match rails in several areas to keep the learning curve low but there are some differences especially in the router.

I still would like to refactor this.  I don't like the method named `any?` to match `*`.   I find that confusing.

**Comment by robacarp** [comment]
> I didn't realize resources requires a path (should be resources "/fields")

@hansy I think this is something that can be improved with very little effort, thanks for pointing this out. Requiring a leading slash shouldn't be necessary.
