### ISSUE TITLE
Adding some utilities to database management

### ISSUE THREAD

**Issue by basilthegreat** [amberframework/amber#921]
Hi,

I would like to propose a feature that I would like to work on if a green light is given. I wanted to propose something like adding a command to `amber generate` that would generate a micrate migration that would alter the table, adjusting it to the parameters of the new model file. Any input would be appreciated :)

Thanks

**Comment by robacarp** [comment]
@basilthegreat can you elaborate more on what you're looking for? I'm not sure I follow.

**Comment by drujensen** [comment]
@basilthegreat You can create migrations using `amber g migration test` to create a new migration file.  Are you requesting something more?

**Comment by drujensen** [comment]
Closing since no response.  Please reopen if there was something else you were envisioning.
