### ISSUE TITLE
Consider moving Homebrew package to custom tap

### ISSUE THREAD

**Issue by paulcsmith** [amberframework/amber#928]
Re: 
https://gitter.im/crystal-lang/crystal?at=5b7431465762ee4fe57d1fde

The Amber homebrew package seems to be blocking Crystal releases. What do you think about removing the Homebrew package and using a custom tap instead? That way it won't block the Crystal release.

We've done this with Lucky and it has worked out well. It is one extra step (`brew tap luckyframework/homebrew-lucky`) but it is a one time thing. It also let's you release a new package whenever you want without waiting for Homebrew. What do you think?

**Comment by robacarp** [comment]
Resolved by https://github.com/Homebrew/homebrew-core/pull/31159 .

New tap is here: https://github.com/amberframework/homebrew-amber
