### ISSUE TITLE
State of Amber Framework

### ISSUE THREAD

**Issue by eliasjpr** [amberframework/amber#941]
To/all: 

We are coming together to address Amber current status and to keep propelling this open source project to success.

### First: Thank You Everyone For Making Amber Possible

First, we want to thank all of you for dedicating your precious time to the project, Amber is one of the best, easy to work, faster to develop frameworks for the Crystal Language thanks to your contributions. Amber is what it is great because of you! 

We specially want to send a shout out to @faustinoaq and @robacarp we cannot be more thankful for your time and contribution and specially the dedication to keep the project up to date and alive. You guys represents what Amber is. You mean a great deal to this project and for that we will be always thankful. Thank you!

### What's happening 

About the current status of Amber, last night the team had a discussion on what to focus next and we have set the following priorities:

- [x] Release Amber 0.9 - Done! [Insert Release Notes URL Here]
- [x] Triage current issues: We have have to close stale and addressed issue so we can move forward with a clean slate so if you have work on an issue, or if your question has been answered or the issue is no longer relevant please, leave your comment on the issue and pin Amber Gitter channel with the issue URL so the team can close it.
- [ ] Build a roadmap around improvements rather than features;
  - Improve Compilation time
  - Reduce size of compiled Amber project
  - Improve shard dependency graph
  - Split CLI from Amber lib
  - Optimize code to improve maintenance

### Get involved now!

We want to continue propelling Amber to success and we cannot do that without the community. We would like YOU to get involve from the beginning, now! We are open to listen to your thoughts and ideas to define the next upcoming roadmap themed `Improvements`.

This is the perfect time for you to contribute your thoughts and ideas.

### Why we are not building new features

We believe that Amber has good tooling to get any type of project going weather it is: API, Monolith, small or large. Amber works, it is stable, and it is fast! :rocket:. We want to allow Amber to scale in any organization, team or project to make that possible Amber needs to continue to improve, have solid foundation. So before we continue to add new awesome features we want to solidify the current ones.

**Comment by rishavs** [comment]
I am very happy with the way you guys have reorganized the project focus. kudos to you all. 
While I am not using Amber or Granite right now, anything that helps the Crystal community grow is good for us all.

**Comment by astupidnerd** [comment]
@eliasjpr I'm still sorta new to Crystal, and very new to Amber, but I think both of these things are amazing and I would love to see them succeed.

What is a good starting place for newcomers? How can I contribute?

**Comment by robacarp** [comment]
@astupidnerd contributions are always welcome, but [a collection of issues](https://github.com/amberframework/amber/issues?q=is%3Aissue+is%3Aopen+label%3Astatus%3Ahelp-wanted) is tagged help-wanted. 

If you're not confident about the way to solve a problem or want to get some input before investing time in a bigger bugfix, the gitter chat is a great way to collaborate.

**Comment by alexbottoni** [comment]
You have done a great work so far. Really impressive. Kudos!

In detail, I greatly appreciate the clean and modern design of the framework. It looks like that most of the lessons of Ruby on Rails, Sinatra, Django and other well-known frameworks have been learned and used. This makes Amber very modular and estensible (and readable/understandable).

At the moment, the main obstacle that keeps me from using Amber in the wild is the relative immaturity of the user management system (user registration, authentication and permission). An indipendent shard or a recipe devoted to this task (like Rails "Devise" or Django "AllAuth") will be of great help for the early adopters. I do NOT mean we need all of the Devise modules right now. We just need an "engine" like Devise to host and manage the upcoming modules. (See issue #580).

**Comment by eliasjpr** [comment]
Closing this issue because I think amber is one of the most healthiest projects in the crystal community
