### ISSUE TITLE
Reduce complexity by focusing amber generators on a single ORM?

### ISSUE THREAD

**Issue by robacarp** [amberframework/amber#942]
Amber generators ask _a lot_ of questions, and "which ORM are you using" is one of them.

In my experience with Rails, the only time I use generators is pretty early on in a project. Not everyone I talk to is this way, but I think it's true of most Rails developers.

I think it'd simplify the maintenance and growth of Amber to focus on providing for only one ORM in the generators, and providing documentation for how to re-wire an Amber project for other ORMs. I've used [Sequel](http://sequel.jeremyevans.net/) with Rails many times following a few quick and simple guidelines for how to update a project.

I don't have a strong opinion on which ORM, and there are several to choose from. Currently Amber supports [Granite](https://github.com/amberframework/granite), [Crecto](https://github.com/Crecto/crecto), and to a lesser extent, [Jennifer](https://github.com/imdrasil/jennifer.cr). [there are many more](https://github.com/veelenga/awesome-crystal#ormodm-extensions) and I'm unfamiliar with the landscape here.

Granite, being under the Amberframework banner, has some obvious advantages, but it also has some growth needed to make it functional enough to really support the future of a web framework. 

RFC.

**Comment by elorest** [comment]
I'd definitely prefer granite. It's been a year since I made any major contributions to the ORM though so I'll let @drujensen weight in on that. Some people preferred crecto so @drujensen spent a weekend or so and added that. Should be pretty easy to remove if we're agreed on it.

**Comment by elorest** [comment]
I'd definitely prefer granite. It's been a year since I made any major contributions to the ORM though so I'll let @drujensen weight in on that. Some people preferred crecto so @drujensen spent a weekend or so and added that. Should be pretty easy to remove if we're agreed on it.

**Comment by Thellior** [comment]
I think supporting one is more efficient because we can guarantee that it's working properly. And i think granite is fine for that because it's under our banner

**Comment by grig191** [comment]
@drujensen, it is very simple, I appreciate all your (Amber core team ) work, but I like whole idea of Ecto, so I will not like this idea.
Anyways, I understand the complexity that is added by second ORM, but I should give you my feedback.
Of course I will use Amber further even if you will decide to remove Crecto support

**Comment by grig191** [comment]
I also agree with @Thellior opinion, definitely, whole team will pay more attention to just one ORM increasing efficiency and decreasing number of bugs, BUT in future ( when Amber will be much more popular and with bigger core team ) support of different ORMs is very nice feature

**Comment by drujensen** [comment]
@grig191 Thanks, I'm glad it wasn't some other reason.  

The hardest part of this proposal is choosing which ORM since both were started from Core members.  Supporting both was the solution we made when we merged Kemalyst with Amber.  I lean toward Granite because its my baby and it's under the amberframework umbrella now.  But I understand the reasons someone would lean toward the Ecto solution.

My take is we are only removing this from the generators and the Crecto team could maintain the recipes in their project for Amber going forward.  @fridgerator WDYT?

**Comment by eliasjpr** [comment]
@drujensen @damianham maybe we can move the generators to an amber `recipe` so people can still use it just maintain it independently

**Comment by fridgerator** [comment]
To me personally it doesn't matter much.  I guess what matters is how many users are using Crecto with Amber.

If Crecto isnt available as a template, how would a recipe for it be managed in another repo?

**Comment by eliasjpr** [comment]
The community will be able to contribute freely to the generators via the recipes repo.

**Comment by damianham** [comment]
I think the important thing is for the core team to agree on the way forward before anyone puts in the effort to do the work.  As @eliasjpr points out generators can be maintained by the community via recipes.  IMO this would be the best way to remove the complexity of support for multiple builtin ORMs.

My 2 cents would be;

* app, scaffolding, controller, model, migration generators in ORM specific recipes
* internal cli generators for anything not ORM dependent e.g. auth, channel, error, error, mailer, socket (until we have a way of overriding generators in a default recipe with generators in a named recipe then all the internal generators would move to the default recipe)
* recipes as shards maintained by the community in their own github accounts and default recipes in github/amberframework
* amber new myapp uses a default recipe (e.g. amberframework/default_recipe)
* default recipe has no ORM (yes there may be valid use cases for that) 
* if the user gives a database engine with -d use default ORM recipe (e.g. amberframework/granite_recipe)
* if the user gives an ORM with -m use well known recipes for that ORM e.g.
    * granite - amberframework/granite_recipe
    * crecto - crecto/crecto_recipe
    * jennifer - imdrasil/jennifer_recipe
* maintain a list of community recipes that describe what recipes are available

I have already done the work to support recipes as shards in a github repo which bootstraps a new app with the recipe in the lib folder of the newly created app for generating scaffolding etc.  The question I still haven't worked out is how to override generators from a default recipe with generators in a recipe given with the -r cmd line arg but that can come later.

@fridgerator I think this answers your question - the Crecto maintainers would create and maintain the amber crecto recipe in the crecto github organisation.

**Comment by proyb6** [comment]
I have in mind to suggest **memory*** as a database for quick demo/developments which is definitely useful those who are unfamiliar with Amber and educations.

**Comment by eliasjpr** [comment]
@proyb6 sqlite3 offers something similar and is supported by the framework and most systems

**Comment by proyb6** [comment]
@eliasjpr It will be great as long as if any database is not installed/available, it will run on SQLite3 or memory database, could the  username and passwords be skip too? Perhaps, “demo” mode.

**Comment by hugopl** [comment]
I think since Crecto is now [no longer actively maintained](https://github.com/Crecto/crecto/commit/4bf83cbfc1fdf6cf4efef05ac0fe6c72b826d90f), keep only one ORM is a good idea, I submitted a MR removing Crecto to fix #1081 but it also removes the -m option from CLI, so I guess it also fixes this issue.
