### ISSUE TITLE
No Content-Type in response requests

### ISSUE THREAD

**Issue by blankoworld** [amberframework/amber#947]
Today I find something that goes wrong between Nginx and Amber : Content-type! It seems that Amber don't return any Content-Type (for the default example while using amber new myapp).

In fact, when I use HTTPS, I activate : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
I set it to "nosniff". Which imply that we need to return (in response) a Content-Type.

On given example, no Content-Type exist.

As someone said on gitter, it seems to be a bug. To avoid this problem, I make something like that thanks to @Thellior:

```crystal
class MyController < ApplicationController
  before_action do
    all { context.response.content_type = "text/html" }
  end

  def index
    render("index.slang")
  end
end
```

### Versions

I use Crystal 0.26 and Amber 0.9.0 under ArchLinux.

**Comment by eliasjpr** [comment]
This is interesting cause the `content-type` header is set based on these tests         context.response.headers["Content-Type"].should eq "text/html"

**Comment by eliasjpr** [comment]
I think I might have found the issue, not sure if you have but feel free to open a PR. I do not have time at the moment to fix this

**Comment by blankoworld** [comment]
I have the time but not the skills ^_^. I search a little bit, but I didn't find what could be the problem. That's why I asked on the Gitter first.

I will search next days again. For now I'm busy ;)

**Comment by eliasjpr** [comment]
I got you! @blankoworld I will be pushing a PR sometime today
