### ISSUE TITLE
Commented routes showing in CLI

### ISSUE THREAD

**Issue by acoustep** [amberframework/amber#951]
### Description

When commenting out a route and running `amber routes` the route still appears.

### Steps to Reproduce

1. Add `# get "/test", TestController, :index` to the `routes :web` block.
2. Run `amber routes`

**Expected behavior:** Route should not show in the routes table.

**Actual behavior:** Route shows in the routes table.

**Reproduces how often:** 
As far as I can tell 100% of the time when using `get` and `post`. 
Commenting out `resources` seems to work fine, though.

### Versions

Amber CLI (amberframework.org) - v0.9.0
Crystal 0.26.1 (2018-08-27)
Mac OSX 10.13.6

### Additional Information

I think this may be to do with how the routes CLI parses routes.cr - is it ignoring comments for get/post? I'm fairly new to the project so I'm not sure.

**Comment by robacarp** [comment]
@acoustep yeah, the `amber routes` command is a bit of a clever hack to run quickly, it doesn't actually load and include the routes so much as it [parses the text content of the routes file](https://github.com/amberframework/amber/blob/master/src/amber/cli/commands/routes.cr#L47-L55).

I'm sure this would be a quick fix.

**Comment by elorest** [comment]
Would be pretty easy to make it ignore lines with #.
