### ISSUE TITLE
amber watch failed on "Quick Start"

### ISSUE THREAD

**Issue by oshybrid** [amberframework/amber#971]
Got this error after starting amber watch (very new to web dev)

$ amber watch
11:43:11 Watcher    | (INFO) Watching 18 files (server reload)...
11:43:11 Watcher    | (INFO) Building project Pet-tracker...
ld: warning: directory not found for option '-L/opt/brew/lib'
ld: warning: directory not found for option '-L/opt/brew/lib'
ld: warning: directory not found for option '-L/opt/brew/lib'
ld: warning: directory not found for option '-L/opt/brew/lib'
ld: library not found for -lssl (this usually means you need to install the development package for libssl)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o '/Users/bradhutchins/pet-tracker/bin/pet-tracker'  -rdynamic  -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lyaml -lpcre -lgc -lpthread /usr/local/Cellar/crystal/0.26.1_1/src/ext/libcrystal.a -levent -liconv -ldl -L/usr/lib -L/usr/local/lib`
11:43:36 Watcher    | (INFO) Compile time errors detected. Shutting down...

Using...
MacBook Pro (15-inch, 2016), OSX 10.14

**Comment by faustinoaq** [comment]
Can you compile a simple crystal program?

Try this: 

```
crystal init app hello
cd hello
shards build
bin/hello
```

**Comment by faustinoaq** [comment]
Analyzing your logs, I think this is an openssl issue on macOS, see: https://github.com/crystal-lang/crystal/issues/6875

**Comment by elorest** [comment]
Thanks.

**Comment by manindragautam** [comment]
Try this:
`echo 'export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig' >> ~/.bash_profile`
