### ISSUE TITLE
Docker Tag for 0.11 missing

### ISSUE THREAD

**Issue by Meldanor** [amberframework/amber#981]
### Description

#980 fixed the Docker build, but currently there is no Version tag for `0.11`, only the `latest`. This makes it hard to use a fixed version of Amber, i.e. when the project uses `0.11`, but the latest is now `0.12` with a breaking change.

Solution: Tag the current image version of amber with 0.11.

**Comment by drujensen** [comment]
This should have happened automatically.  I will look into it.

**Comment by drujensen** [comment]
I manually pushed v0.11.1 docker image.  thanks for reporting this.
