### ISSUE TITLE
No overload matches 'Amber::Router::Cookies::Store#set'

### ISSUE THREAD

**Issue by bartblast** [amberframework/amber#982]
### Description

Setting a cookie with additional params, as given in the example in the docs here: https://docs.amberframework.org/amber/guides/controllers/cookies

cookies[:name] = {
   value:   "a yummy cookie",
   expires: 1.year.from_now,
   domain:  "domain.com"
 }

throws an error: no overload matches 'Amber::Router::Cookies::Store#set' with types Symbol, NamedTuple(value: String, expires: Time, domain: String)

Looking at the code there is no overload that handles the NamedTuple:
Amber::Router::Cookies::Store#[]=(Symbol, NamedTuple(value: String, expires: Time, domain: String))
(or similar)
which is needed to run the code as specified in the docs.

### Steps to Reproduce

Put this code in any controller action:
cookies[:name] = {
   value:   "a yummy cookie",
   expires: 1.year.from_now,
   domain:  "domain.com"
 }

and try to compile.

**Expected behavior:**

"name" cookie is set, without throwing an error.

**Actual behavior:**

Error: no overload matches 'Amber::Router::Cookies::Store#set' with types Symbol, NamedTuple(value: String, expires: Time, domain: String)

**Reproduces how often:**
All the time.

### Versions

Amber: 0.11.0
Crystal: 0.27.0

**Comment by drujensen** [comment]
https://github.com/amberframework/docs/pull/120

**Comment by drujensen** [comment]
@bartblast thanks for reporting this.  I updated the documentation with the latest changes.
