### ISSUE TITLE
Error on type model

### ISSUE THREAD

**Issue by nbouliol** [amberframework/amber#995]
### Description

Having a model called `Type` is not well supported

### Steps to Reproduce

I did

`amber g scaffold Type label:string`
other scaffolding, then
`amber watch`

**Actual behavior:** https://pastebin.com/P9En4Qsn

### Versions

```
→ amber --version
Amber CLI (amberframework.org) - v0.11.1

→ crystal --version
Crystal 0.27.0 (2018-11-04)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

**Comment by drujensen** [comment]
Yeah, there are several reserved words in Crystal and Amber.  Not sure the best way to deal with this except maybe check to see if someone is trying to use one and prevent it.

**Comment by eliasjpr** [comment]
I think the keyword `Type` might be reserved

**Comment by elorest** [comment]
Not sure if this is an issue we should worry about. There are multiple key words in most other frameworks including Rails, Phoenix that you just need to know not to use.

**Comment by drujensen** [comment]
@robacarp Is there a list of reserved words we should check for?

**Comment by robacarp** [comment]
Well, I'm not sure what all would be in an exhaustive list but it could start with Type, Array, Int32, etc. Plan for eventual completeness?

**Comment by nsuchy** [comment]
The list from that issue at least looks like a good start. Do we want to check for these words in https://github.com/amberframework/amber/blob/master/src/amber/cli/generators/scaffold.cr or at a higher level in the commands chain? Should we return an exception or a pretty console output? Working on a PR to close out this issue.
